### ISSUE TITLE
Global Variable in V8-Processor Action

### ISSUE THREAD

**Issue by CNX09** [apioo/fusio#100]
is there a way to create global variables in fusio, for use on V8-processors Action
such as the URL in the following screenshot. so the URL can be replace easily.
![image](https://user-images.githubusercontent.com/22588362/33002952-1cafcde2-cdea-11e7-86c8-4a0fe5bdb8f1.png)

**Comment by k42b3** [comment]
Hi, currently we have no way to define global variables in the V8 action. But at your http connection (`tki`) it is also possible to define a base url. In your action you can then simply use only `/api/getView/tenorAgreement` as uri. The http connection resolves then the url.
