### ISSUE TITLE
Unclear way of creating schema

### ISSUE THREAD

**Issue by koswarabilly** [apioo/fusio#101]
i am sorry in advanced, since this should not be an issue and should be labeled question.

```
{
"id": "http://acme.com/schema",
"type": "object",
"title": "schema",
"properties": {
"name": {
"type": "string"
},
"author": {
"$ref": "file:///author.json"
},
"date": {
"type": "string",
"format": "date-time"
}
}
}
```

as documented, what is id field? should i leave it as "http://acme.com/schema" or what should i put?
how can i test and validate the schema i created?

**Comment by k42b3** [comment]
Hi, no problem, so in general the id field contains an arbitrary uri, this means you can use the url of your website or something else. It is also possible to omit this field, Fusio uses then a fallback id.

To validate the schema you can use any online schema validator (i.e. https://www.jsonschemavalidator.net/). But also if you save a schema Fusio will validate it. In the end if you use a schema at a route it validate all incoming data after this schema.

**Comment by koswarabilly** [comment]
@k42b3  "In the end if you use a schema at a route it validate all incoming data after this schema."
the quoted sentence, what do you mean by incoming data? is it the respond from i get from making request? or the request it self is the incoming data?

**Comment by koswarabilly** [comment]
@k42b3 Thankyou for your explanation, the next thing i keep wondering is.. 
in your documentation, i found that fusio automatically generate documentation from schema, where can i find the documentation generated?

**Comment by k42b3** [comment]
Hi, yes the documentation is available in the public folder at `/documentation`. Since the latest release you can also look at the `/swagger-ui` folder. These apps generates a complete documentation based on your endpoints and schemas.

You can also take a look at the demo [documentation](https://demo.fusio-project.org/documentation/#!/api/todo) or [swagger-ui](https://demo.fusio-project.org/swagger-ui/).

**Comment by koswarabilly** [comment]
i can not find it...
![screenshot from 2017-11-27 13-12-21](https://user-images.githubusercontent.com/29243760/33253148-a77ad266-d374-11e7-9a12-59a4d9d3d432.png)

i havent update to the lastest so i guess i wont have `/swagger-ui`

**Comment by k42b3** [comment]
If you download the latest version, the `swagger-ui` folder is located inside the `public/` folder i.e. here in the [repository](https://github.com/apioo/fusio/tree/master/public)

**Comment by koswarabilly** [comment]
Thankyouu @k42b3
