### ISSUE TITLE
Documentation can not handle "type": ["type1", "type2"]

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#106]
Fusio Impl v1.1.5

```json
{
  "type": "object",
  "properties": {
     "name": {
       "type": ["string", "null"]
     }
  }
}
```

That kind of schema will throw
```
psx.ERROR: PHP Notice: Array to string conversion in my-project-path/vendor/psx/schema/src/PropertyType.php on line 992
```

I am using deploy. Have not test it with backend app yet.

**Comment by k42b3** [comment]
This was a problem with the underlying schema library. The latest release contains now also a fix so that it should be possible to use the type array notation.
