### ISSUE TITLE
Summarize deploy status in the end of deploy output

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#108]
Currently, when I have so many items to deploy, I have to scroll up to check whether it has any error or not.

My suggestion is to have summarized status in the end of the deploy message. The message should say whether the deploy is a success or has errors. If there are any errors, it should list what the errors are.

**Comment by k42b3** [comment]
in general I think this is a good idea. Currently the deploy looks like i.e.:

```
Deploy successful!
The following actions were done:

- [UPDATED] config
- [UPDATED] connection Default-Connection
- [UPDATED] schema Todo
- [UPDATED] schema Todo-Collection
- [UPDATED] schema Message
- [UPDATED] schema Test
- [UPDATED] action Todo_collection_php
- [UPDATED] action Todo_insert_php
- [UPDATED] action Todo_row_php
- [UPDATED] action Todo_delete_php
- [UPDATED] routes /todo
- [UPDATED] routes /todo/:todo_id
- [SKIPPED] Default-Connection resources/migration/v1_schema.php
```

so you would like to add a status message at the bottom whether no error occured? If an error occured the error message gets displayed beside the line i.e. `- [ERROR] schema Some error message` so I think we probably not need to repeat the error message at the bottom. Or would you like to see a list of all error messages again?

**Comment by zaniar** [comment]
If the whole deploy actions are successful, the message at the bottom should say so.
If some deploy actions are unsuccessful, the message at the bottom should say so, and repeat all the errors.

My main point is: I do not want to scroll way back to the top to check the errors, especially if I have hundred or more line of deploy message which most of them are successful actions & few of them are unsuccessful actions.

**Comment by k42b3** [comment]
Ok, I see, yes this seems useful especially for large deployments. I think adding a success message at the bottom should be no problem but I need to check whether we can collect all error messages to list them at the bottom.

**Comment by k42b3** [comment]
Implemented in the latest release
