### ISSUE TITLE
Routes Not Working

### ISSUE THREAD

**Issue by LaserStony** [apioo/fusio#109]
I create a new Route called "/libs" and tried running it with 'Welcome' Action but it gave a 404 Not Found Error. Same Error Occurred When I tried using any of the default APIs from [here](https://github.com/apioo/fusio#api). Also as the documentation says that it should contain "/todo" Route, wellll it doesn't. It only contains One i.e "/".

**Comment by k42b3** [comment]
Hi, so the `/todo` route gets created if you run the:

```
php bin/fusio deploy
```

command. The deploy command uses then the API config from the `.fusio.yml` file. But you are not required to run the deploy command you can also use the backend to configure your routes.

Regarding the `/libs` endpoint could you try to access the endpoint through `/index.php/libs` to see whether url rewriting works correct. Also do you see your `/libs` route if you run the following command:

```
php bin/fusio route
```

**Comment by LaserStony** [comment]
`php bin/fusio deploy` Worked, Now I can see todo routes but they don't work either. I tried using `index.php/libs` but still no use. I also ran `php bin/fusio route`. Still the Same error...

**Comment by k42b3** [comment]
Ok, could you show me the error response of the `/libs` request and also it would be helpful to see the php error logs, otherwise it is difficult to debug your issue. And plese check whether the `psx_debug` setting is true inside the `configuration.php` file, to display all errors.

**Comment by LaserStony** [comment]
After some working I got it to work by using `/public/index.php/libs`. But Why the Public. Also, How Can I fix it To use `/libs` instead of `/public/index.php/libs` on My Online Server.?

**Comment by k42b3** [comment]
To use urls like `/libs` you need to enable the apache [rewrite](http://httpd.apache.org/docs/2.4/mod/mod_rewrite.html) module (in case you use apache as webserver). In the `public/` folder there is a `.htaccess` file which gets then used by the webserver in case the module is activated.

Normally you need to configure your webserver that the `public/` folder is the web root folder. We have also an [example htdocs ](https://github.com/apioo/fusio/blob/master/build/apache.conf) config which shows how to do this. Then you need to adjust the `psx_url` config in the `configuration.php` file.

How do you access the default api endpoint?. Normally the `/backend` API endpoints are used by the backend app which is located in the `public/fusio` folder. Also pelase take a look at the [bootstrap](https://www.fusio-project.org/bootstrap) guide which should help to get started.

**Comment by LaserStony** [comment]
hmmm...
**Main .htaccess**
```
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]

# add a trailing slash to /wp-admin
RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

RewriteCond %{REQUEST_FILENAME} -f [OR]
RewriteCond %{REQUEST_FILENAME} -d
RewriteRule ^ - [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]
RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]
RewriteRule . index.php [L]

php_value memory_limit 256M
php_value upload_max_filesize 64M
php_value post_max_size 128M
php_value max_execution_time 300
php_value max_input_time 300

```
**api/public/.htaccess**
```
RewriteEngine On
RewriteBase /

RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule (.*) /index.php/$1 [L]

RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]

```

Can u tell me whats Wrong?.

Also, the thing that I asked about **URIFragments**. Can u tell me about it a little too..

**Comment by k42b3** [comment]
The `.htaccess` file looks good but I would recommend to create a separate vhost for your API. I.e. your blog is available at `myservice.com` and the API should be available at `api.myservice.com`. This can be done through a simple vhost entry like in the example htdocs which I have posted.

Basically uri fragments are the variable uri parts of an route i.e. if you create a route `/news/:year`, then you could access the year in the action through the `getUriFragment('year')` method. But how the uri fragment gets used depends on the action. If you use the SQL-Table action to create an API endpoint based on a database table you can get a row only by id. This means you need a route i.e. `/libs/:id`, then you can access a specific record with i.e. `/libs/4`.

**Comment by LaserStony** [comment]
Thanx! Now I get what are Uri Fragments. 
So, You are suggesting that I create A Sub-Domain api.someplace.com and install fusio there?

**Comment by k42b3** [comment]
Yes I would recommend to create a separate subdomain. Mhh regarding the routing proble, could you create a `info.php` file containing:

```php
<?php

phpinfo();
```

if you call this site you can check whether the `mod_rewrite` Module was loaded. Simply search for the string `mod_rewrite` or find the line `Loaded Modules`.

**Comment by LaserStony** [comment]
is there any way to customize the Api for Advance usage if one is unable to install V8 Extension.?

**Comment by k42b3** [comment]
Yes you can also use Fusio without V8, then you need to write you actions in simple PHP. Then you need to assign those [actions](https://github.com/apioo/fusio/blob/master/src/Todo/collection.php) to a route either through the backend UI or you can use the deploy mechanism.

**Comment by j2l** [comment]
To help debug @LaserStony (and my) route problem (see my other issue) i tried deploying Fusio locally (using Neard on Windows) and ended up with:
![image](https://user-images.githubusercontent.com/65325/35157350-01450de6-fd34-11e7-8eb2-2f84500f899d.png)
/fusio/public/ works fine though.

Your vhost example doesn't work for me.

Is there an exhaustive tutorial to deploy Fusio using any WAMP?

**Comment by chriskapp** [comment]
@dlinstedt thanks for the info, Iam not a cPanel user but I have added this notice to the documentation which should help new cPanel users: https://fusio.readthedocs.io/en/latest/installation.html#cpanel

**Comment by EvoPulseGaming** [comment]
I would like to reference this: https://github.com/apioo/fusio/issues/242
The last few comments, describe all the things to pay attention to to fix these issues with CPanel.

This should be closed

**Comment by chriskapp** [comment]
Yes, this should solve the issues regarding CPanel.
