### ISSUE TITLE
Use .env as configuration file

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#110]
By using `.env` file, it will be easy to move between servers.

Example case:
Development server have different database configuration than production server. With `.env` I can just `git pull` to deploy it in production server. I do not have to worry about configuration file being overwritten in development.

Also, the configuration should be accessible in `yaml` files.

Real case:
Currently I added [vlucas/phpdotenv](https://github.com/vlucas/phpdotenv) in my project. I just load it in `configuration.php`. The problem is I can not figure out how to use `$_ENV` variable in `connections.yaml` file.

**Comment by k42b3** [comment]
Hi, in general you can access normal env vars through `${env.my_env}` in all `yaml` files. In most production APIs I use also only env vars to configure the system. In the config through PHPs `getenv` or `$_ENV` and in the yaml through `${env.my_env}`. As I see it, the package helps only to set specific environment variables, I will need to check whats the best way is to integrate this package. Iam also aware of a symfony package which does this, at the weekend I will take a look at those.

**Comment by k42b3** [comment]
So with the last release we have added a new `.env` file, like you suggested, which includes now all sensitive values. Those values are loaded on demand in the `configuration.php` file. This should simplify deploying Fusio on different environments.

**Comment by webdevilopers** [comment]
Symfony has changed the usage for `.env` files:
* https://symfony.com/doc/current/configuration/dot-env-changes.html#what-changed-exactly

This behaviour can be easily updated by changing the version in composer:
```
{
  "name": "fusio/fusio",
  "description": "Fusio project",
  "homepage": "http://fusio-project.org",
  "license": "AGPL-3.0-only",
  "authors": [
    {
      "name": "Christoph Kappestein",
      "email": "christoph.kappestein@gmail.com",
      "homepage": "http://christoph.kappestein.com"
    }
  ],
  "require": {
    "php": ">=7.0",
    "fusio/impl": "^4.0",
    "fusio/adapter-http": "3.1.1",
    "symfony/dotenv": "4.2.*"
  },
  "require-dev": {
    "phpunit/phpunit": "^6.0",
    "guzzlehttp/guzzle": "^6.2"
  },
  "autoload": {
    "psr-4": {
      "App\\": "src/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "App\\Tests\\": "tests/"
    }
  }
}
```

And in the configuration file:

```php
<?php

if (!getenv('FUSIO_ENV')) {
    $dotenv = new \Symfony\Component\Dotenv\Dotenv();
#    $dotenv->load(__DIR__ . '/.env');
    $dotenv->loadEnv(__DIR__ . '/.env');
}
```

Please let me know if this is of interest.

**Comment by chriskapp** [comment]
Hi, yes this makes sense in the next version we will update the dotenv library to `4.2`. Iam not sure whether we want to use `load` or `loadEnv`. It looks like `load` simply loads a single .env file and `loadEnv` looks also at other .env files depending on the environment. In the end if we use the new version every user can easy change this at the configuration file.

**Comment by webdevilopers** [comment]
Exactly, that is how `loadEnv` works. Great news, looking forward to the next version! :)
