### ISSUE TITLE
Cockroachdb?

### ISSUE THREAD

**Issue by gustavotero7** [apioo/fusio#113]
Hi, can I use Cockroachdb with fusio?

**Comment by k42b3** [comment]
Hi, we have no extra Cockroachdb adapter but the Cockroachdb has a pgsql compatible API. This means you could use the `SQL` connection and choose the PostgreSQL type. Through this you should be able to connect to a Cockroachdb and execute normal SQL queries. That being said I have actually not tested whether this works correct so please let me know if you have any issues with this.

**Comment by k42b3** [comment]
I think the issue is solved, if you have any further problems please reopen this issue.
