### ISSUE TITLE
Import of petstore.yaml gives error

### ISSUE THREAD

**Issue by colorcube** [apioo/fusio#115]
I tried to import the openapi example file (and others too):

https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/yaml/petstore.yaml

Always I get this error:
/ must be of type object in /var/www/fusio/vendor/psx/schema/src/SchemaTraverser.php on line 439

Fusio (0.5.0)

**Comment by k42b3** [comment]
You should try to use the JSON version of the petstore example. At this point the importer does not understand the yaml format.

**Comment by k42b3** [comment]
So I think we should either improve the error message that YAML is not supported or better we detect and convert automatically the yaml format.

**Comment by k42b3** [comment]
In the latest 1.1.1 release we now parse also the YAML format
