### ISSUE TITLE
can't access route and can't delete it

### ISSUE THREAD

**Issue by j2l** [apioo/fusio#119]
Discovered Fusio on Softaculous (!). 
It looks very nice!

But it seems it has a hard time working with this kind of install (softaculous on shared server).
Following the video, I created a static action and a "/hello" route. I got a 404. Even after removing .htaccess

So as admin, I tried removing the route /hello and got:
.../fusio/public/index.php/backend/routes/73 403 (Forbidden)
  | (anonymous) | @ | fusio.min.js:51
-- | -- | -- | --
  | sendReq | @ | fusio.min.js:50
  | serverRequest | @ | fusio.min.js:50
  | processQueue | @ | fusio.min.js:51
  | (anonymous) | @ | fusio.min.js:51
  | $digest | @ | fusio.min.js:52
  | $apply | @ | fusio.min.js:52
  | (anonymous) | @ | fusio.min.js:55
  | defaultHandlerWrapper | @ | fusio.min.js:48
  | eventHandler

EDIT:
Access issue is a rewrite issue, I can access /fusio/public/index.php/hello(?i=1)
but I can't run commands or change htdocs on this server.
And still can't delete a route and/or action.
Any idea?

**Comment by k42b3** [comment]
Hi, thanks for the feedback. So the javascript error which you have posted looks like an `htaccess` issue that the `Authorization` header is not correctly forwarded to Fusio. Iam not really sure how Fusio is installed/configured on those servers but since you are not able to run commands on the server, it is maybe not possible for you to fix this issue. Iam connected with one of the Softaculous developer so I will try to contact them to fix those issues.

**Comment by j2l** [comment]
Thanks!
If you have 5min, you can try it on a free hosting, like profreehost.
I realize it's v0.5.0 installed via Softaculous.
I'm trying to "switch" files to RC8 but I wonder if migration is possible.

**Comment by j2l** [comment]
`.htaccess` is:
```
<IfModule mod_alias.c>
RedirectMatch 301 ^/fusio/$ http://reatest.ezyro.com/fusio/public
</IfModule>
```

**Comment by j2l** [comment]
I didn't thank you for this wonderful project and all you've done so far.
Congrats for this gem!

**Comment by softaculous** [comment]
@j2l Sorry for the inconvenience. We are in discussing about this issue with @k42b3 
Will notify you once we replicate and resolve this issue

**Comment by j2l** [comment]
Thanks @softaculous, for both replying (didn't know you're on github too) and for your everlasting tool :)

**Comment by k42b3** [comment]
@j2l I have just received a message from the softaculous devs that they have adjusted the `.htaccess` file. Since I have no way to verify those changes could you check whether this problem is now solved.

**Comment by j2l** [comment]
It's weird,
@softaculous script says it updated Fusio to 0.9.9 (thanks!) so I installed a new one under `/fusio099/`
![image](https://user-images.githubusercontent.com/65325/35033430-ea05460c-fb6a-11e7-97bb-fea01b94e93b.png)
![image](https://user-images.githubusercontent.com/65325/35033460-09a997f6-fb6b-11e7-8ae9-1cf9daf56d15.png)

 but installed version is still 0.5.0 in admin panel.
![image](https://user-images.githubusercontent.com/65325/35033710-ecfcb5f6-fb6b-11e7-86b1-d62d763a7162.png)

Consequently, `.htaccess` is still:
```
<IfModule mod_alias.c>
RedirectMatch 301 ^/fusio099/$ http://NNN.com/fusio099/public
</IfModule>
```
and rewrites are not working.

Additionaly, /public/developer/ throws a half baked result of:
```
Developer
Documentation
API
Account
Logout
Login
Logged in as {{ userName }}
powered by Fusio
```
with errors in console:
```
Uncaught SyntaxError: Unexpected token <
NNN.com/:16 Uncaught ReferenceError: fusioApp is not defined
    at NNN.com/:16
```

**Comment by k42b3** [comment]
@j2l ok unfortunately I cant not access those servers directly to help configure Fusio, but I will forward this to the developer.

In general the `0.5` is the version of the frontend app and not of Fusio itself. So I think the main problem is still that url rewrites are not working. Through the redirect we loose any `Authorization` header etc.

**Comment by j2l** [comment]
More investigation: 
Rewrite module is present (in php info):
![image](https://user-images.githubusercontent.com/65325/35140950-636de4ce-fcf9-11e7-8bd3-f7401a2f5abe.png)

and modifying .htaccess using `Deny From All` logically throws a 403.
I conclude that rewrite is active and working.

I wrote a forum post on profreehost and I'll keep you informed.

**Comment by j2l** [comment]
I tried another free hosting service and tried to upload fusio 1.0 (~7000 files, mainly symphony) and migrating a local db install.
I end up with
![image](https://user-images.githubusercontent.com/65325/35158382-2ec94464-fd37-11e7-9bad-467a32da5c29.png)
May or not be related.

**Comment by j2l** [comment]
After testing 100+ combinations, I found a temporary (weird) solution for the local WAMP at least:
in httpd.conf, disable the VHost by adding #:
```
#<VirtualHost *:80>
#    DocumentRoot "${NEARD_LIN_PATH}/www/"
#    ServerName localhost
#</VirtualHost>
```
and in the Vhost file set the Vhost according to your full windows path, using Unix slashes for path :
```
<VirtualHost *:80>
    DocumentRoot "E:/apps/neard/www/fusio/public"
    ServerName localhost
</VirtualHost>
```
now you can access:
http://localhost/developer/ (static section)
http://localhost/fusio/#!/action (admin)
http://localhost/hello/ (if you built this static route for testing purpose)

htaccess, i added QSA because I saw it somewhere:
```
        # rewrite
        RewriteEngine On
        RewriteBase /

        RewriteCond %{REQUEST_FILENAME} !-f
        RewriteCond %{REQUEST_FILENAME} !-d
        RewriteRule (.*) /index.php/$1 [L,QSA]

RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

No way to change httpd.conf on shared server so the problem is the same.
BUT now, you can delete a created route and action so I change my title accordingly.

**Comment by k42b3** [comment]
@j2l thanks for your effort and at least your local installation works now. As far as I understand the situation, softaculous runs on some shared hosting where it is not possible to change the httpd.conf (also not for the softaculous developers). So we only have the possibility to adjust this through a `.htaccess` file. I have suggested to try the following `.htaccess` file in the root folder to rewrite all requests to the `public/` folder, but Iam not sure whether this works.

```
RewriteEngine on
RewriteCond %{REQUEST_URI} !public/
RewriteRule (.*) /public/$1 [L]
```

Could you tell me the name of the shared hosting provider then I may create an account and test whether I can install Fusio there. That being said in general I would recommend to use a normal hosting solution where you can modify the httpd.conf and create a proper vhost entry.

The `putenv` error above is also a restriction from the shared hosting provider. To solve this your could remove the `.env` loading code inside the `configuration.php` line 3-4. In the config array you must then replace all `getenv` calls with actual values. Normally Fusio would read those values from the provided environment variables.

**Comment by j2l** [comment]
> Could you tell me the name of the shared hosting provider 

profreehost.com (reseller of byethost service).
Thanks for your help. I think softaculous is interesting to find "basic" users.

> RewriteEngine on
> RewriteCond %{REQUEST_URI} !public/
> RewriteRule (.*) /public/$1 [L]

results in a 500

**Comment by k42b3** [comment]
Ok, great, thanks I will check this out and see whether Iam able to install Fusio there.

**Comment by k42b3** [comment]
So I have tried to create an account there but let me tell you this service looks more like a scam. Iam not sure whether any user can run a productive service on such a platform. Ads everywhere and also uploading Fusio through FTP is probably not a good idea. But I have found a solution which works locally using the following `.htaccess`

```
RewriteEngine on
RewriteRule (.*) public/$1/
```

This redirects all requests to the public/ folder. But again I can only recommend to invest a few dollars for a simple virtual server where you can control the web server and set a proper document root. Also the development flow is not great since you need to manually update the database through phpmyadmin everytime something has changed, since you can not use the `deploy` command. So I will add a shared-hosting notice to the documentation with the `.htaccess` config above.

**Comment by k42b3** [comment]
I have added the shared-hosting chapter to the manual:
http://fusio.readthedocs.io/en/latest/installation.html#shared-hosting
this should point new users in the right direction. Unfortunately I have currently no better solution for you. But Iam also working on a service platform which lets you run Fusio simply in the cloud without any setup. But this project is currently in the pre-alpha stage ;)

**Comment by j2l** [comment]
Thank you!

> Ads everywhere and also uploading Fusio through FTP is probably not a good idea.

I don't see ads because I use an ad blocker but I trust you and I agree, VPS is better (but you must maintain OS, logs, and security). Cloud hosting is the way (congrats!) ... but I can't drop my money for now.
For the moment I want to test behavior with mobile on a shared hosting (limited bandwidth, distant server, service sleep, etc).

Thank you for the ```Rewrite```, it works!
May be doc should precise something like: Works on Fusio root .htaccess, not on `public/.htaccess`.

Also testing `developer/` returns:
`/projects/fusio/public/developer/css/fusio.min.css Failed to load resource: the server responded with a status of 404 (Not Found)`
I don't know how/why `projects/` get into the way.

Also it seems another problem is still present, may be related to rewrite:
`Uncaught ReferenceError: fusioApp is not defined`
throwing the infamous:
`Logged in as {{ userName }}`

Aah, almost there :)
Just need `/developer` and this issue is closed for me.

**Comment by j2l** [comment]
Thank you!

> Ads everywhere and also uploading Fusio through FTP is probably not a good idea.

I don't see ads because I use an ad blocker but I trust you and I agree, VPS is better (but you must maintain OS, logs, and security). Cloud hosting is the way (congrats!) ... but I can't drop my money for now.
For the moment I want to test behavior with mobile on a shared hosting (limited bandwidth, distant server, service sleep, etc).

Thank you for the ```Rewrite```, it works!
May be doc should precise something like: Works on Fusio root .htaccess, not on `public/.htaccess`.

Also testing `developer/` returns:
`/projects/fusio/public/developer/css/fusio.min.css Failed to load resource: the server responded with a status of 404 (Not Found)`
I don't know how/why `projects/` get into the way.

Also it seems another problem is still present, may be related to rewrite:
`Uncaught ReferenceError: fusioApp is not defined`
throwing the infamous:
`Logged in as {{ userName }}`

Aah, almost there :)
Just need /developer and this issue is closed for me.

**Comment by j2l** [comment]
No, I still can't delete a route :(
In console:
`fusio.min.js:51 DELETE http://api.NN.com/public/index.php/backend/routes/73 403 (Forbidden)`

**Comment by EvoPulseGaming** [comment]
https://github.com/apioo/fusio/issues/242

This should be closed, once the documentation has been updated, this shouldn't be an issue anymore.
(Using subdomain, changing document root in cpanel)

**Comment by chriskapp** [comment]
Yes, I will close this issue since the problems with CPanel are solved.
