### ISSUE TITLE
Add documentation for best practice DI container

### ISSUE THREAD

**Issue by christoph-bessei** [apioo/fusio#121]
The documentation mentions the [DI container](http://fusio.readthedocs.io/en/latest/development.html?highlight=container#php-class), but the example misses the usage of the DI container.
An example how to use the container and maybe some best practices would be nice.
E.g. [avoid ServiceLocator pattern](http://www.php-fig.org/psr/psr-11/meta/#4-recommended-usage-container-psr-and-the-service-locator) and additional functions of the [fusio container](https://github.com/apioo/fusio-impl/blob/master/src/Dependency/Container.php) compared to the [PSR-11 interface](http://www.php-fig.org/psr/psr-11/#3-interfaces)

**Comment by k42b3** [comment]
This is true I will probably make a complete new chapter regarding the usage of the DI container. So I will post any updates on this here. Basically the Fusio DI container implements the PSR-11 interface but has also some additional methods. 

In the action factory we currently use the `ServiceLocator` pattern that means your action can implement the `ContainerAwareInterface` and can then use all services from the container see (https://github.com/apioo/fusio-engine/blob/master/src/Factory/ContainerAwareInterface.php).
Actually at the beginnig this feature was only implemented for some internal actions and should not be used extensively. If there is a need we could also try to develop a cleaner way by i.e. auto injecting dependencies through the constructor but Iam not sure whether this is the best way.

**Comment by k42b3** [comment]
We have now a [business logic](http://fusio.readthedocs.io/en/latest/development/business_logic.html) chapter which explains more detailed how to use the DI container and also alternatives.
