### ISSUE TITLE
Unable to get to /developer/documentation/api using nginx

### ISSUE THREAD

**Issue by slifin** [apioo/fusio#122]
<img width="628" alt="screen shot 2018-01-18 at 09 39 21" src="https://user-images.githubusercontent.com/198857/35091054-7d649cfe-fc33-11e7-8c68-0fbdd0efe668.png">

So I'm at the bottom of this list but when I go to http://mylocalhost/fusio I get: 

```
{
    "success": false,
    "title": "PSX\\Framework\\Loader\\InvalidPathException",
    "message": "Unknown location in \/private\/var\/www\/fusio\/vendor\/psx\/framework\/src\/Loader\/Loader.php on line 121",
    "trace": "#0 \/private\/var\/www\/fusio\/vendor\/psx\/framework\/src\/Dispatch\/Dispatch.php(121): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Loader\\Context))\n#1 \/private\/var\/www\/fusio\/vendor\/psx\/framework\/src\/Environment\/WebServer\/Engine.php(47): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#2 \/private\/var\/www\/fusio\/vendor\/psx\/framework\/src\/Environment\/Environment.php(67): PSX\\Framework\\Environment\\WebServer\\Engine->serve(Object(PSX\\Framework\\Dispatch\\Dispatch), Object(PSX\\Framework\\Config\\Config))\n#3 \/private\/var\/www\/fusio\/public\/index.php(29): PSX\\Framework\\Environment\\Environment->serve()\n#4 {main}",
    "context": "117             $this-&gt;executeController($controller, $result, $response);\n118 \n119             return $controller;\n120         } else {\n<b>121             throw new InvalidPathException('Unknown location', $request);\n<\/b>122         }\n123     }\n124 \n125     \/**\n"
}
```

I've checked fusio_routes and there is no route for /fusio:

<img width="880" alt="screen shot 2018-01-18 at 09 40 49" src="https://user-images.githubusercontent.com/198857/35091153-b3f26bde-fc33-11e7-8980-813e29e1800b.png">

**Comment by slifin** [comment]
I'm using nginx php-fpm and mariadb to host locally

**Comment by slifin** [comment]
nginx config here: 

```
server {
	listen 80;
	server_name fusio;
	root /var/www/fusio/public;
	index index.php
	access_log off;
	error_log /var/log/nginx/fusio.log;
	location / {
		try_files $uri /index.php?$query_string;	
	}
	
	location ~ \.php$ {
		include /usr/local/etc/nginx/fastcgi.conf;
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_index index.php;
		fastcgi_param HTTP_PROXY "";
		fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}

}
```

**Comment by slifin** [comment]
I've tried `php bin/fusio deploy` and `php bin/fusio route` which has added some routes but not /fusio

**Comment by slifin** [comment]
based on a issue in this repo I've changed by config to:

```
server {
	listen 80;
	server_name fusio;
	root /var/www/fusio/public;
	index index.php
	access_log off;
	error_log /var/log/nginx/fusio.log;
	location / {
		try_files $uri $uri/ /index.php;
	}

	location ~ \.php$ {
		include /usr/local/etc/nginx/fastcgi.conf;
		fastcgi_pass 127.0.0.1:9000;
		fastcgi_index index.php;
		fastcgi_param HTTP_PROXY "";
		fastcgi_param SCRIPT_FILENAME $document_root/$fastcgi_script_name;
		fastcgi_param PATH_INFO $fastcgi_path_info;
	}

}
```
now after running adduser and install deploy etc, I get a 403 directly from nginx on the route /fusio but all the other routes work like they used to /todo etc

**Comment by slifin** [comment]
I needed to add index.htm to `index index.php` i.e. `index index.php index.htm` inside nginx config

**Comment by slifin** [comment]
I also needed to add index index.php index.htm and index.html i.e. `index index.php index.htm index.html`

**Comment by slifin** [comment]
I've got the same issue as the original comment at this route: /developer/documentation/api
```
{
    "success": false,
    "title": "PSX\\Framework\\Loader\\InvalidPathException",
    "message": "Unknown location in \/private\/var\/www\/fusio\/vendor\/psx\/framework\/src\/Loader\/Loader.php on line 121",
    "trace": "#0 \/private\/var\/www\/fusio\/vendor\/psx\/framework\/src\/Dispatch\/Dispatch.php(121): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Loader\\Context))\n#1 \/private\/var\/www\/fusio\/vendor\/psx\/framework\/src\/Environment\/WebServer\/Engine.php(47): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#2 \/private\/var\/www\/fusio\/vendor\/psx\/framework\/src\/Environment\/Environment.php(67): PSX\\Framework\\Environment\\WebServer\\Engine->serve(Object(PSX\\Framework\\Dispatch\\Dispatch), Object(PSX\\Framework\\Config\\Config))\n#3 \/private\/var\/www\/fusio\/public\/index.php(29): PSX\\Framework\\Environment\\Environment->serve()\n#4 {main}",
    "context": "117             $this-&gt;executeController($controller, $result, $response);\n118 \n119             return $controller;\n120         } else {\n<b>121             throw new InvalidPathException('Unknown location', $request);\n<\/b>122         }\n123     }\n124 \n125     \/**\n"
}
```

**Comment by k42b3** [comment]
Hi, this looks like nginx redirects the `/fusio` request to Fusio but `fusio/` is a folder in the `public/` folder which contains the js backend app. Coud you try to request the url with a trailing slash i.e. `http://mylocalhost/fusio/` or maybe the html file directly `http://mylocalhost/fusio/index.htm`. So Fusio has no `fusio/` route registered because it is simply a html js app in the `public/` folder.

**Comment by slifin** [comment]
yeah telling nginx to consider index.htm and index.html index files fixed /fusio, 
but weirdly I now have the same issue again but at the route:  /developer/documentation/api

**Comment by k42b3** [comment]
Yes the developer js app contains this `.htaccess` file since it runs in angularjs `html5Mode`, which basically means we can use urls like `/developer/documentation/bootstrap` and this request gets routed to the `/developer/index.html` angularjs app.

It would be great if you want to share the config. I could add this to the [manual](http://fusio.readthedocs.io/en/latest/installation.html#apache) with a new chapter nginx. Or if you like you can also make a pull request basically to this [file](https://github.com/apioo/fusio/blob/master/doc/installation.rst#apache).

**Comment by theraw** [comment]
try this
```
location / {
    try_files $uri $uri/ /index.php?a=$uri;
}
```

**Comment by slifin** [comment]
<img width="520" alt="screen shot 2018-01-30 at 11 22 58" src="https://user-images.githubusercontent.com/198857/35563831-f24dd64a-05af-11e8-828c-d3b6ca41f97a.png">
Thank you for the update, I get the above with 

`try_files $uri $uri/ /index.php?a=$uri;`

but again some routes work and some don't

**Comment by theraw** [comment]
`/backend` isn't working even for me! https://api.dope.al/backend
the same output even at https://demo.fusio-project.org/backend 

about routes they should work all just make sure you are using php7.0-fpm or 7.1+ 
this is my full nginx conf as of now
```bash
server {
        listen 80;
        root /hostdata/api.dope.al/public_html/fusio/public/;
        index index.html index.php index.htm;
        server_name api.dope.al www.api.dope.al;

        location / {
          access_log off;
          return 301 https://$host$request_uri;
        }
}
server {
        listen 443 http2;
        root /hostdata/api.dope.al/public_html/fusio/public/;
        index index.html index.php index.htm;
        server_name api.dope.al www.api.dope.al;

        ssl                       on;
        ssl_protocols             TLSv1.2 TLSv1.1 TLSv1;
        ssl_prefer_server_ciphers on;
        ssl_ciphers               'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
        ssl_certificate           /hostdata/api.dope.al/ssl/fullchain.pem;
        ssl_certificate_key       /hostdata/api.dope.al/ssl/privkey.pem;
        ssl_dhparam               /ssl/dh2048.pem;
        ssl_session_cache         shared:SSL:5m;
        ssl_session_timeout       1d;

        location / {
          index index.php index.html index.htm;
          try_files $uri $uri/ /index.php?a=$uri;
        }

        # =========================================
        # PHP.
        # =========================================
        location ~ \.php {
          try_files $uri /index.php =404;
          fastcgi_pass 127.0.0.1:9191;
          fastcgi_index index.php;
          fastcgi_read_timeout 90;
          fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
          include fastcgi_params;
        }
        # =========================================
        # END PHP.
        # =========================================
}
```
`
https://api.dope.al/images/ftp
`
also make sure you are using right url to `.env` ,
also if you haven't. then use `php bin/fusio deploy` to deploy routes

if with config which i provided nginx doesn't read `.php` files then just change ` location ~ \.php {` to `=>`  `location ~ \.php$ {`

**Comment by k42b3** [comment]
@theraw @slifin so `/backend` is no route which is available at Fusio. If you want to visit the backend app you should visit the `/fusio` endpoint. You can see all available backend endpoints at http://demo.fusio-project.org/internal/#!/page/about but you need to set an an `Authorization` header in order to make a request.

The nginx config looks good but I will also test a config so that I can finally add an nginx chapter to the documentation: http://fusio.readthedocs.io/en/latest/installation.html#web-server

**Comment by theraw** [comment]
@k42b3 yes nginx isn't like apache you should test it well because 1 wrong move can make big problems to someone ex if you don't use 
```
        location ~ /\.env {
          deny all;
        }
```
someone can download that .env from browser directly and it can cause big problems later as there is stored mysql password ..

sadly where was `api.dope.al` is a server which i use for tests purposes and i damaged its kernel a day ago and i lost what i installed so i will re'install fusio i will do tests as i will use it, so i will see may i can help with nginx configs more then that..

**Comment by LeongTitanFour** [comment]
Hi. I read and open http://fusio.readthedocs.io/en/latest/installation.html#web-server  but it is not existed. Please  give me the document , thank you!

**Comment by theraw** [comment]
https://fusio.readthedocs.io/en/latest/basic/installation.html#web-server

**Comment by vrdriver** [comment]
Hello, I used ngnix on my VPS too and had great difficulty installing/configuring it. In the end I gave up and used a different server running apache, and installing it through softaculous. Can you please update the documentation for nginx installations? Thanks.

**Comment by okedialf** [comment]
Any update on the nginx documentation?

**Comment by gamol90** [comment]
had this running on nginx except that a refresh in the url would return error instead of redirecting users to login page. Thinking it might be an nginx config

**Comment by chriskapp** [comment]
We have a working nginx config exmaple s. https://docs.fusio-project.org/docs/installation/nginx where also the reload works
