### ISSUE TITLE
Doctrine\\DBAL\\Exception\\InvalidFieldNameException

### ISSUE THREAD

**Issue by Lorderich** [apioo/fusio#129]
Hey, 

there is an error within the datbase connection to the fusio databases. 

This error makes at impossible to login or do anything else. 

The only working solution i found was remove the existing installation and reinstall. 

{
    "success": false,
    "title": "Doctrine\\DBAL\\Exception\\InvalidFieldNameException",
    "message": "An exception occurred while executing 'SELECT id,\n                       methods,\n                       path,\n                       controller\n                  FROM fusio_routes\n                 WHERE status = ? AND (priority IS NULL OR priority < 0x1000000) ORDER BY priority DESC' with params [1]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'priority' in 'where clause' in A:\\WebAPPS\\Apache\\htdocs\\API\\fusio\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php on line 71",
    "trace": "#0 A:\\WebAPPS\\Apache\\htdocs\\API\\fusio\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php(128): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 A:\\WebAPPS\\Apache\\htdocs\\API\\fusio\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Connection.php(855): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT id,\\n    ...', Array)\n#2 A:\\WebAPPS\\Apache\\htdocs\\API\\fusio\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Connection.php(785): Doctrine\\DBAL\\Connection->executeQuery('SELECT id,\\n    ...', Array, Array)\n#3 A:\\WebAPPS\\Apache\\htdocs\\API\\fusio\\vendor\\fusio\\impl\\src\\Loader\\RoutingParser.php(82): Doctrine\\DBAL\\Connection->fetchAll('SELECT id,\\n    ...', Array)\n#4 A:\\WebAPPS\\Apache\\htdocs\\API\\fusio\\vendor\\psx\\framework\\src\\Loader\\Loader.php(110): Fusio\\Impl\\Loader\\RoutingParser->resolve(Object(PSX\\Http\\Request), Object(PSX\\Framework\\Loader\\Context))\n#5 A:\\WebAPPS\\Apache\\htdocs\\API\\fusio\\vendor\\psx\\framework\\src\\Dispatch\\Dispatch.php(121): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Loader\\Context))\n#6 A:\\WebAPPS\\Apache\\htdocs\\API\\fusio\\vendor\\psx\\framework\\src\\Environment\\WebServer\\Engine.php(47): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#7 A:\\WebAPPS\\Apache\\htdocs\\API\\fusio\\vendor\\psx\\framework\\src\\Environment\\Environment.php(67): PSX\\Framework\\Environment\\WebServer\\Engine->serve(Object(PSX\\Framework\\Dispatch\\Dispatch), Object(PSX\\Framework\\Config\\Config))\n#8 A:\\WebAPPS\\Apache\\htdocs\\API\\fusio\\public\\index.php(29): PSX\\Framework\\Environment\\Environment->serve()\n#9 {main}",
    "context": "67  \n68              case '1054':\n69              case '1166':\n70              case '1611':\n<b>71                  return new Exception\\InvalidFieldNameException($message, $exception);\n<\/b>72  \n73              case '1052':\n74              case '1060':\n75              case '1110':\n"
}

**Comment by k42b3** [comment]
Hi, this looks like you have an older version of Fusio installed. The priority column was add with version `v2.0.1`. If you run the command `php bin/fusio` which version of Fusio does it show?

**Comment by k42b3** [comment]
It looks like this problem is solved, otherwise please feel free to reopen this issue.
