### ISSUE TITLE
PHP Fatal error:  Class 'PSX\Framework\Dependency\Container' not found in A:\WebAPPS\Apache\htdocs\API\fusio\vendor\psx\framework\src\Dependency\DefaultContainer.php on line 51

### ISSUE THREAD

**Issue by Lorderich** [apioo/fusio#130]
After a brand new installation the error appears. 

PHP Fatal error:  Class 'PSX\Framework\Dependency\Container' not found in A:\WebAPPS\Apache\htdocs\API\fusio\vendor\psx\framework\src\Dependency\DefaultContainer.php on line 51

**Comment by k42b3** [comment]
Hi, this looks like you have an older version of the `psx/framework` package installed. Could you run the command `composer show` to check the installed version, it should be at least `v4.0.1`. Have you installed Fusio through the released zip file or through composer?

**Comment by k42b3** [comment]
It looks like this problem is solved, otherwise please feel free to reopen this issue.
