### ISSUE TITLE
Password that starts with $ will not be recognized.

### ISSUE THREAD

**Issue by iDevid** [apioo/fusio#133]
I generated a random password for fusio user that starts with $, the install script doesn't recognize it and it proceeds without a password.

**Comment by k42b3** [comment]
Hi, so if you are using the `php bin/fusio adduser` command with the password argument it could be that you shell tries to substitute a value which starts with $ as variable so you may need to escape this character.

**Comment by iDevid** [comment]
I had this error during the fusio db install script

**Comment by k42b3** [comment]
mhh ok, could you tell me th steps to reproduce this error? Or have you simply run the `php bin/fusio install` command and then an error occured?

**Comment by iDevid** [comment]
I simply run php bin/fusio install with a mysql password that contains $. If the $ will be in the middle of the password, it will be truncated.

**Comment by k42b3** [comment]
Ok, then I have misunderstood the question, I thought you mean a user password instead of a mysql password. I will try to reproduce the issue but I guess the `$...` gets substituted with a variable name either in the `.env` file or somewhere else. But I will take a look at it.

**Comment by k42b3** [comment]
Hi, so I could reproduce the problem and in the .env file you need to use single quotes instead of double quest because otherwise the the value gets substituted with a variable name. I.e. the following does not work:

```
FUSIO_DB_PW="test$test"
```

instead you need to use the:

```
FUSIO_DB_PW='test$test'
```
