### ISSUE TITLE
Action doesn't auto-recognize column type from query result

### ISSUE THREAD

**Issue by irvanmohamad** [apioo/fusio#134]
I tried to follow instructions in https://www.youtube.com/watch?v=k5bFhVOjfiY but the result seems to be different

Suppose that the action code is

```
var connection = connector.get("conn");

var totalCount = connection.fetchColumn("SELECT COUNT(*) FROM some_table LIMIT 1");
var result = connection.fetchAll("SELECT * FROM sometable LIMIT 1");
response.setBody({
    totalCount: totalCount,
    result: result
});
```

The some_table columns are:
- customerid: integer
- firstname: string
- phone: json

The result should be like this in the video tutorial above

```
{
    "totalCount": 1,
    "result": [
        {
            "customerid": 1,
            "firstname": "RNPOJG",
            "phone": ["081221441144","0812345129"]
        }
    ]
}
```

But mine is:

```
{
    "totalCount": 1,
    "result": [
        {
            "customerid": "1",
            "firstname": "RNPOJG",
            "phone": "[\"081221441144\",\"0812345129\"]"
        }
    ]
}
```

**Comment by k42b3** [comment]
Hi, the `fetchAll` method only executes a SQL query and returns the response without modifing any value. So in your case you would need to transform those values manually like i.e.:

```javascript
var result = connection.fetchAll("SELECT * FROM sometable LIMIT 1");

result = result.map(function(row){
    row['customerid'] = parseInt(row['customerid']);
    row['phone'] = JSON.parse(row['phone']);

    return row;
});
```

**Comment by irvanmohamad** [comment]
Done 👍  Thank you very much

**Comment by dgambin** [comment]
Hi,

As I can see, the code in SQLSelect.php (older version, without convertRow function) also uses fetchAll but the response is obviously converted somewhere because I get all my int columns like int, not like string. Is there a function doing it?

regards, dejan
