### ISSUE TITLE
Schema migration during development

### ISSUE THREAD

**Issue by christoph-bessei** [apioo/fusio#140]
**Feature**
Could we force fusio to execute the changed migration file, if ```FUSIO_ENV```is set to ```dev```? 
Fusio already detects content changes in migration files (fileHash is stored in ```fusio_deploy_migration```) during ```fusio deploy```, so this should probably be easy.

**Use case**
During development I normally change a migration file multiple times (e.g. fix a small bug, forgot something, ...), but don't want to add new migration file for each small change.
But currently ```fusio deploy``` ignores the changed file, so I have to delete the entry in ```fusio_deploy_migration```, before I call ```fusio deploy```.

**Comment by k42b3** [comment]
In the latest release we have now a force flag at the deploy command i.e. `bin/fusio deploy -f` which always executes the migration file. This should help to simplify the development process.
