### ISSUE TITLE
Field name in fusio_action too short for nested PHP class actions

### ISSUE THREAD

**Issue by christoph-bessei** [apioo/fusio#141]
The field ```name``` in the table ```fusio_action``` is currently restricted to 64 characters.
This could cause problems (deploy fails), if the a PHP class action with a long namespace is used.
E.g. ```C3\LongCustomerName\LongProjectName\Action\SubFolder1\GetCollectionAction```

Is there a reason for the 64 character restriction or can we change the field length to 100 oder 200 characters?

**Comment by k42b3** [comment]
So there is no explicit reason, we can simply increase the length of the column in the next release. I think we should set it to 255 wich is the same length as the `class` column.

**Comment by k42b3** [comment]
In the latest 1.1.2 release we have increased the column length.
