### ISSUE TITLE
Preflight OPTIONS request fails for routes without get

### ISSUE THREAD

**Issue by christoph-bessei** [apioo/fusio#142]
Currently it's not possible to execute a POST/PATCH/PUT CORS request with an OPTIONS Preflight request, if the route has no endpoint for GET requests.

Reason:
[AssertMethod](https://github.com/apioo/fusio-impl/blob/e876cec766906f76896380a3b0e8e84f54d32138/src/Filter/AssertMethod.php#L70) sets the ```methodName``` to GET in case of an OPTIONS request.
The following database look up with ```$this->routesMethodService->getMethod($routeId, $version, $methodName);``` returns an empty result, because there's not GET endpoint and then the request fails, because there's no method allowed.

Workaround:
Add an empty GET endpoint to the route

**Comment by k42b3** [comment]
This is true, basically we do this only to get a schema from a method since we only define a schema for GET, POST, PUT, DELETE and PATCH methods. Maybe we should check there the available request methods and simply use the first available request method.

**Comment by k42b3** [comment]
This issue is now fixed in the latest 1.1.2 release.
