### ISSUE TITLE
Database transaction

### ISSUE THREAD

**Issue by koswarabilly** [apioo/fusio#144]
Mark this as a question,
does fusio support database transaction which have system as the following image
![transaction_states](https://user-images.githubusercontent.com/29243760/38476342-6a6b8e6c-3bd7-11e8-81df-276468d53bbf.png)

if it does, give me some tips and hint of how to use it
thankyou

**Comment by k42b3** [comment]
Hi,

so basically this dependes also on the database which you use but in general this is supported. I.e. inside an action you can easily write code in a transaction like:

```
/** @var \Doctrine\DBAL\Connection $connection */
$connection = $connector->getConnection('Default-Connection'); 

try {
    $connection->beginTransaction();

    // do multiple SQL queries with rollback on failure

    $connection->commit();
} catch (\Throwable $e) {
    $connection->rollBack();
}

```

**Comment by koswarabilly** [comment]
@k42b3 Thankyou so much
