### ISSUE TITLE
Creating users but always get an Authentication error message

### ISSUE THREAD

**Issue by PluginIO** [apioo/fusio#147]
I have gone through the manual installation process on a Bitnami LAMP instance with PHP 7.1.14 on AWS EC2. I didn't want to redirect the virtual domains yet since I don't want the service at the www root, and so I have currently omitted that section and access the login via /public/fusio/index.htm#!/login page.

I can see the Fusio mysql database entries and I can create users, I see those users in the database although when I try to login as one of those user, I always get an Authentication error message.

This also seems to have resulted in some configuration changes that cause the public/index.php to return a 500 error and the public/fusio/ does not automatically load the index.htm page, but rather it lists the folder contents that includes the index.htm file. 👎

**Comment by k42b3** [comment]
Hi, mhh if you login at the backend, could you take a look at the response from the `/backend/token` request, maybe your apache has the mod_rewrite module not enabled please take a look at:
http://fusio.readthedocs.io/en/latest/installation.html#backend

Regarding the loading of the index.htm inside the `public/fusio/` folder, this looks like a web server configuration problem since Fusio can not change such a behaviour. Also could you take a look at the error logs of the web server maybe there are some useful information to further debug the problem.

**Comment by PluginIO** [comment]
The error that I am receiving pertains to the permissions and so I'm wondering if you can shed any light on this. When I look at the permissions of the folders using ```stat``` I see that they are setup as per the installation documentation and should be writable.

![capture](https://user-images.githubusercontent.com/1716106/39040180-c125399c-447e-11e8-89ed-752f330f483c.PNG)

**Comment by PluginIO** [comment]
So, I did **another** migration to a plain Ubuntu 64-bit instance (had to setup all of the LAMP stack manually)
```
sudo su
apt-get update && apt-get upgrade
apt-get install apache2
apt-get install python-software-properties
add-apt-repository ppa:ondrej/php
apt-get update
apt-get install php7.2
php -v
apt-get install php-pear php7.2-curl php7.2-dev php7.2-gd php7.2-mbstring php7.2-zip php7.2-mysql php7.2-xml
systemctl restart apache2
pecl install apcu
echo "extension=apcu.so" | tee -a /etc/php/7.2/mods-available/cache.ini
ln -s /etc/php/7.2/mods-available/cache.ini /etc/php/7.2/apache2/conf.d/30-cache.ini
systemctl restart apache2

apt-get -y install gcc make autoconf libc-dev pkg-config
apt-get -y install libmcrypt-dev
pecl install mcrypt-1.0.1

[Enter]

bash -c "echo extension=/usr/lib/php/20170718/mcrypt.so > /etc/php/7.2/cli/conf.d/mcrypt.ini"
bash -c "echo extension=/usr/lib/php/20170718/mcrypt.so > /etc/php/7.2/apache2/conf.d/mcrypt.ini"

php -i | grep "mcrypt"

apt-get install mysql-server

sudo apt-get install git-core

apt install composer

apt-get update --fix-missing

cd /var/www/html/

wget https://github.com/apioo/fusio/releases/download/v1.1.2/fusio_1.1.2.zip

apt-install unzip

unzip fusio_1.1.2.zip

mysql -u root -p

[Enter password]

create database fusio;
exit

vim env
[Set url and mysql password]

php bin/fusio install
php bin/fusio adduser

[Add new user]

chown -R www-data: cache/
vim /etc/apache2/sites-available/000-default.conf

[Set the virtual root directory]

systemctl restart apache2
```

Finally got the graph view, tried to add an action and immediately see the following error:

```
An exception occurred while executing 'INSERT INTO fusio_audit (refId, event, ip, message, content, date) VALUES (?, ?, ?, ?, ?, ?)' with params ["2", "action.create", "86.1.36.121", "Created action test-action", "{\"status\":1,\"name\":\"test-action\",\"class\":\"Fusio\\\\Adapter\\\\Util\\\\Action\\\\UtilStaticResponse\",\"engine\":\"Fusio\\\\Engine\\\\Factory\\\\Resolver\\\\PhpClass\",\"config\":null,\"date\":\"2018-04-20 14:24:19\"}", "2018-04-20 14:24:19"]: SQLSTATE[HY000]: General error: 1364 Field 'appId' doesn't have a default value in /var/www/html/fusio/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 115
```
