### ISSUE TITLE
Remove

### ISSUE THREAD

**Issue by emresaracoglu** [apioo/fusio#151]
Hi,

How I can uninstall from server?

I tried but didt work.

`composer remove fusio/fusio`

**Comment by k42b3** [comment]
Hi, to remove Fusio you can simply remove the folder i.e. with [`rm`](http://man7.org/linux/man-pages/man1/rm.1.html). Through composer you could only remove the `fusio/impl` package but this does not remove all files. Also you may need to drop the databases which you have used for Fusio.

**Comment by emresaracoglu** [comment]
I understand thank you @k42b3 👍
