### ISSUE TITLE
Error during installation of Fusio

### ISSUE THREAD

**Issue by jan-sp** [apioo/fusio#157]
Hi,

I have an issue during the installation of fusio.
The setup of the environment is as follow

- Ubuntu server 18.04 LTS
- Databaseserver
Server: Localhost via UNIX socket
Servertype: MySQL
Serverversie: 5.7.22-0ubuntu18.04.1 - (Ubuntu)
Protocolversie: 10
Gebruiker: root@localhost
Karakterset van server: UTF-8 Unicode (utf8)

- Webserver
Apache/2.4.29 (Ubuntu)
Clientversie van database: libmysql - mysqlnd 5.0.12-dev - 20150407 - $Id: 38fea24f2847fa7519001be390c98ae0acafe387 $
PHP-uitbreiding: mysqliDocumentatie curlDocumentatie mbstringDocumentatie
PHP-versie: 7.2.5-0ubuntu0.18.04.1

When I try to execute the install command, I get some errors (see below).  Any suggestions how I can resolve this problem or figure out what can be the cause?

Tx in advance
Jan

`php fusio install

In AbstractMySQLDriver.php line 103:

  An exception occured in driver: SQLSTATE[HY000] [2002] Invalid argument

In PDOConnection.php line 47:

  SQLSTATE[HY000] [2002] Invalid argument

In PDOConnection.php line 43:

  SQLSTATE[HY000] [2002] Invalid argument

system:install [-p|--preview]
`

**Comment by chriskapp** [comment]
Hi, mhh this could be a problem that the default mysql port is maybe not used. Does your mysql server may run on another port then `3306`? You can also specify the port in the `configuration.php` file:

```
    'psx_connection'          => [
        'dbname'              => getenv('FUSIO_DB_NAME'),
        'user'                => getenv('FUSIO_DB_USER'),
        'password'            => getenv('FUSIO_DB_PW'),
        'host'                => getenv('FUSIO_DB_HOST'),
        'port'                => 1234,
        'driver'              => 'pdo_mysql',
    ],
```

**Comment by jan-sp** [comment]
Hi,

No SQL listens on the default port.
tcp        0      0 127.0.0.1:3306          0.0.0.0:*               LISTEN
    1249/mysqld




-- 
Mvg,

Jan Speecke
tel: 0477/46.26.91


2018-05-25 19:02 GMT+02:00 Christoph Kappestein <notifications@github.com>:

**Comment by chriskapp** [comment]
Ok, could you take a look at the PHP error logs which maybe contains a complete stack trace with more information about the problem. To check whether the problem comes from Fusio or is a general problem, you could also create a `test_connect.php` script which simply opens up a PDO connection to your mysql server i.e.:

```php
$dsn = 'mysql:dbname=testdb;host=127.0.0.1';
$user = 'dbuser';
$password = 'dbpass';
$dbh = new PDO($dsn, $user, $password);
```

If you call this script through the web server it should not throw an exception.

**Comment by jan-sp** [comment]
Hi,

I've changed the entry FUSIO_DB_HOST= in de .env file to 127.0.0.1 in stead of using name of the machine.  After this modification, installation continues and de Fusio DB is created.

Tx for the advise

Best regards
Jan
