### ISSUE TITLE
Add UI panel

### ISSUE THREAD

**Issue by chriskapp** [apioo/fusio#166]
We should evaluate whether we add a UI Panel where a user can define a UI representation for a specific JsonSchema. We should take a look at the [react-jsonschema-form](https://github.com/mozilla-services/react-jsonschema-form) or [jsonforms](https://jsonforms.io/) project which provides already a JSON vocabular to define an UI based on a JsonSchema. From there it would be possible to implement this in other GUI frameworks like i.e. AngularJS, AndroidApp or even something like JavaFX.

This would have the advantage that we define the form on the server-side and in case the schema updates the form inside the app updates also automatically without changing the code.

Besides create a new backend admin panel we could also create a new button at the schema panel where it is possible to provide a UI form. We also need a new public route i.e. `/documentation/ui/:schema_name` where a user can simply request the JsonSchema with the corresponding UI data (if provided).

**Comment by chriskapp** [comment]
This is now implemented in the latest release. @LaserStony I think the feature you are describing is a little bit different from this issue. If I understand you correctly you would like to automatically generate a JsonSchema based on an action response. This is also a good idea which we could build i.e. into the action designer but please create a separate issue for this. This issue is more about form generation for an specific endpoint.

**Comment by LaserStony** [comment]
hmmm.. Ok... Will do if you say so...
