### ISSUE TITLE
OAuth2 endpoint add Client Credentials Grant

### ISSUE THREAD

**Issue by chriskapp** [apioo/fusio#172]
Currently our OAuth2 endpoint supports only the following grants:

* Authorization Code Grant (https://tools.ietf.org/html/rfc6749#section-4.1)
* Resource Owner Password Credentials Grant (https://tools.ietf.org/html/rfc6749#section-4.3)

we should add also the **Client Credentials Grant** so that its possible to obtain an access token only with the app key/secret. Then every action is assigned to the user which has created the app and it is not possible to use the app under another user account.

**Comment by LaserStony** [comment]
Ooo... That would be quiet handy... It would seriously make the outcome quiet handy...

**Comment by chriskapp** [comment]
This is now implemented in the latest release
