### ISSUE TITLE
Empty /whoami response

### ISSUE THREAD

**Issue by kidino** [apioo/fusio#175]
I am getting empty `whoami` response. I logged in to my `/fusio`. I got in. But the whoami returned no content / data. And because of that, 

* there is no username on the top right
* every insert error will show an error relating to inserting data to fusio_audit, probably because there is no userId or something

What would have caused this and how do I fix it? Or did I install this wrong?

**Comment by chriskapp** [comment]
Hi, could you show me the concrete error message so that I can further debug the problem. Maybe you have some mysql or php error log?

**Comment by EvoPulseGaming** [comment]
This must be a user error, also no reply. I've installed and reinstalled even migrated databases without issues. This can probably be closed
