### ISSUE TITLE
Connection Class = SQL, Type : Oracle Database - Not possible to set SERVICE_ NAME only SID

### ISSUE THREAD

**Issue by MartinHajducik** [apioo/fusio#183]
Hello ,

Recently I've downloaded this nice tool (version = 1.3.0), and I was trying to set new connection with Oracle Database type. 

But there is an issues if you have to use SERVICE_NAME instead of SID, because when you use create form modal window, for Oracle DB type you can specify only host,username, password, and database. Which is by default used as SID for DBAL Driver vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractOracleDriver.php 

Therefore for quick fix, I've adjusted mentioned DBAL driver around line 127 

//$service = 'SID=' . $serviceName;
  $service = $serviceName;

To make it work now you have to put  below in database input field.

SID=<sid id>
or
SERVICE_NAME=<service name>

I am not so experienced so I am writing it here , hopefully author or somebody else can add another parameter $params['servicename'] to createform for new Connection.

**Comment by chriskapp** [comment]
Hi, thanks for the feedback. So in general the `SQL` connection provides a simple way to connect to most databases. In your case you could try to use the `SQL (advanced)` connection where you can configure the complete connection string i.e.: `oci8://localhost:1521/db?servicename=your_service_name`

You can get more information about the available configuration at:
https://www.doctrine-project.org/projects/doctrine-dbal/en/2.7/reference/configuration.html#connecting-using-a-url

**Comment by MartinHajducik** [comment]
Hi,

Thanks for info. It is working now with SQL Advanced type and connection URL format 

oci8://username:password@examplehost.com:1521/SERVICE_NAME=nameofservice

**Comment by chriskapp** [comment]
Ok, great I will close this issue since it looks like there is nothing more todo here.
