### ISSUE TITLE
Restore password 

### ISSUE THREAD

**Issue by jsalazar10** [apioo/fusio#187]
Hi

I notice that Fusio doesn't have a method to recover application passwords in case you forget it, please in future implementations can you build it.

**Comment by amig** [comment]
Any update on this issue?

**Comment by chriskapp** [comment]
Hi, so besides the normal login a user can also login through a remote provider i.e. Google or Github. In this context changing/restoring a password does not really make sense. So Iam currently not sure whats the best way to handle this case. Probably we need a new "restore" endpoint where the user can request a new password.

**Comment by kidino** [comment]
May I suggest some API endpoints for this:

1. POST (public) - /consumer/forgot_password
`data : { "email":<email address> }`

This would do the following
- find user based on email address
- generate a forget password hash for the user, stored in a new column in the user table. The hash should have an expiry period, ie, 48 hours
- Fusio sends an email with the link that contains the forget password hash
- Administrator can customize the link to where ever he feels fit, ie, /mysite/forget_password/<hash> where the developer has created a web UI for users to enter new password
- There should be somewhere (file, or via /fusio) that Administrator can update the template for the forget password

2. POST (public) - /consumer/forgot_password/<hash>
`data : { "email":<email address>, "new_password":<new_password> }`

This would do the following
- validates that the hash exists for user as per email address provided
- validates the hash is still valid and active, not expired
- updates the password for the user

3. GET (public) - /consumer/forgot_password/<hash>
`data : { "email" : <email address }`

An API just to check if the hash is still valid for the user. This can be used on the page where the developer needs to display the UI for updating the password.

**Comment by kidino** [comment]
But then again, maybe I can implement this my own with a user that has backend authorization.

**Comment by chriskapp** [comment]
ok, so for the normal login we could implement this to provide a way to restore the password. In case the user has authenticated through a different provider we would simply throw an error. I would maybe create only the route `/consumer/forgot_password` and use `POST` to start the restore process and `PUT` to set a new password. I will add this to the 1.9 milestone, so that we implement this feature at the next release.

**Comment by theraw** [comment]
@chriskapp is there anyway to recover admin password just lost it? (i have full access on files/mysql ofc)

**Comment by chriskapp** [comment]
@theraw no currently there is no way to restore the password, but you can create a new admin user through the `bin/fusio adduser` command

**Comment by chriskapp** [comment]
We have just commited the changes to implement this feature https://github.com/apioo/fusio-impl/commit/1032a8fb4e9fdb50f5d113ce1fdd625a7a636fa6
We have now a new endpoint `/consumer/password_reset` where you can send a POST request to start the password reset process (containing the user email). The user receives an email with a body and subject which can be customized through the settings. The mail contains a link with a token, you can use this token to set a new password for the user sending a PUT request to the `/consumer/password_reset` endpoint containing the token and the new password. The token will expire after one hour. This feature is then included in the next release.

**Comment by kidino** [comment]
Awesome. Is there a way to customize the email?
