### ISSUE TITLE
error:0607A082, error:06065064 on deleting connection

### ISSUE THREAD

**Issue by koswarabilly** [apioo/fusio#188]
i do not know how but fusio manage to get this error when i tried to delete certain connection.
Here is the screenshot:
![capture](https://user-images.githubusercontent.com/29243760/44771423-1c6a3780-ab95-11e8-88b0-bc3662b180ce.PNG)
and when i try to view the existing connection it shows me something weird
![capture](https://user-images.githubusercontent.com/29243760/44771472-3dcb2380-ab95-11e8-99d5-d2cb58cc218c.PNG)
I believe that this is not the information when you try to edit existing connection.

Is this Fusio's bug or am i doing something wrong?

**Comment by chriskapp** [comment]
Hi, mhh this looks like an openssl error when Fusio tries to decode the credentials from the database. Which version of Fusio do you use? This happens simply after you have tried to delete a connection?

**Comment by koswarabilly** [comment]
I am sorry i am not the one who installed in the server
The version i am currently in is `v4.0.1@26253dcc33e3ab23f2e2f285c23ac9405fac32cb`

Yeah this happens simply after i tried to delete a connection.

**Comment by chriskapp** [comment]
I will close this issue since it looks like there is nothing more todo here
