### ISSUE TITLE
Swagger and PHP-Sandbox

### ISSUE THREAD

**Issue by victoralicaya** [apioo/fusio#189]
hi, I have created APIs on PHP-Sandbox and I don't know how to integrate it to swagger, do you have any tutorials?

**Comment by chriskapp** [comment]
Hi, so this is really simple. You basically need to assign a request and response schema for your route. Then Fusio automatically generates the fitting swagger definition for. You can see this at the `/swagger-ui` app. I.e. take a look at our [demo api](https://demo.fusio-project.org/swagger-ui/). The schema must be in the Json-Schema format and can be created at the backend or you can also use the deploy mechanism.

**Comment by EvoPulseGaming** [comment]
This can probably be closed as well
