### ISSUE TITLE
Integrating Fusio with existing OAuth2 Authentication Server and SSO

### ISSUE THREAD

**Issue by rlvillacarlos** [apioo/fusio#190]
Hi I would like to know if there is an out of the box way to setup fusio so that it will use an existing OAuth 2 authentication Server and SSO?

**Comment by chriskapp** [comment]
Hi, so the developer portal of Fusio currently supports email registration and Google, Facebook and Twitter login. So unfortunately there is no out of the box way to configure an SSO with another OAuth2 server.

But in general it is easy possible to develop a new OAuth2 provider. Please take a look at the [source](https://github.com/apioo/fusio-impl/tree/master/src/Service/User/Provider)

In the future we also want try to support other SSO solutions like i.e. LDAP, SAML but this is still on our todo list. Regarding the integration of a new OAuth2 server we could improve the integration by allowing the developer to register an external provider.

**Comment by chriskapp** [comment]
With the latest 1.4 release it is now easy possible to extend the social login with other providers, please take a look at our manual: https://fusio.readthedocs.io/en/latest/concept/social_login.html
