### ISSUE TITLE
Add app to simplify action development

### ISSUE THREAD

**Issue by chriskapp** [apioo/fusio#191]
We could build a new JS app which is targeted towards developers to build new actions on the web. This app could use the [monaco-editor](https://microsoft.github.io/monaco-editor/) to simply develop an action. The app could have a three column layout, on the left column you have a list with all available actions and connections, in the middle is a large editor and on the right the user has the response of the action. At the top there is a button to execute the action. This app could help users who only code on the web and have no access to the filesystem.

Also it would be possible to split up tasks so that the develop only works with this app and another admin assign those actions to a specific route. If this is useful we could also create a new developer role which can only create and edit actions but have no other rights on the system. Through this it would be also easy to outsource action development.

**Comment by kidino** [comment]
I like this!

**Comment by chriskapp** [comment]
We have created a new app, based on the monaco-editor which allows a user to easily develop new actions. We will release this with the next 1.7 release. Here a short preview how it looks:

![fusio_vscode](https://user-images.githubusercontent.com/2505846/61587719-874aa580-ab8f-11e9-9ae0-7beef3d85f38.png)
