### ISSUE TITLE
Need a detailed example for PHP sandbox

### ISSUE THREAD

**Issue by dlinstedt** [apioo/fusio#192]
I would like to use PHP-Sandbox to execute Guzzle.  

I want: external call -> action
Action -> call another remote REST API using Guzzle or something
Process results -> return result of bridged call

Unfortunately I don’t see a way of doing this, and I don’t have access to v8 JS engine, so I can’t use those pieces.

I tried setting up a second service to call a different REST API, but i can’t get it to work with an AUHORIZATION token, so I can’t “hook” two actions together.

I tried leveraging / including Guzzle in the PHP code, and got an error - unable to include it.

Thoughts?

**Comment by EvoPulseGaming** [comment]
This also can be closed probably
