### ISSUE TITLE
Route "POST" does not work for me

### ISSUE THREAD

**Issue by tmtung144** [apioo/fusio#193]
I have 2 different actions: **send_comment_post** sends a new comment to the post, and **comments_by_post** makes a list of comments that have been made so far.

![2018-10-12_14-42-18](https://user-images.githubusercontent.com/19670776/46855185-2d14fb00-ce2d-11e8-9444-bb4aaabc113f.png)

In the same route **/comments_post /:post_id** I execute GET and POST but when POST is executed I always get the response GET

![2018-10-12_14-51-13](https://user-images.githubusercontent.com/19670776/46855667-977a6b00-ce2e-11e8-98c4-90a173cb9b4f.png)
![2018-10-12_14-51-39](https://user-images.githubusercontent.com/19670776/46855678-9b0df200-ce2e-11e8-9bfa-641a6f4affcc.png)

Please help me!

**Comment by chriskapp** [comment]
Hi, from the screenshot everything loooks fine. Can you execute the `send_comment_post` action manually by clicking on the wrench at the backend? Also can you show me the HTTP POST request and response.

**Comment by tmtung144** [comment]
This is the result in the backend
![2018-10-12_16-13-18](https://user-images.githubusercontent.com/19670776/46860214-280a7880-ce3a-11e8-94f2-85a0045e0d24.png)
Here is the call from **postman**
![2018-10-12_16-13-54](https://user-images.githubusercontent.com/19670776/46860235-33f63a80-ce3a-11e8-935a-e1ebaa5e5c8e.png)

**Comment by tmtung144** [comment]
By the way I'm using nginx server.
There is no specific rewrite .htaccess configuration as in **apache**. Is it a problem?

**Comment by tmtung144** [comment]
Sorry for my English skills, I'm not sure what you want but I am sending you 2 tables of **routes** and my **routes_method**. At the same time I discovered my methods are ANY

[fusio.zip](https://github.com/apioo/fusio/files/2472591/fusio.zip)

**Comment by chriskapp** [comment]
no problem, I will take a look at the files and try to identify the problem.

**Comment by chriskapp** [comment]
Could you add the following context values to your GET and POST response so that we can exactly see which route and action is used:

```
'actionId' => $context->getAction()->getId(),
'routeId' => $context->getRouteId(),
```

**Comment by tmtung144** [comment]
**GET**: 
{
    "actionId": "22",
    "routeId": "105",
    ...
}

and **POST** I can not get the value from Postman, but if you run in Actions will result
{
    "actionId": "23",
    "routeId": 23,
    ...
}

**Comment by tmtung144** [comment]
Grrr, I discovered that when using the `/documentation`, the path will work with the **POST** method in the form `https://domain/index.php/comments_post/:post_id`

**Comment by chriskapp** [comment]
Ok, this looks then indeed like a url rewrite problem. How does you nginx config looks, do you redirect all requests to the index.php i.e. for apache we have an example vhost entry: https://fusio.readthedocs.io/en/latest/basic/installation.html#apache

**Comment by tmtung144** [comment]
```
RewriteCond %{HTTP:Authorization} ^(.*)
RewriteRule .* - [e=HTTP_AUTHORIZATION:%1]
```

Is there something important here that I have not used to Authorization so I'm not sure if there is any other problem?

**Comment by chriskapp** [comment]
Regarding the nginx config, could you maybe post your working config, then I would add this config to the manual so other users can better start using Fusio with nginx: https://fusio.readthedocs.io/en/latest/basic/installation.html#apache

**Comment by EvoPulseGaming** [comment]
This can probably be closed
