### ISSUE TITLE
Generate XML instead of JSON

### ISSUE THREAD

**Issue by justchake** [apioo/fusio#194]
Is het possible to create an API that generated XML output instead of JSON?

**Comment by chriskapp** [comment]
Hi, sure you can use the `format` parameter to specify the response type i.e. 
https://demo.fusio-project.org/todo?format=xml
Fusio looks also at the `Accept` header so if your request contains `Accept: application/xml` it will return the xml format.

**Comment by chriskapp** [comment]
I will close this issue since it looks like the question is answered. Also we have now added a new chapter to the manual regarding the serialization process:
https://fusio.readthedocs.io/en/latest/internal/serialization.html

**Comment by chriskapp** [comment]
Hi, ok so you would need to use `application/jsonx+xml` MIME as Accept value since we have removed our general XML write and provide currently only the JSONx writer to generate XML.
