### ISSUE TITLE
IFTTT web request problem to fusio

### ISSUE THREAD

**Issue by kirildevlion** [apioo/fusio#199]
Hello,
If i use IFTTT service with web request to execute api. Fusio api blocks this request. IFTTT i got message "Unable to make web request. Your server returned a 400". 
How can i permit to fusio executes api with web request of IFTTT? 

![image](https://user-images.githubusercontent.com/23627990/48953032-1ba33080-ef4d-11e8-95b6-64e7d6464a9a.png)

**Comment by kirildevlion** [comment]
I send GET request to http://api.devlion.co from my browser and from IFTTT 
Attached log access example: 

![image](https://user-images.githubusercontent.com/23627990/49002331-f8080200-f167-11e8-9bc6-3f390c5d4a1d.png)

In php ERROR file there is no errors. Maybe it blocks it because there is no User Agent in this request?

**Comment by chriskapp** [comment]
Yes this probably the problem, Fusio rejects all request without a `User-Agent` header. Normally it is best practive for a tool to provide a user agent header. Is it possible to set a User-Agent for the IFTTT tool?

**Comment by kirildevlion** [comment]
No, as for now IFTTT can not send User Agent. Maybe i can disable this
validation in code?

**Comment by chriskapp** [comment]
ok, so currently it is not possible to deactivate the user agent check through a config.

Maybe you can request to IFTTT that they add a proper user agent header to their HTTP requests. The [HTTP spec](http://svn.tools.ietf.org/svn/wg/httpbis/specs/rfc7231.html#header.user-agent) states that clients SHOULD add a user agent header.

Basically it is there to have a meaningful way to identify client requests which is also shown at the log panel. Also popular APIs like [GitHub](https://developer.github.com/v3/#user-agent-required) require a user agent.

In general it would be easy to deactivate this check by simply removing the middleware at the [SchemaApiController](https://github.com/apioo/fusio-impl/blob/master/src/Controller/SchemaApiController.php#L117) but Iam not really sure whether we want this.

**Comment by kirildevlion** [comment]
Thanks a lot!

**Comment by chriskapp** [comment]
So I will close this issue since it looks like there is nothing more todo
