### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by navneetccna** [apioo/fusio#201]
I was wondering if there any adapter for GraphQL. That would be great.

**Comment by chriskapp** [comment]
Hi, currently we have no adapter regarding GraphQL. In general you could also use the HTTP adapter to query a graphql server but if there is a better GraphQL client we could also easily create an adapter for this. Or do you thought about using Fusio as GraphQL server?

**Comment by navneetccna** [comment]
I am thinking about adapter. There are lots of very good GraphQL client available.
Fusio as GraphQL server it would be great but I thought it would take more time and it will be better you use adapter for already exist good GraphQL server.

**Comment by chriskapp** [comment]
Yes, this is a great idea. Building an GraphQL adapter should be no problem, do you recommend any specific PHP GraphQL client which we should use? On packagist.org I actually did not found a very popular GraphQL client library. It would be great if the library also uses Guzzle to send HTTP requests since it is already included in Fusio.

**Comment by navneetccna** [comment]
https://packagist.org/?query=graphql-client

softonic/graphql-client and euautomation/graphql-client use Guzzle for HTTP requests.

**Comment by chriskapp** [comment]
ok thanks, I will check it out and see whether we can create a new adapter for this.

**Comment by navneetccna** [comment]
Hi @chriskapp,

Any update? Meanwhile I was looking in to the graphql server as well and found this https://github.com/webonyx/graphql-php

If you have any plan to implement fusio as a graphql server then https://github.com/webonyx/graphql-php it will help

**Comment by chriskapp** [comment]
So I have good news, I have just released the first version of our GraphQL adapter. The adapter is available at https://github.com/apioo/fusio-adapter-graphql I have also wrote a Tweet about it: https://twitter.com/FusioAPI/status/1076436182890938368 Please let me know what do you think and whether this works for your use case.

**Comment by navneetccna** [comment]
Kudos.
Thanks a lot.

**Comment by chriskapp** [comment]
yes sure, so basically it is really simple you need to install the adapter at your Fusio system through:

```
composer require fusio/adapter-graphql
php bin/fusio system:register "Fusio\Adapter\GraphQL\Adapter"
```

then you need to create a new GraphQL connection which points to your GraphQL server. Then you can make a request to the GraphQL server in your action i.e.

```
$client = $connector->getConnection("graphql");

$query = <<<GRAPHQL
{
  products: allProducts(count: 8) {
    id
    name
    price
  }
}
GRAPHQL;

$data = $client->request($query);

```

we do this also in the test case of the adapter:
https://github.com/apioo/fusio-adapter-graphql/blob/master/tests/Connection/GraphQLTest.php#L71

the response is then simply the json decoded data

**Comment by chriskapp** [comment]
FYI the client is now included in the latest release. Because of this I will close this issue.
