### ISSUE TITLE
Quickstart update suggestion

### ISSUE THREAD

**Issue by kidino** [apioo/fusio#202]
I would like to suggest the following update for the homepage Quickstart page (http://fusio-project.org/bootstrap)

- Include information about script install (install.php)
- Include information about running migration, because the demo To-Do API now uses class Action and MySQL System Connection instead of SQLite in previous version.

Since there is no repo for the project homepage, attached is my proposed HTML file for the Quickstart page.
[fusio-bootstrap.zip](https://github.com/apioo/fusio/files/2660199/fusio-bootstrap.zip)

**Comment by chriskapp** [comment]
Hi, thanks for the great feedback. I have just updated the bootstrap page with your improvements. Please take a look at the page, I have adjusted some parts but I think it is now great.

**Comment by kidino** [comment]
Awesome!

**Comment by kidino** [comment]
http://fusio-project.org/bootstrap

There is a typo here that could get people starting out frustrated. The command below is missing one dash ... should be

php bin/fusio migration:migrate **--connection=System**

not 

php bin/fusio migration:migrate **-connection=System**

**Comment by kidino** [comment]
Also need fixing in the manual page

https://fusio.readthedocs.io/en/latest/concept/migration.html
