### ISSUE TITLE
How to delete a token?

### ISSUE THREAD

**Issue by kidino** [apioo/fusio#204]
I see a list of tokens from the /fusio backend. And I can see information about the token, ie, who it belongs to. But I cannot find information on how to delete a token.

**Comment by chriskapp** [comment]
Hi, so if you go to the "App" panel and take a look at the "Tokens" tab, there should be also a button to delete such tokens. But maybe we should also add a delete button to the general token panel.

**Comment by kidino** [comment]
Yeah ... I was looking in the general token. Most of my use case is where systems are accessing the API, not actual end users. So I plan to create a user with scope and all, login with it one time to get the token, then just give the developer the token. I will also make the token expiry time to really long, like 999Y or so in configuration.php

But there are cases where we may need to remove the token.

Having a delete button in the general would be great. In the meantime, if you can point out to me the endpoint to do this, that'll do for now. I have been going through the backend API but couldn't figure it out.

**Comment by chriskapp** [comment]
So with the latest release it is now also possible to delete tokens directly through the token list. Because of this I will close this issue.
