### ISSUE TITLE
Suggestion - CRUD API Generator

### ISSUE THREAD

**Issue by kidino** [apioo/fusio#207]
I would like to suggest a feature where CRUD API can be created one shot, rather then to have to do them one by one. There is a screen with the following fields:

- Base route (ie, /northwind/customer)
- Select connection (ie, northwind)
- Enter table name
- Check APIs to be deployed (checkboxes)
-- GET - for listing
-- GET ID - for rec
-- POST - for insert
-- PUT - for update
-- DELETE - for delete
- Add to new Scope (textfield)
- Add to Scope (shows available scopes as checkboxes)

This will
- Create the Action with SQL-Table Adapter
- Create all the checked API Routes

Of courses, management later continues in Routes, Actions, Scope and the rests of the admin panel

**Comment by chriskapp** [comment]
Hi, this is a great idea. I think it would be great to wrap all this logic in a custom javascript app. I.e. `CrudGenerator` a user could then use this app to simple create endpoints by only providing those settings and the app then makes all needed API calls.

I had a similar idee to build an app where a user could simply model an entity and the app then creates all fittings routes and actions etc. I think this idea goes into the same direction.

**Comment by chriskapp** [comment]
Hi, so we have just released a new tool (https://generate.apioo.de/) which can generate source code for a CRUD API. This basically generates the points which you have listed. So I will close this issue since we have now a service to automatically generate code for a CRUD API based on a relational database.
