### ISSUE TITLE
Extra characters returned in JSON

### ISSUE THREAD

**Issue by twenster** [apioo/fusio#208]
Hello,

I'm trying to use Fusio, but I'm currently block by some extraneous characters returned by Fusio.

I have a page producing a JSON file (content-type application/json) which seems correct
```
{
    (...my content...)
}
```

In fusio interface I created a user, a scope, and app, an action (GET & POST) and a route.
When testing calling the page from the action designer in GET or POST, I get the same content in the error 200 box. That's fine.

However when I request the page through the route (I have a javascript in a php page making the call), then the JSON is altered:
```
33a
{
    (...my content...)
}
0
```
The number (here 33) is different depending of the length or content of the JSON itself). I can't understand why. the 0 is always there.
I tried calling with GET or POST as public or private route, but the response is always the same.
Using Fusio 1.4.0 and now 1.5.0...
Any suggestions ?

**Comment by chriskapp** [comment]
Hi, this looks like the server responds with a "chunked" response, do you have maby set in the request the header `Transfer-Encoding` to `chunked`, but normally this should be handeled by your browser. Could you show me the complete HTTP request which you send to Fusio.

**Comment by twenster** [comment]
Hi,

Here is the header received by Fusio, from my Javascript

Safari:
```
Host: mysite.com
Cookie: PHPSESSID=802efc1e4a582c56d51f43525ef09e31
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15
Dnt: 1
Content-Length: 6
Referer: https://mysite.com/atomospeller/dev/login.php
Origin: https://mysite.com
Accept-Encoding: br, gzip, deflate
Accept-Language: fr-ch
Accept: application/json; charset=UTF-8
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Authorization:

```

Firefox:

```
Host: mysite.com
Te: trailers
Dnt: 1
Content-Length: 6
Content-Type: application/x-www-form-urlencoded; charset=UTF-8
Referer: https://mysite.com/atomospeller/dev/login.php
Accept-Encoding: gzip, deflate, br
Accept-Language: fr,fr-FR;q=0.8,en-US;q=0.5,en;q=0.3
Accept: application/json; charset=UTF-8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.14; rv:64.0) Gecko/20100101 Firefox/64.0
Authorization:

```

(I just replaced the domain. name).

Indeed, the format seems a chunked transfert. However I do know where this is coming from. Except for .env file and public/.htaccess, I haven't modified any files of Fusio.

In the JS, I only set Accept and Content-Type header.

**Comment by chriskapp** [comment]
ok, so in general Fusio sends also the body chunked encoded in case the header `Transfer-Encoding` is set to `chunked`. You can see this code at: `vendor/psx/http/src/Server/Sender.php`

You could deactivate this chunked encoding to see whether this solves your problem. But from the header which you have posted there is no `Transfer-Encoding` header available.

Is this problem also there if you simply create a php file which returns json content. If yes this could be also a problem with your webserver.

**Comment by twenster** [comment]
I did the following test (from my first post):
Direct call from browser to the page returning the JSON: the response is a correct encoded JSON
Direct call from a javascript in browser from a page: the response is a correct encoded JSON
Call from Fusio 1.50 Action Designer: the 200 response is a correct JSON
Call from a javascript to Fusio using the route: the response is chunked

As you suggest, I deactivated the chunked encoded in the Server.php file, and the response is a correct JSON (not chunked)

**Comment by chriskapp** [comment]
this is interesting. Normally the browser handles chunked encoding automatically, but in this case the browser has not requested chunked encoding since the header is missing (in the header which you have posted above). So I would assume that the webserver somehow automatically sets this header and
because of this the browser returns the complete body since it does not expect a chunked response. Could you check the webserver config whether in the config or in a `.htaccess` file there is a directive which sets this header.

**Comment by twenster** [comment]
The server is a mutualized one, I sadly don't have access to the plesk dashboard. However I didn't see any mention in the existing .htaccess

If the server was responsible to request chunked encoding, I should get chunked response from direct call from my javascript, which is not the case. I'm wondering why only through Fusio route, this is happening... BTW Fusio and the page returning the JSON are on the same server.

Or is it because the page returning the JSON forces a content-type: application/json, which disables chunked transfer encoding?

**Comment by chriskapp** [comment]
ok, this is indeed strange. In general a `Content-Type` header should not disable chunked encoding. Could you maybe test this behaviour also with another browser? And could you write a simple PHP script which contains `var_dump($_SERVER);` which you then request with the same javascript logic. In this way we could see exactly the headers which arrive at Fusio.

**Comment by twenster** [comment]
Below is the var_dump of what my log2.php is receiving from Fusio.

The workflow is the following : login.php calls (XMLHttpRequest) Fusio route, which calls log2.php. Log2.php returns var_dump with header text/plain. login.php is printing the response. I change the IPS and domaine name. You notice the response is chunked too.

```
e14
 array(57) {
    ["TEMP"] => string(50) "/home/clients/dde1219f7e0244c3b6446bb769bbf912/tmp"
    ["TMPDIR"] => string(50) "/home/clients/dde1219f7e0244c3b6446bb769bbf912/tmp"
    ["TMP"] => string(50) "/home/clients/dde1219f7e0244c3b6446bb769bbf912/tmp"
    ["ORIG_SCRIPT_NAME"] => string(19) "/.fpm/php5.external"
    ["ORIG_PATH_TRANSLATED"] => string(76) "/home/clients/dde1219f7e0244c3b6446bb769bbf912/web/atomospeller/dev/log2.php"
    ["ORIG_PATH_INFO"] => string(26) "/atomospeller/dev/log2.php"
    ["ORIG_SCRIPT_FILENAME"] => string(101) "/home/clients/dde1219f7e0244c3b6446bb769bbf912/.config/apache/mysite.com/.fpm/php5.external"
    ["SCRIPT_NAME"] => string(26) "/atomospeller/dev/log2.php"
    ["REQUEST_URI"] => string(26) "/atomospeller/dev/log2.php"
    ["QUERY_STRING"] => string(0) ""
    ["REQUEST_METHOD"] => string(4) "POST"
    ["SERVER_PROTOCOL"] => string(8) "HTTP/1.1"
    ["GATEWAY_INTERFACE"] => string(7) "CGI/1.1"
    ["REDIRECT_URL"] => string(26) "/atomospeller/dev/log2.php"
    ["REMOTE_PORT"] => string(5) "35802"
    ["SCRIPT_FILENAME"] => string(76) "/home/clients/dde1219f7e0244c3b6446bb769bbf912/web/atomospeller/dev/log2.php"
    ["SERVER_ADMIN"] => string(26) "hello@mysite.com"
    ["CONTEXT_DOCUMENT_ROOT"] => string(88) "/home/clients/dde1219f7e0244c3b6446bb769bbf912/.config/apache/mysite.com/.fpm/"
    ["CONTEXT_PREFIX"] => string(6) "/.fpm/"
    ["REQUEST_SCHEME"] => string(4) "http"
    ["DOCUMENT_ROOT"] => string(50) "/home/clients/dde1219f7e0244c3b6446bb769bbf912/web"
    ["REMOTE_ADDR"] => string(13) "64.64.64.64"
    ["SERVER_PORT"] => string(2) "80"
    ["SERVER_ADDR"] => string(14) "84.84.84.84"
    ["SERVER_NAME"] => string(20) "mysite.com"
    ["SERVER_SOFTWARE"] => string(6) "Apache"
    ["SERVER_SIGNATURE"] => string(0) ""
    ["PATH"] => string(60) "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
    ["CONTENT_LENGTH"] => string(1) "6"
    ["HTTP_X_FORWARDED_HOST"] => string(20) "mysite.com"
    ["HTTP_ACCEPT"] => string(68) "application/json, application/x-www-form-urlencoded;q=0.9, */*;q=0.8"
    ["HTTP_X_FUSIO_REMOTE_IP"] => string(13) "64.64.64.64"
    ["HTTP_X_FUSIO_APP_KEY"] => string(0) ""
    ["HTTP_X_FUSIO_APP_ID"] => string(0) ""
    ["HTTP_X_FUSIO_USER_ID"] => string(0) ""
    ["HTTP_X_FUSIO_USER_ANONYMOUS"] => string(1) "1"
    ["HTTP_X_FUSIO_ROUTE_ID"] => string(2) "93"
    ["HTTP_ORIGIN"] => string(28) "https://mysite.com"
    ["HTTP_REFERER"] => string(55) "https://mysite.com/atomospeller/dev/login.php"
    ["HTTP_DNT"] => string(1) "1"
    ["HTTP_HOST"] => string(20) "mysite.com"
    ["CONTENT_TYPE"] => string(33) "application/x-www-form-urlencoded"
    ["HTTP_USER_AGENT"] => string(39) "GuzzleHttp/6.3.3 curl/7.38.0 PHP/7.1.24"
    ["PHP_VERSION"] => string(3) "7.0"
    ["SCRIPT_URI"] => string(53) "http://mysite.com/atomospeller/dev/log2.php"
    ["SCRIPT_URL"] => string(26) "/atomospeller/dev/log2.php"
    ["UNIQUE_ID"] => string(27) "XDmmcTv9oULpYLr4u4i@KgAAAAM"
    ["REDIRECT_STATUS"] => string(3) "200"
    ["REDIRECT_HANDLER"] => string(9) "php5-fcgi"
    ["REDIRECT_PHP_VERSION"] => string(3) "7.0"
    ["REDIRECT_SCRIPT_URI"] => string(53) "http://mysite.com/atomospeller/dev/log2.php"
    ["REDIRECT_SCRIPT_URL"] => string(26) "/atomospeller/dev/log2.php"
    ["REDIRECT_UNIQUE_ID"] => string(27)  "XDmmcTv9oULpYLr4u4i@KgAAAAM"
    ["FCGI_ROLE"] => string(9) "RESPONDER"
    ["PHP_SELF"] => string(26) "/atomospeller/dev/log2.php"
    ["REQUEST_TIME_FLOAT"] => float(1547282033.8748)
    ["REQUEST_TIME"] => int(1547282033)
}
0

```

One thing. in Fusio, for that route, I passthrough all data (parameters, request and responses).

**Comment by twenster** [comment]
I just tried the make my calls using Insomnia (https://insomnia.rest). A direct call and a call through Fusio, return a valid JSON ! Transfer is chunked... So in either XMLhttpRequest Safari and Firefox are doing something when a call through Fusio. Can't explain why ...

**Comment by chriskapp** [comment]
mhh is there maybe a proxy which modifies the response? In the `var_dump` is also no `Transfer-Encoding` header so I would assume that Fusio does not send the response chunked. As another test could you make the `var_dump` not from a script which gets called by Fusio but instead simply place the `var_dump` at the `public/index.php` file. If you now call the `index.php` through XMLHttpRequest we should see the header which Fusio receives.
