### ISSUE TITLE
Is there a log level setting in Fusio ?

### ISSUE THREAD

**Issue by DEVPCL** [apioo/fusio#210]
Is it possible to set the log Level in Fusio ? Even to disable it ? Or disable database storing ?
Thanks in advance.

**Comment by chriskapp** [comment]
Hi, yes so at the configuration.php file you can set i.e.:

```
'psx_log_level' => \Monolog\Logger::ERROR,
```

this tells Fusio to use the ERROR level, which is also the default. For more details you could also set i.e. DEBUG. I have also just added this to the configuration:
https://github.com/apioo/fusio/blob/master/configuration.php#L124

to completely disable logging, you could also set a custom logger factory i.e.:

```
'psx_logger_factory'      => function($config){
	return new \Monolog\Handler\NullHandler();
},
```

**Comment by chriskapp** [comment]
The latest release contains now to log level config so I will close this issue.
https://github.com/apioo/fusio/blob/master/configuration.php#L124
