### ISSUE TITLE
JSON reponse truncated in browser, CURL or Swagger-UI

### ISSUE THREAD

**Issue by webdevilopers** [apioo/fusio#213]
I have a (Symfony Flex) REST API returning a JSON result with the URL "dev.personnel.com/employee/list/json". The JSON result returns an array of employees. Currenlty there are *10* entries. The header content-length returns *4730*.

Fusio hast a POST passthru route with the URL "dev.api.com/index.php/employees/".

The JSON result is correct when executing via action designer.

But when calling it via AJAX in any browser (FF, Chrome), via CURL or Swagger-UI the result is truncated which results in:
SyntaxError: JSON.parse: end of data after property value in object at line 173 column 30 of the JSON data
But the header content-length still returns *4730*.

I then only return *9* array entries which reduces the content-length to *4219*. Now if I try the route it succeeds.

All other headers are always the same:

```
access-control-allow-origin: *
Connection	Keep-Alive
Content-Type	application/json
Keep-Alive	timeout=5, max=100
Server	Apache/2.4.29 (Ubuntu)
cache-control	no-cache, private
vary	Accept
Accept	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Encoding	gzip, deflate
Accept-Language	de,en-US;q=0.7,en;q=0.3
Cache-Control	max-age=0
Connection	keep-alive
DNT	1
Host	dev.api.com
Upgrade-Insecure-Requests	1
User-Agent	Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0
```

There is one unicode string in the middle of the JSON but it seems to be correctly parsed:
"firstName":"J\u00f6rg"

Here are the $_SERVER dumps:

Source REST API
```
  "REDIRECT_STATUS" => "200"
  "HTTP_HOST" => "dev.personnel.com"
  "HTTP_CONNECTION" => "keep-alive"
  "HTTP_UPGRADE_INSECURE_REQUESTS" => "1"
  "HTTP_USER_AGENT" => "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) snap Chromium/71.0.3578.98 Chrome/71.0.3578.98 Safari/537.36"
  "HTTP_ACCEPT" => "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"
  "HTTP_ACCEPT_ENCODING" => "gzip, deflate"
  "HTTP_ACCEPT_LANGUAGE" => "de,en-US;q=0.9,en;q=0.8"
  "PATH" => "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  "SERVER_SIGNATURE" => "<address>Apache/2.4.29 (Ubuntu) Server at dev.personnel.com Port 80</address>\n"
  "SERVER_SOFTWARE" => "Apache/2.4.29 (Ubuntu)"
  "SERVER_NAME" => "dev.personnel.com"
  "SERVER_ADDR" => "127.0.0.1"
  "SERVER_PORT" => "80"
  "REMOTE_ADDR" => "127.0.0.1"
  "DOCUMENT_ROOT" => "/var/www/personnel/web"
  "REQUEST_SCHEME" => "http"
  "CONTEXT_PREFIX" => ""
  "CONTEXT_DOCUMENT_ROOT" => "/var/www/personnel/web"
  "SERVER_ADMIN" => "[no address given]"
  "SCRIPT_FILENAME" => "/var/www/personnel/web/app_dev.php"
  "REMOTE_PORT" => "34406"
  "REDIRECT_URL" => "/employee/list/json"
  "GATEWAY_INTERFACE" => "CGI/1.1"
  "SERVER_PROTOCOL" => "HTTP/1.1"
  "REQUEST_METHOD" => "GET"
  "QUERY_STRING" => ""
  "REQUEST_URI" => "/employee/list/json"
  "SCRIPT_NAME" => "/app_dev.php"
  "PHP_SELF" => "/app_dev.php"
  "REQUEST_TIME_FLOAT" => 1548934504.948
  "REQUEST_TIME" => 1548934504
```

Fusio API Gateway
```
  "REDIRECT_STATUS": "200",
  "HTTP_HOST": "dev.personnel.com",
  "HTTP_USER_AGENT": "GuzzleHttp/6.3.3 curl/7.58.0 PHP/7.2.10-0ubuntu0.18.04.1",
  "CONTENT_TYPE": "application/json",
  "HTTP_DNT": "1",
  "HTTP_UPGRADE_INSECURE_REQUESTS": "1",
  "HTTP_CACHE_CONTROL": "max-age=0",
  "HTTP_X_FUSIO_ROUTE_ID": "92",
  "HTTP_X_FUSIO_USER_ANONYMOUS": "1",
  "HTTP_X_FUSIO_USER_ID": "",
  "HTTP_X_FUSIO_APP_ID": "",
  "HTTP_X_FUSIO_APP_KEY": "",
  "HTTP_X_FUSIO_REMOTE_IP": "127.0.0.1",
  "HTTP_X_FORWARDED_FOR": "127.0.0.1",
  "HTTP_ACCEPT": "application/json, application/x-www-form-urlencoded;q=0.9, */*;q=0.8",
  "HTTP_X_FORWARDED_HOST": "dev.api.com",
  "CONTENT_LENGTH": "2",
  "PATH": "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
  "SERVER_SIGNATURE": "<address>Apache/2.4.29 (Ubuntu) Server at dev.personnel.com Port 80</address>\n",
  "SERVER_SOFTWARE": "Apache/2.4.29 (Ubuntu)",
  "SERVER_NAME": "dev.personnel.com",
  "SERVER_ADDR": "127.0.0.1",
  "SERVER_PORT": "80",
  "REMOTE_ADDR": "127.0.0.1",
  "DOCUMENT_ROOT": "/var/www/personnel/web",
  "REQUEST_SCHEME": "http",
  "CONTEXT_PREFIX": "",
  "CONTEXT_DOCUMENT_ROOT": "/var/www/personnel/web",
  "SERVER_ADMIN": "[no address given]",
  "SCRIPT_FILENAME": "/var/www/personnel/web/app_dev.php",
  "REMOTE_PORT": "34458",
  "REDIRECT_URL": "/employee/list/json",
  "GATEWAY_INTERFACE": "CGI/1.1",
  "SERVER_PROTOCOL": "HTTP/1.1",
  "REQUEST_METHOD": "GET",
  "QUERY_STRING": "",
  "REQUEST_URI": "/employee/list/json",
  "SCRIPT_NAME": "/app_dev.php",
  "PHP_SELF": "/app_dev.php",
  "REQUEST_TIME_FLOAT": 1548934928.316,
  "REQUEST_TIME": 1548934928
```

Maybe related to:
https://github.com/apioo/fusio/issues/208

Other suggestions relate to UTF-8 or `mbstring`:
https://stackoverflow.com/questions/24307397/json-string-encoded-from-large-array-got-truncated-when-output-to-http-client

Discussion started on Twitter here:
https://twitter.com/webdevilopers/status/1090683778568200192

**Comment by chriskapp** [comment]
Hi, thanks detailed report. Could you send me the complete JSON response from the action designer of your Symfony Flex API. In this way I could try to reproduce the problem, by creating an API which returns this response which is then called by Fusio.

**Comment by chriskapp** [comment]
@webdevilopers thanks for finding this issue so far. In general Fusio uses a serializer which tries to convert the provided object graph into a fitting JSON response. Therefor it uses an graph traverser to decide which value is an object, array or scalar value see:
https://github.com/apioo/psx-data/blob/master/src/GraphTraverser.php#L108

In the MongoDB case we have `MongoDB\BSON\` objects, which implement all `JsonSerializable` so the graph traverser uses this method to get the JSON representation of the object.

Regarding the issue, unfortunately I could not yet reproduce the issue. I have created locally an action which passes the cursor directly to the response:

```
$connection = $connector->getConnection('mongo');

$collection = $connection->selectCollection('test');
$cursor     = $collection->find();

return $response->build(200, [], [
    'data' => $cursor,
]);
```

and everything works fine so far. Iam using the data which you have send me per mail. While it is great that it works with `iterator_to_array` iam currently not exactly sure what the issue actually is. But nevertheless please let me know if there is anything which you have discovered and have fun using Fusio ;)

**Comment by webdevilopers** [comment]
You're welcome!

The Mongo Cursor is not the problem. As far as I understand it happens when an array key at a certain nesting depth is a **0**.

This happened twice in my sample data I thin at the third level. Then the JSON broke.
When I removed a level by removing the keys from the iterator it worked.

At the bottom line the Fusio serializer works great in the dispatcher action. But it breaks inside the browser.

Maybe there also is some Apache "nested depth level" manipulation?

**Comment by webdevilopers** [comment]
I had an array with 10 entries and it looked pretty random at what point the JSON would break.
In either case it was the **0** of the `hiredAt` or `createdAt` key.

Here is a single entry example:
```json
[{"5c4eda054db9aa733f4de187":
{"_id":{"$id":"5c4eda054db9aa733f4de187"},
"id":"3059b782-2b54-4234-a88f-c8299e26e4c1",
"personnelNumber":6,
"firstName":"John",
"lastName":"Doe",
"contactDetails":{"email":"john.doe@example.com","phone":"+49 (0) 1234 123 45 67","mobile":"","fax":"+49 (0) 1234 567 89 00"},
"address":{"street":"","postcode":"","city":"","country":""},
"hiredAt":{"sec":1206608001,"usec":0},
"createdBy":"Personalleiter Max Mustermann","createdAt":{"sec":1206608001,"usec":0}}]
```

I don't think we will actually be able to reproduce the issue. I would suggest to close it for now.
I can re-open it, if it happens again. I will be working a lot on this project in order to test the power of Fusio. :+1:

**Comment by chriskapp** [comment]
ok great :thumbsup: then I will close this issue for now but feel free to reopen it if you have any further information. Also if you have any issues or ideas regarding Fusio please let me know.
