### ISSUE TITLE
Get slow response

### ISSUE THREAD

**Issue by Juk7** [apioo/fusio#216]
Hello, I have created a web service with a specific parameter to let the user ask for max number of elements.

I'm using my own PHP file launched with PHP Processor to get data (I construct an associative array and I'm using at last of my code a $response->build call).

The problem is that the response is slow to obtained  because of the amount of data dealed by Fusio.

- The global time is 13,5 second to get my data with the API. It's very slow.
- In PHP, if I put a _die()_ juste before $reponse->build, the time elapsed is 2,5 sec. Not too bad
- If I try _die(json_encode($data))_ just before $response->build, the time elapsed is 6,5 sec. The json_encode is slow.

What can I do in Fusio to reduce the time ?
Thank you

**Comment by chriskapp** [comment]
Hi, so 13,5 second sounds really slow. Maybe you try to serialize a very large amount of data? In general I would recommend to limit the size of the response data and the user can then obtain more data by providing i.e. a start index.

**Comment by chriskapp** [comment]
I will close this issue since it looks like there is nothing more to do.
