### ISSUE TITLE
Return mysql Json object

### ISSUE THREAD

**Issue by alexfok007** [apioo/fusio#218]
Hi i am facing problems with return the MYSQL JSON fields values.

In fields labels , i use JSON and stored in format` [{"id": 1}, {"id": 2}, {"id": 3}]`

```
{
    "totalCount": 14999,
    "entries": [
        {
            "id": 2,
            "file_name": "ABC",
            "create_date": "2019-03-08 10:01:07",
            "labels": "[{\"id\": 1}, {\"id\": 2}, {\"id\": 3}]"
        }
    ]
}
```
It should be like this....

```
{
    "totalCount": 14999,
    "entries": [
        {
            "id": 2,
            "file_name": "ABC",
            "create_date": "2019-03-08 10:01:07",
            "labels": [{"id": 1}, {"id": 2}, {"id": 3}]
        }
    ]
}
```

**Comment by chriskapp** [comment]
Hi, so so the SQL-Table Action can not detect whether the row contains JSON. In this case you would need to manually decode the JSON i.e. with the PHP-Sandbox action.

**Comment by alexfok007** [comment]
> Hi, so so the SQL-Table Action can not detect whether the row contains JSON. In this case you would need to manually decode the JSON i.e. with the PHP-Sandbox action.

Yes, i done using for loop to convert. thanks.

**Comment by chriskapp** [comment]
ok great, then I will close this issue
