### ISSUE TITLE
class list not loaded on Fusio app (in connection) and Missing authorization issue

### ISSUE THREAD

**Issue by SaudAlghamdi** [apioo/fusio#219]
Hello, 

I added tow adapters sql and http and I don't found them in connections
and the same for all other sections like app and action 

also when I try to create app or anything i face this message 
`Missing authorization header in /var/www/fusio/vendor/fusio/impl/src/Filter/Authentication.php on line 124`

Could you help me to solve this issue ? 

Note : 
adapter created using those commands and succeed: 
```
composer require fusio/adapter-sql
php bin/fusio system:register Fusio\Adapter\Sql\Adapter
```

Server Details : 
- Centos 7 
- Apache Web server

Finally this is the stacktrace from console:

`fusio.min.js:195 GET http://142.93.174.130/index.php/backend/connection/list 401 (Unauthorized)
(anonymous) @ fusio.min.js:195
sendReq @ fusio.min.js:195
serverRequest @ fusio.min.js:195
processQueue @ fusio.min.js:196
(anonymous) @ fusio.min.js:196
$digest @ fusio.min.js:197
$apply @ fusio.min.js:197
(anonymous) @ fusio.min.js:198
defaultHandlerWrapper @ fusio.min.js:193
eventHandler @ fusio.min.js:193
fusio.min.js:196 Possibly unhandled rejection: {"data":{"success":false,"title":"PSX\\Http\\Exception\\UnauthorizedException","message":"Missing authorization header in /var/www/fusio/vendor/fusio/impl/src/Filter/Authentication.php on line 124","trace":"#0 /var/www/fusio/vendor/psx/http/src/Filter/FilterChain.php(110): Fusio\\Impl\\Filter\\Authentication->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#1 /var/www/fusio/vendor/psx/http/src/Filter/UserAgentEnforcer.php(43): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#2 /var/www/fusio/vendor/psx/http/src/Filter/FilterChain.php(110): PSX\\Http\\Filter\\UserAgentEnforcer->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#3 /var/www/fusio/vendor/psx/framework/src/Loader/Loader.php(123): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#4 /var/www/fusio/vendor/psx/framework/src/Loader/Loader.php(102): PSX\\Framework\\Loader\\Loader->execute(Array, Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#5 /var/www/fusio/vendor/psx/framework/src/Dispatch/Dispatch.php(125): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(Fusio\\Impl\\Loader\\Context))\n#6 /var/www/fusio/vendor/psx/framework/src/Environment/WebServer/Engine.php(47): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#7 /var/www/fusio/vendor/psx/framework/src/Environment/Environment.php(67): PSX\\Framework\\Environment\\WebServer\\Engine->serve(Object(PSX\\Framework\\Dispatch\\Dispatch), Object(PSX\\Framework\\Config\\Config))\n#8 /var/www/fusio/public/index.php(29): PSX\\Framework\\Environment\\Environment->serve()\n#9 {main}","context":"120                 } else {\n121                     throw new UnauthorizedException('Invalid access token', 'Bearer', $params);\n122                 }\n123             } else {\n<b>124                 throw new UnauthorizedException('Missing authorization header', 'Bearer', $params);\n</b>125             }\n126         } else {\n127             $app = new Model\\App();\n128             $app-&gt;setAnonymous(true);\n"},"status":401,"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","url":"http://142.93.174.130/index.php/backend/connection/list","headers":{"Accept":"application/json, text/plain, */*","Authorization":"Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xMjcuMC4wLjEiLCJzdWIiOiIyYTExZjk5NS0xMzA2LTU0OTQtYWFhNS01MWM3NGQ4ODJlMDciLCJpYXQiOjE1NTIzOTU2NDksImV4cCI6MTU1MjM5OTI0OSwibmFtZSI6InNhdWQxMjMifQ.oxf7AoZ8hoYnLYCHRuzseUZDSV4KtiRinI_u5Oppf_E"},"cached":false},"statusText":"Unauthorized","xhrStatus":"complete"}
(anonymous) @ fusio.min.js:196
(anonymous) @ fusio.min.js:195
processChecks @ fusio.min.js:196
$digest @ fusio.min.js:197
$apply @ fusio.min.js:197
done @ fusio.min.js:195
completeRequest @ fusio.min.js:195
xhr.onload @ fusio.min.js:195
load (async)
(anonymous) @ fusio.min.js:195
sendReq @ fusio.min.js:195
serverRequest @ fusio.min.js:195
processQueue @ fusio.min.js:196
(anonymous) @ fusio.min.js:196
$digest @ fusio.min.js:197
$apply @ fusio.min.js:197
(anonymous) @ fusio.min.js:198
defaultHandlerWrapper @ fusio.min.js:193
eventHandler @ fusio.min.js:193`

**Comment by chriskapp** [comment]
Hi, so in general you dont need to add the SQL and HTTP adapter since they are installed by default. You should see them under the Connection Panel if you create a new connection.

Regarding your problem, it is probably because your Apache does not redirect the `Authorization` header to Fusio, you need to have a specific mod_rewrite rule in your .htaccess file for this. So I would guess in your case mod_rewrite is not activated. More information at: https://fusio.readthedocs.io/en/latest/basic/installation.html#web-server

**Comment by SaudAlghamdi** [comment]
Thanks it's works for me.
