### ISSUE TITLE
Return single object 

### ISSUE THREAD

**Issue by jan-sp** [apioo/fusio#220]
Hi,

A very basic question (I suppose)

I want to use Fusio to expose the content of some MS SQL tables.  So I did the following:

- Create A connection: OK
- create an Action (connection and Table is filled in...)
- Created a Route and select the action.

All is fine, and the response returns all the rows in the table

My question is the following;
When I want there's only one record returned, I can use the same connection and use an endpoint url like /companies/:id
But how do I pass the id?  Is this possible in the interface of the action?  Are there exemples?

A very basic question, but I'm not familiar with this things...

Tx for helping me out in advance

Kind regards 
Jan

**Comment by chriskapp** [comment]
Hi,

Iam not sure I understand the question correctly but you need to invoke the route with an actual id i.e. `/companies/1` or `/companies/4`. The id is then available as uri fragment at your action.

best regards
Christoph

**Comment by EvoPulseGaming** [comment]
He is talking about the SQL-Table connection type

No, you cannot use this to return a single row, this connection type will return all rows. 
There is an SQL-Select connection type that will allow you to do this, but you will need to write out you sql query by hand.

**Comment by chriskapp** [comment]
I will close this issue since it looks like everything is answered
