### ISSUE TITLE
Failed to load resource: the server responded with a status of 405

### ISSUE THREAD

**Issue by wittawoot** [apioo/fusio#223]
In action page when Execute then not respond .it return error as below ..
![Screen Shot 2562-03-24 at 18 14 39](https://user-images.githubusercontent.com/2696885/54878571-3a64f580-4e61-11e9-9e08-4bdcbbdf5f6d.jpg)

**Comment by chriskapp** [comment]
Hi, in general 405 means that the HTTP status is not supported, could you take a look at the error logs, maybe there are some more information about the problem?

**Comment by EvoPulseGaming** [comment]
Stale issue, suggest closing.
