### ISSUE TITLE
Unable to add adapters. "Provided adapter class does not exist".

### ISSUE THREAD

**Issue by marcosandresacevedo** [apioo/fusio#23]
Hi,

When trying to add an adapter on Fusio 0.5.0, specifically the `fusio/adapter-http` the following message is thrown when executing the command `php bin/fusio system:register Fusio\Adapter\Http\Adapter`:

`Provided adapter class does not exist`

I successfully ran the required composer command `composer require fusio/adapter-http` before this.

Where can I start looking in to, so I can overcome this issue?

**Comment by marcosandresacevedo** [comment]
I also notice that I don't have Action Classes that I had available in a previous version installation. I only have  `SQL-Table, Util-Static-Response and V8-Processor` listed in the Class drop down when adding a new Action.

I also get the same error trying to add the `fusio/adapter-sql` after running `php bin/fusio system:register Fusio\Adapter\Sql\Adapter`. Although I'm not sure if this adapter is part of the default installation or is different than the `SQL-Table` adapter already available.

Perhaps there might be something miscofigured that is preventing all adapters from loading properly?

**Comment by marcosandresacevedo** [comment]
It seems that I might be jumping the gun on a few things. As far as I could tell from the commits, a bunch of Adapters were removed when going from 0.4.1 to 0.5.0. I ran into the commit that adds the V8 Processor documentation, and I might infer that going forward the intended use is to use JavaScript for doing database CRUD as well as using HTTP all within V8.

However, I'm not certain if the Adapter loading is intended to be removed or if I should still be able to load Adapters in version 0.5.0. As far as I can tell, the issue remains.

**Comment by k42b3** [comment]
Hi, yes with the [0.5.0] release we have removed some adapters in favor of the 
v8 processor. So the idea is that you now either write your API logic in javascript or in php.

Regarding the adapter registration. Adapters are also supported in the 0.5 version. 
If you register the http adapter you should get two new actions. I think in your case 
something went wrong with the compose require command:

```
composer require fusio/adapter-http
```

To check whether the installation was successful you can take a look at the 
vendor folder and check whether the folder `vendor/fusio/adapter-http` exists.
In your composer.lock file you should also see the `fusio/adapter-http` package 
with a version like `^0.2.1`. Then you should be able to register the adapter:

```
php bin/fusio system:register Fusio\Adapter\Http\Adapter
```

I have just tested the registration and as far as I can tell everything works as
expected.

[0.5.0]: http://fusio-project.org/blog/post/version-0.5-released

**Comment by marcosandresacevedo** [comment]
Yes. I have verified that the `vendor/fusio/adapter-http` directory is created and that the composer.lock file contains the `fusio/adapter-http` package version `0.2.1`. I am still unable to register the adapter. I noticed that when running the command  `composer require fusio/adapter-http` I'm doing it as `sudo composer require fusio/adapter-http`. I suspect that this is causing the `vendor/fusio/adapter-http` directory  (and dependencies) to be created with owner:group  root:root and 755 permissions. I tried to eliminate the possibility of permissions being the problem by running a `sudo chmod -R 777` on the Fusio installation and all its subdirectories and tried to run the `composer require fusio/adapter-http` and `php bin/fusio system:register Fusio\Adapter\Http\Adapter` commands without sudo but the error of `Provided adapter class does not exist` remained.

I suspect something might have broken with the Adapter installation when using my particular path configurations. Is there any place that there might be a hard coded reference as to where the bin/fusio script looks for files or the fully qualified class name when adding an Adapter?

My Fusio installation is on `/var/www/api.somedomain.come/public_html/` and in this directory the files are listed as such:

`README.md`
`LICENSE`
`container.php`
`CHANGELOG.md`
`src`
`cache`
`fusio_0.5.0.zip`
`public`
`configuration.php`
`bin`
`composer.json`
`composer.lock`
`vendor`

My DocumentRoot in Apache for the Virtual Host configuration points to the `public` sub directory in this directory.

I also tried applying the proper owner:group (which is `www-data`) to the directories created after running the `sudo composer require fusio/adapter-http` command but this didn't help as I kept getting the same message trying to register the adapter.

**Comment by k42b3** [comment]
Can you check whether the file `vendor/composer/autoload_psr4.php` contains an entry `'Fusio\\Adapter\\Http\\' => array($vendorDir . '/fusio/adapter-http/src')`. If not you could run `composer dump-autoload` to regenerate the autoload file.

**Comment by mortezaf** [comment]
Hi brother,I have the same problem and `autoload_psr4.php` contains an entry 
` 'Fusio\\Adapter\\Amqp\\' => array($vendorDir . '/fusio/adapter-amqp/src'),
`
Can you help me?

**Comment by mortezaf** [comment]
I found the solution
The class namespace must be placed inside ""
`php bin/fusio system:register "Fusio\Adapter\Amqp\Adapter"`

**Comment by linuxmalaysia** [comment]
Please update the docmentation for adapter to include "". I had same problem installing soap adapter and this resolved my problem.

php bin/fusio system:register "Fusio\Adapter\Soap\Adapter"

> I found the solution
> The class namespace must be placed inside ""
> `php bin/fusio system:register "Fusio\Adapter\Amqp\Adapter"`
