### ISSUE TITLE
Backend permissions

### ISSUE THREAD

**Issue by chriskapp** [apioo/fusio#231]
Currently we have the user status `Administrator` which allows a user to login at the backend. With this status the user can access all aspects of the backend. It would be great to create another permission layer which would allow to give access to only a certain subset of the features. I.e. we could create a role `Developer` which can only edit actions and schemas but is not able to create user or edit routes.

**Comment by chriskapp** [comment]
Through the new scopes for the backend/consumer endpoints we can give fine grain access to every user based on the assigned scopes.

**Comment by jothikannan** [comment]
Hi @chriskapp 

I have created an cosumer with backend scope, and when I try to login as the created consumer it says unknown credentials. 

A consumer can access the dashboard when he/she has a backend scope? P

**Comment by chriskapp** [comment]
Hi, yes if a user has the backend scope he can login to the backend. So you can create a user with backend and consumer scopes to access both apps. In your case maybe the user has the wrong status, the status must be "Administrator" to be able to login to the backend.

**Comment by jothikannan** [comment]
Hi,

I am super confused. If a user has a consumer and backend can able to login into admin dashboard or not? Or only the user who has Administrator only can access the dashboard? Please reply.

**Comment by chriskapp** [comment]
So basically only the user which have the status `Administrator` but those users must also have the backend scope assigned. If a user has the backend scope he can basically modify your complete API, for security reasons we have a separated admin status.

**Comment by jothikannan** [comment]
thanks @chriskapp , now I got it and completely understand how fusio works.
