### ISSUE TITLE
My installation works fine except developer portal

### ISSUE THREAD

**Issue by harshalone** [apioo/fusio#234]
My installation works fine except developer portal

I have installed Fusio on my shared hosting with softaculous

Everything works fine except my developer portal looks like this
https://api.bebluebox.com/public/developer/

I am guessing its related to some path issue. how can I fix it?

**Comment by chriskapp** [comment]
Hi, sure so the problem is that you need to set the correct `<base href="...">` path at the `public/developer/index.html` file, then it should work as expected.

**Comment by chriskapp** [comment]
I think we can close this issue, in the next release we have also the new marketplace which solves this problem by automatically creating the fitting base path for the app.
