### ISSUE TITLE
Specify HTTP protocol in action

### ISSUE THREAD

**Issue by RewoDevNull** [apioo/fusio#235]
Currently we need the ability to specify the http protocol (1.0, 1.1, 2.0) in some actions using the http processor.

I ran into an issue with curl which is used by guzzle and triggered by the HttpProcessor + HttpEngine. If you have curl prior version 7.36 installed it will generate a invalid chunk encoding error by using the HTTP1.1 protocol. Our hosting provider doesn't want to upgrade curl (currently installed in version 7.29) because its very coupled with the operating system CentOS, libcurl, etc. and could possibly not ensure the system stability then.
curl has fixed this issue after version 7.36 by itself.

I figured out by manually setting the http version ('version' => '1.0') onto HTTP1.0 in [Fusio\Adapter\Http\Action\HttpEngine](https://github.com/apioo/fusio-adapter-http/blob/master/src/Action/HttpEngine.php) it all works fine and as espected:

```
public function handle(RequestInterface $request, ParametersInterface $configuration, ContextInterface $context)
{
    // do some stuff...
    
    $options = [
        'headers' => $headers,
        'query' => $request->getParameters(),
        'http_errors' => false,
        'version' => '1.0',
    ];
    
    // do more stuff and handle request...
}
```

**Comment by RewoDevNull** [comment]
I've added a pull request onto the related project ([fusio-adapter-http](https://github.com/apioo/fusio-adapter-http)): 
[Pull request: added http protocol version](https://github.com/apioo/fusio-adapter-http/pull/1)

**Comment by chriskapp** [comment]
Great, I have just merged the PR and tagged also a new version.
