### ISSUE TITLE
cant login after installation

### ISSUE THREAD

**Issue by mahathirm** [apioo/fusio#237]
![image](https://user-images.githubusercontent.com/32903354/60944711-c832f680-a313-11e9-97d9-af63561dd3f4.png)

i have a problem after installation everytime i tried to login i got an eror says authentication failed n i try to inspect and here what i hv got "fusio.min.js:187 POST http://10.36.27.16/index.php/backend/token 404 (Not Found)"

**Comment by chriskapp** [comment]
Hi, this sounds like the backend app does not find the correct Fusio API url. At the index.htm you can manually define the `fusio_url`. You can also take a look at our documentation for more information: https://fusio.readthedocs.io/en/latest/basic/installation.html#backend

**Comment by mahathirm** [comment]
![image](https://user-images.githubusercontent.com/32903354/61019605-f9b7ca80-a3c4-11e9-955c-c1400c64b74f.png)
hi, i ready tried that one but i have the same problem/trouble like that in the picture

**Comment by chriskapp** [comment]
Ok, do you have correctly configured the `fusio_url` at your `index.htm` file? The backend app should issue an AJAX call to the `/backend/token` endpoint, could you show me the response of this call.

**Comment by mahathirm** [comment]
![problem](https://user-images.githubusercontent.com/32903354/61193216-35fc6b00-a6e4-11e9-9b61-651b737b8c3a.JPG)
i have correctly configured the fusio_url at my index.htm same as the link https://fusio.readthedocs.io/en/latest/basic/installation.html#backend, and i still have the same problem

n i have check the network no ajax request
![problem2](https://user-images.githubusercontent.com/32903354/61193279-ac00d200-a6e4-11e9-8111-62408cfe0b6d.JPG)

**Comment by chriskapp** [comment]
Is this issue resolved or do you still have problems to login?

**Comment by chriskapp** [comment]
I will close this issue since there is no response.
