### ISSUE TITLE
Developer app base path configuration should be detected or part of the configuration file.

### ISSUE THREAD

**Issue by marcosandresacevedo** [apioo/fusio#24]
For the apps that come as part of the Fusio installation there should be a way for them to detect their proper base element eg. `<base href="/projects/fusio/public/developer/">` so that upon installation they're not broken out of the box if the Fusio installation does not follow the expected hard coded paths in the environment it was just installed.

Link to the groups discussion for more detail: [https://groups.google.com/forum/#!topic/fusio/1B5Fv8ZeKu0](https://groups.google.com/forum/#!topic/fusio/1B5Fv8ZeKu0)

**Comment by k42b3** [comment]
Our docker image configures automatically the correct base path. For normal installations we have a javascript method which tries to guess the correct path.
