### ISSUE TITLE
cant load the fusio

### ISSUE THREAD

**Issue by mahathirm** [apioo/fusio#241]
![image](https://user-images.githubusercontent.com/32903354/61102450-05c08c80-a498-11e9-83b5-32d61df90d7f.png)
hi, i have some trouble here i follow your step in the question before, and after iam follow your step instruction i got have problem like this. do you have a solution?

**Comment by chriskapp** [comment]
Hi, ok mhh, maybe the `fusio_url` is not correctly configured at your `index.htm` page, since it says `http://localhost:8080/...` is not a function.

**Comment by mahathirm** [comment]
![image](https://user-images.githubusercontent.com/32903354/61195498-94304a80-a6f2-11e9-8ae6-7428ca6150a0.png)
this is my configuration, i already set the fusioUrl but the error say that http://localhost:8080/... is not a function. so what shoud i do? should i change che fusioUrl configuration? or is there any problem with my fusio.min.js?

**Comment by chriskapp** [comment]
in your Screenshot you can see `(true)` behind the url string, this causes javascript to try to invoke the string as function.

**Comment by chriskapp** [comment]
I guess this issue is now solved, so I will close this issue.
