### ISSUE TITLE
Certain route paths will fail

### ISSUE THREAD

**Issue by EvoPulseGaming** [apioo/fusio#242]
If there is some sort of internal restricted names for paths, it would be nice if the backend blocks you when using them.

Create a route using the below paths. Use DEFAULT settings for everything.
fail = 
{
    "success": false,
    "title": "Internal Server Error",
    "message": "Unknown location"
}

/properties = fails
/p = works
/pp = works
/pr = fails
/prr = fails
/prop = fails
/props = fails
/roperties works
/pl = fails
/pz = fails

/test =works
/tess =works
/test2 = works

**Comment by chriskapp** [comment]
Hi, so in Fusio there are some path restricted but you will receive an error if you try to create a route for those paths, the following paths are reserved: https://github.com/apioo/fusio-impl/blob/master/src/Backend/Filter/Routes/Path.php#L38
Iam not sure why the paths you mentioned fail but Fusio has there no internal restriction. Could you set the debug mode to `true` in the `configuration.php` and show me the stacktrace of the error.

**Comment by EvoPulseGaming** [comment]
{
  "success": false,
  "title": "PSX\\Framework\\Loader\\InvalidPathException",
  "message": "Unknown location in /home/evopulse/public_html/evotracker/vendor/psx/framework/src/Loader/Loader.php on line 104",
  "trace": "#0 /home/evopulse/public_html/evotracker/vendor/psx/framework/src/Dispatch/Dispatch.php(125): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(Fusio\\Impl\\Loader\\Context))\n#1 /home/evopulse/public_html/evotracker/vendor/psx/framework/src/Environment/WebServer/Engine.php(47): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#2 /home/evopulse/public_html/evotracker/vendor/psx/framework/src/Environment/Environment.php(67): PSX\\Framework\\Environment\\WebServer\\Engine->serve(Object(PSX\\Framework\\Dispatch\\Dispatch), Object(PSX\\Framework\\Config\\Config))\n#3 /home/evopulse/public_html/evotracker/public/index.php(29): PSX\\Framework\\Environment\\Environment->serve()\n#4 {main}",
  "context": "100             $controller = $this-&gt;controllerFactory-&gt;getController($context-&gt;getSource(), $context);\n101 \n102             $this-&gt;execute($controller, $result, $response);\n103         } else {\n<b>104             throw new InvalidPathException('Unknown location', $request);\n</b>105         }\n106     }\n107 \n108     /**\n"
}

**Comment by EvoPulseGaming** [comment]
I also compared the stack trace between using 
/pr
/production

and the trace is exactly the same.

**Comment by kidino** [comment]
I am having similar problem. And here's the wierd thing, for some of my friends, it works with double slashes, ie,

domain.com//publishing/author
domain.com//publisher/author

**Comment by chriskapp** [comment]
Ok, mhh so unfortunately I could not reproduce the problem yet. I have created two routes on a new Fusio installation and I could call `/pr` and `/production` which each have called a different action. Could you give me some instructions how I could reproduce this issue?

**Comment by EvoPulseGaming** [comment]
Sorry, I cannot give you more details but this one last piece of info:

I am using KnownHost's hosting service, they have CPanel, and I used Softaculous to install fusio, using what I thought was rather generic defaults. 

My step for reproduction are simple, create a new route, and without changing anything save it. Test.

**Comment by EvoPulseGaming** [comment]
I can also confirm that using // works.....
https://evotracker.evo-pulse.com//pr <-This is now a valid route

**Comment by chriskapp** [comment]
Ok, since you mentioned Softaculous it could be that there is a problem with their .htaccess configuration. I remember previous issues regarding this. Otherwise could you make a plain Fusio installation without CPanel and Softaculous to see whether you can reproduce this problem?

**Comment by EvoPulseGaming** [comment]
Is there a way I can export my stuff without making a "full backup"? Then I can get back to testing this

**Comment by EvoPulseGaming** [comment]
So I went through any .htaccess file, in the root, publichtml and my fusio folder. The only one that has anything is the one generated for fusio by cpanel, its as follows:

<IfModule mod_alias.c>
RedirectMatch 301 ^/$ https://evotracker.evo-pulse.com/public/index.php
</IfModule>
# php -- BEGIN cPanel-generated handler, do not edit
# Set the “ea-php72” package as the default “PHP” programming language.
<IfModule mime_module>
AddType application/x-httpd-ea-php72 .php .php7 .phtml
</IfModule>
# php -- END cPanel-generated handler, do not edit

**Comment by chriskapp** [comment]
In the past I have talked with a Softaculous developer and I have tried to convince him that it would be great to create a correct vhost entry for Fusio where the document root is at the `public/` folder so that you would have urls like: https://evotracker.evo-pulse.com/my/api Then you could also remove the `.htaccess` file at the `public/` folder.

We have also an example apache vhost entry in our documentation: https://fusio.readthedocs.io/en/latest/basic/installation.html#apache

But I guess I could not convince him, so they have this `.htaccess` solution which is not ideal. Basically it means that your document root is not at the `public/` folder instead every request gets redirected to the `public/` folder. This means that every request returns first a redirect before it hits your API and worse it also means that you can access every file under `src/` `vendor/` etc. So maybe you can try to make a support request at Softaculous that they properly configure Fusio, maybe with a link to this issue.

**Comment by EvoPulseGaming** [comment]
I've contacted them, I'll let you know how it goes

**Comment by EvoPulseGaming** [comment]
Their reply is as follows:

Hi,

We had a discussion with Fusio developer to use Fusio with re-direction. Softaculous do not have rights to edit/update server's Apache conf. Because of this restriction we handle redirection using .htaccess.

Also, even if users make manual installation on Shared hosting server then they won't be able to make changes in vhost on their own. We do not have any alternate method to install Fusio

**Comment by EvoPulseGaming** [comment]
I've also asked them about vhost. In cpanel I can set the subdimains root document to /public, and then I could remove the redirect from the .htaccess file. I'm asking them if that is the equivalent of what Fusio requires.

**Comment by EvoPulseGaming** [comment]
So, they replied, that setting the subdomain's document to /public and removing the re-write from the .htaccess file, would be the correct way to install this as the software requires.

However upon further testing, I still cannot get routes like /pr to work unless using double slashes (//pr)

**Comment by EvoPulseGaming** [comment]
SOLVED!!!!
Updated to 1.8.0, and noticed that marketplace wouldn't work.
Created fresh install of 1.8.0, did some comparisons, and noticed that configuration.php has some new stuff that didn't get put in via the update.

Added psx_dispatch (changed 'index.php/' to '' as per the instructions)
added the fusio marketplace url (this now works)

.env file: removed "/public" from the end of my url
Cpanel: verified that my subdomains document root pointed to /public

profit!!! /pr and variations work now!
***Note: its possible that removing /public from my .env url was the actual solution.

Anyways, it would be nice if this was in the documentation under the CPanel section

**Comment by EvoPulseGaming** [comment]
> 
> 
> I am having similar problem. And here's the wierd thing, for some of my friends, it works with double slashes, ie,
> 
> domain.com//publishing/author
> domain.com//publisher/author

please view my last comment here, should solve your issues!
