### ISSUE TITLE
Feature Request - Provide option to clear RESTful API service cache at defined time interval(s).

### ISSUE THREAD

**Issue by kvnlwlls** [apioo/fusio#243]
Christoph -

Requesting a Fusio feature to clear the RESTful API service cache (in folder <install-dir>/api) at defined time interval(s).

Thankyou.

-Kevin

**Comment by chriskapp** [comment]
Hi, I think we could add a new CLI command i.e. `bin/fusio system:clear_cache` which then deletes all cache files. A user could then simply setup a cron to execute this command in specific intervals.

**Comment by kvnlwlls** [comment]
Christoph -

That would be great; and would provide the developer flexibility in how and
when to remove the cached results.

Thankyou.

Regards,

-Kevin

**Comment by chriskapp** [comment]
So we have added the command which is then included in the next release:
https://github.com/apioo/fusio-impl/commit/684c6eacba4106ca92ad8bfc08f2afa14ec22993

**Comment by kvnlwlls** [comment]
Christoph -

That's Great.  Looking forward to the new release.

 -Kevin

**Comment by kvnlwlls** [comment]
Christoph -

Great to see the API cache removal in the newest release.

-Kevin
