### ISSUE TITLE
Removing /index.php/ from swagger

### ISSUE THREAD

**Issue by thenixtone** [apioo/fusio#248]
Can't seem to find any documentation or anywhere in any of the files to do this..?

In the servers dropdown my swagger has my domain with /index.php/ appended as well as when using the 'Try out' feature, it hits the same url.

My htaccess and vhost are fine and work when I hit it externally with just domain.com/whatever

I just want the frontend to not display it

EDIT: This is also the same in /documentation

**Comment by chriskapp** [comment]
Hi, sure so in the `configuration.php` file you need to set:
```
'psx_dispatch' => '',
```

by default the value is `index.php/`, which causes that Fusio builds such urls.

**Comment by thenixtone** [comment]
Awesome, cheers, works perfect
