### ISSUE TITLE
Update backend app

### ISSUE THREAD

**Issue by chriskapp** [apioo/fusio#253]
Currently the backend app https://github.com/apioo/fusio-backend is based on Angular 1.7 we should migrate this app to the latest Angular https://angular.io/ version and also use our internal SDK https://www.npmjs.com/package/fusio-sdk for all API communication. This means also we need to migrate all JS files to TypeScript. We should also use the Angular/Bootstrap https://ng-bootstrap.github.io/ project and check whether all needed components are available.

**Comment by chriskapp** [comment]
Maybe we can take also a look at other Angular UI Frameworks:
* https://material.angular.io/
* https://github.com/NG-ZORRO/ng-zorro-antd

**Comment by ratsey** [comment]
VMWare's [Clarity](https://clarity.design/) is very clean looking and incredibly easy to work with.

**Comment by ratsey** [comment]
Funny that I'm finding my post from two years ago when I came to make a comment about updating to Angular.

A short term improvement would be to remove the paging from Route Paths and Actions and have them as a scrollable, sorted, list.

FYI, I retract my comment about Clarity. It's good - but I'm moving back to vanilla Material design.

**Comment by chriskapp** [comment]
Hey @ratsey, yes I have also added a similar issue s. https://github.com/apioo/fusio-apps-backend/issues/24 to the backend app since this behavior has also bothered me. I think also Angular is the correct choice and in combination with https://ng-bootstrap.github.io/ we have a good replacement. The issue is also on top of my todo list but it takes some time since the backend app has grown a bit. The great thing about Angular is that we then can also include the https://www.npmjs.com/package/ngx-typeschema-editor component which we use at https://apigen.app/entity so that we have a visual schema editor at the backend.
