### ISSUE TITLE
[Resolved] InvalidFieldNameException

### ISSUE THREAD

**Issue by billyhiuwali** [apioo/fusio#261]
i have gotten this error message after i installed 1.8v fusio . the error is showed below.
it seems like method.operation_id field is missing ,but i am not sure if this is the root cause.
do you have any idea? Thank you 

**{
    "success": false,
    "title": "Doctrine\\DBAL\\Exception\\InvalidFieldNameException",
    "message": "An exception occurred while executing 'SELECT method.public,\n                       method.operation_id,\n                       method.action,\n                       method.status,\n                       method.costs,\n                       method.action_cache\n                  FROM fusio_routes_method method\n                 WHERE route_id = ?\n                   AND version = ?\n                   AND method = ?\n                   AND active = ?' with params [104, 1, \"GET\", 1]:\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'method.operation_id' in 'field list' in C:\\xampp\\htdocs\\fusio\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Driver\\AbstractMySQLDriver.php on line 60",
    "trace": "#0 C:\\xampp\\htdocs\\fusio\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php(169): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 C:\\xampp\\htdocs\\fusio\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\DBALException.php(145): Doctrine\\DBAL\\DBALException::wrapException(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'An exception oc...')\n#2 C:\\xampp\\htdocs\\fusio\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Connection.php(911): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'SELECT method.p...', Array)\n#3 C:\\xampp\\htdocs\\fusio\\vendor\\doctrine\\dbal\\lib\\Doctrine\\DBAL\\Connection.php(545): Doctrine\\DBAL\\Connection->executeQuery('SELECT method.p...', Array, Array)\n#4 C:\\xampp\\htdocs\\fusio\\vendor\\fusio\\impl\\src\\Table\\Routes\\Method.php(198): Doctrine\\DBAL\\Connection->fetchAssoc('SELECT method.p...', Array)\n#5 C:\\xampp\\htdocs\\fusio\\vendor\\fusio\\impl\\src\\Service\\Routes\\Method.php(226): Fusio\\Impl\\Table\\Routes\\Method->getMethod(104, 1, 'GET')\n#6 C:\\xampp\\htdocs\\fusio\\vendor\\fusio\\impl\\src\\Filter\\AssertMethod.php(79): Fusio\\Impl\\Service\\Routes\\Method->getMethod(104, 1, 'GET')\n#7 C:\\xampp\\htdocs\\fusio\\vendor\\psx\\http\\src\\Filter\\FilterChain.php(110): Fusio\\Impl\\Filter\\AssertMethod->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#8 C:\\xampp\\htdocs\\fusio\\vendor\\psx\\http\\src\\Filter\\UserAgentEnforcer.php(43): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#9 C:\\xampp\\htdocs\\fusio\\vendor\\psx\\http\\src\\Filter\\FilterChain.php(110): PSX\\Http\\Filter\\UserAgentEnforcer->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#10 C:\\xampp\\htdocs\\fusio\\vendor\\psx\\framework\\src\\Loader\\Loader.php(123): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#11 C:\\xampp\\htdocs\\fusio\\vendor\\psx\\framework\\src\\Loader\\Loader.php(102): PSX\\Framework\\Loader\\Loader->execute(Array, Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#12 C:\\xampp\\htdocs\\fusio\\vendor\\psx\\framework\\src\\Dispatch\\Dispatch.php(125): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(Fusio\\Impl\\Loader\\Context))\n#13 C:\\xampp\\htdocs\\fusio\\vendor\\psx\\framework\\src\\Environment\\WebServer\\Engine.php(47): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#14 C:\\xampp\\htdocs\\fusio\\vendor\\psx\\framework\\src\\Environment\\Environment.php(67): PSX\\Framework\\Environment\\WebServer\\Engine->serve(Object(PSX\\Framework\\Dispatch\\Dispatch), Object(PSX\\Framework\\Config\\Config))\n#15 C:\\xampp\\htdocs\\fusio\\public\\index.php(29): PSX\\Framework\\Environment\\Environment->serve()\n#16 {main}",
    "context": "56  \n57              case '1054':\n58              case '1166':\n59              case '1611':\n<b>60                  return new Exception\\InvalidFieldNameException($message, $exception);\n<\/b>61  \n62              case '1052':\n63              case '1060':\n64              case '1110':\n"
}**

**Comment by chriskapp** [comment]
Hi, it looks like you upgrade an existing installation and you have not executed all migrations. Can you execute the command `php bin/fusio install` to execute all missing migrations?

**Comment by billyhiuwali** [comment]
[
![Capture](https://user-images.githubusercontent.com/31437338/65375065-db732280-dcc3-11e9-94ff-64a59c5636e8.PNG)
](url)


Hi Chris . 

i was installing fusio as a new project. i have edited ".env " file  and then run "php bin/fusio install".
i have uploaded the error message showed during the installation . i think there is some syntax error in the installation file.

**Comment by chriskapp** [comment]
ok, I see that you are using MariaDB, I guess it is a problem with our database abstraction layer and MariaDB could you tell me which version do you use?

**Comment by billyhiuwali** [comment]
Hi Chris. 
My maria DB version is 10.4.6

**Comment by chriskapp** [comment]
ok, I looked it up and currently only version `10.3` is tested, could you try to use version `10.3` of MariaDB to check whether this solves the problem? See https://travis-ci.org/doctrine/dbal

**Comment by billyhiuwali** [comment]
Hi Chris 
i have installed it again  with MariaDB 10.3.18
However , the problem is still there.

**Comment by billyhiuwali** [comment]
Hi Chris,

i have tried version 10.3.4 . it does not work. 
However , it works on MariaDB version 10.2.27
The problem is resolved. 

Thank you so much.

**Comment by chriskapp** [comment]
great, then thanks for testing and good to know that the installation works only with MariaDB 10.2.x. Newer MariaDB versions will be probably supported if the DBAL library releases a newer version. I will then close this issue.
