### ISSUE TITLE
Failed API Test

### ISSUE THREAD

**Issue by Akaie** [apioo/fusio#262]
I've been trying to set up the todo test API and have been getting the error "ERROR: Failed API Test. Username/password incorrectly set up at Fusio side." in response when I try to login to consumer/login. From what I can tell, it's not returning a token. I've read a great deal of documentation but everything I've tried hasn't helped.

**Comment by chriskapp** [comment]
Hi, ok do you have any additional error information i.e. stacktrace of the exception. You receive this error if you try to login at the backend?

**Comment by Akaie** [comment]
I can log into the backend just fine, its when I try to access the API itself and it brings me to the Test API Credential screen. As far as I checked from the backend, there's no errors or logs of the interaction. I ran a script I know works as it worked when I connected to someone else's fusio based API, and apparently, I'm getting nothing in return to the calls.

**Comment by chriskapp** [comment]
Ok, Iam not sure what you exactly mean by the `Test API Credential screen`. Could you show me a screenshot and the complete url. Maybe it is related to some customization which is not part of Fusio?

**Comment by Akaie** [comment]
Oh, I see, it was loading the index.php I had, which was an API credentials test. The page produces the error I'm getting when the token isn't set. Sorry for the confusion. 

The page is putting in a request to http://localhost/fusio/public/consumer/login. Is that the right URL to do credential checking?

**Comment by chriskapp** [comment]
Yes, so the `/consumer/login` endpoint is the correct endpoint to obtain an token to access the API. It could be that you have mod_rewrite not enabled so you need to make a request using `index.php/` i.e. http://localhost/fusio/public/index.php/consumer/login

**Comment by Akaie** [comment]
consumer/login still isn't returning a token, but other queries that don't need authorization are now working with that index.php/ suggestion. Additionally, is there any way to sanitize SQL queries?

**Comment by chriskapp** [comment]
Ok, so this depends always on your action code but I would highly recommend to use prepared statments. If you show me the action code I could also give you some security tips.

**Comment by Akaie** [comment]
I understand the issue with prepared statements. I was mostly wondering if the $connector object had prepared statements or an escape method. The one where you call to your database connection. $connector->getConnection('DBCONNECTION'). Is it just a wrapper to create a PDO connection? There wasn't much documentation on what $connector was.

**Comment by chriskapp** [comment]
Yes, so it returns a doctrine DBAL instance. In our documentation we have also an overview which connection returns which object please take a look at: https://fusio.readthedocs.io/en/latest/development/deploy.html#connection
Most Connections use a well-known library to connect to the fitting service i.e. the SQL Connection returns a `Doctrine\DBAL\Connection` instance, the MongoDB connection a `MongoDB\Database`, etc.

**Comment by Akaie** [comment]
Oh thank you, that's really helpful. Thank you again, you've been a really big help.

**Comment by chriskapp** [comment]
Ok, great, I will then close this issue.
