### ISSUE TITLE
Manually delete User

### ISSUE THREAD

**Issue by billyhiuwali** [apioo/fusio#263]
i found that if i delete a user in dashboard, the user will be disappeared. However, the user record will be remained in Database [table: fusio_user] , and the status will turned from 1 to 3. 
i will manually delete the user in database , in order to create a new one with the same name in Fusio dashboard. i would like to know if this practice is correct. Thanks.

**Comment by chriskapp** [comment]
Hi, yes we dont actually delete a user since the user is referenced in the log and other tables, therefor we dont delete the user but set the status to "deleted". Through this it is also possible to restore a deleted user.

**Comment by billyhiuwali** [comment]
Thanks.
