### ISSUE TITLE
Angular routing does not work in /developer/ application

### ISSUE THREAD

**Issue by soundpress** [apioo/fusio#265]
If trying to go url /developer/login or any other url longer than /developer/ server returns 404
Tried on two configurations:
- Windows 10 x64 + Apache 2.4 + php 7.1 x64
- Azure Ubuntu 18.4 + Apache 2.2.4 + php 7.2

**Comment by chriskapp** [comment]
Hi, I think you need to set the correct base url at the index.html file of the developer app otherwise the html5 routing does not work properly.

**Comment by soundpress** [comment]
Hi, thanks for quick answer
Do you mean <base href="/developer/"> tag or var fusioUrl?
Both seems are set correctly. I can get /developer/login/ page clicking links, can register new user but can not go to page entering url in browser. Also back button does not work.

**Comment by devinbalkind** [comment]
Hi. Is there a way we could access support for this issue?

**Comment by chriskapp** [comment]
Hi, sure so in general the problem should be that the `base` tag of this app is not properly configured since it is required by the router inside the angularjs app. If this is correctly configured Iam not really sure about the current issue, @soundpress what do you mean exactly by: 

> can register new user but can not go to page entering url in browser

If you take i.e. a look at the demo app https://demo.fusio-project.org/developer/documentation you can call such an url in a browser without a problem.

**Comment by soundpress** [comment]
@chriskapp thanks for your reply
By 
> can register new user but can not go to page entering url in browser
I meant that all other application parts work great, I can browse pages clicking links, register new user etc.
The only issue I am having problem with is trying to open internal page by direct link.

After your last message I was trying to set base tag different values but only current value makes application working at all. Any other value causes just printing application template code

![image](https://user-images.githubusercontent.com/9949082/66124257-9799ea80-e5ec-11e9-8357-eedd004f8465.png)

**Comment by chriskapp** [comment]
Ok, in your Screenshot it looks like a wrong base tag and therefor the
Browser cant download the correct js and css. So if you use the "current"
base tag and the css and ja loads properly, it is the correct base path.
Maybe you can also take a look at the demo App to see how to configure the
Developer app.


soundpress <notifications@github.com> schrieb am Do., 3. Okt. 2019, 13:46:

**Comment by soundpress** [comment]
@chriskapp the issue was fixed with help of our front-end developer. The problem was in local .htaccess file. Below is the correct configuration which works. Writing it here cause seems you have removed Developer application from the package.
`
<IfModule mod_rewrite.c>
 RewriteEngine On
 RewriteBase /public/developer/
 RewriteRule ^index\.html$ - [L]
 RewriteCond %{REQUEST_FILENAME} !-f
 RewriteCond %{REQUEST_FILENAME} !-d
 RewriteRule . index.html [L]
</IfModule>
`

**Comment by chriskapp** [comment]
Thanks for the Info, in the latest release we have introduced the
marketplace for Apps https://www.fusio-project.org/marketplace which allows
you to install all Apps at the Backend therefor we have removed all Apps at
the Public folder except for the Backend app, but I will take a look at the
htaccess file.

soundpress <notifications@github.com> schrieb am Fr., 4. Okt. 2019, 16:39:

**Comment by soundpress** [comment]
Thank you too for the great system!

**Comment by chriskapp** [comment]
Regarding the `.htaccess` file, could it be that you are using an older Apache version which does not support the `FallbackResource` config https://httpd.apache.org/docs/trunk/mod/mod_dir.html#fallbackresource

The version which you have posted above is basically the older way to redirect all requests to a specific file. I think for now I will not change the htaccess file but if there are more problems from other users we could also easily use the older syntax.

**Comment by soundpress** [comment]
Great, thanks

**Comment by chriskapp** [comment]
I will close this issue since it looks like everything is solved here.
