### ISSUE TITLE
WASM support

### ISSUE THREAD

**Issue by chriskapp** [apioo/fusio#267]
Currently we have the PHP Sandbox to write actions in PHP. If we want to support other languages it would be great if we could support WASM. This means we have an action where a user can upload a wasm file and this wasm file gets executed if the action is called. We should take a look at the PHP wasm extension: https://github.com/wasmerio/php-ext-wasm

Through this we could use all languages which support wasm:
https://github.com/appcypher/awesome-wasm-langs

There are of course some challenges, the code inside the wasm file must have the ability to use the connections which are provided by Fusio, means to i.e. query the database make http calls etc. Therefor we need to make the connection API available inside wasm.

Also since it requires a special PHP extension we need to provide those actions as separate adapter. Inside the docker container we could maybe install it by default.

This relates also to #215 so it could be an alternative which would be much easier to maintain since we dont need to maintain multiple different worker libraries.

**Comment by billyhiuwali** [comment]
it would be great news. i look forward to use C# in Fusio.

**Comment by chriskapp** [comment]
So with the latest release we have implemented a worker system s. https://www.fusio-project.org/documentation/worker which allows us to support different languages. @billyhiuwali currently we have developed a Java, Javascript, PHP and Python worker but we are also planing to support other languages like C#
