### ISSUE TITLE
Expired token sends wrong http status code 500

### ISSUE THREAD

**Issue by EvoPulseGaming** [apioo/fusio#268]
When my application attempts to use the rest service with an expired token, the reply from fusio is http status 500(internal server error), when it should be 401 (unauthorized)

Edit, not that it should make a difference, but I do have development enabled instead of production

**Comment by chriskapp** [comment]
Hi, is there a specific router where this occurs, in general Fusio should return a `401` in case your endpoint requires authorization and you have not provided an `Authorization` header see:
https://github.com/apioo/fusio-impl/blob/master/src/Service/Security/TokenValidator.php#L116

**Comment by EvoPulseGaming** [comment]
The reply from the server for an EXPIRED token is 500:
https://evotracker.evo-pulse.com/isloggedin


{
  "success": false,
  "title": "Firebase\\JWT\\ExpiredException",
  "message": "Expired token in \/home\/evopulse\/public_html\/evotracker\/vendor\/firebase\/php-jwt\/src\/JWT.php on line 134",
  "trace": "#0 \/home\/evopulse\/public_html\/evotracker\/vendor\/fusio\/impl\/src\/Service\/Security\/TokenValidator.php(149): Firebase\\JWT\\JWT::decode('eyJ0eXAiOiJKV1Q...', '3312d99f0c3d91a...', Array)\n#1 \/home\/evopulse\/public_html\/evotracker\/vendor\/fusio\/impl\/src\/Service\/Security\/TokenValidator.php(103): Fusio\\Impl\\Service\\Security\\TokenValidator->getToken('eyJ0eXAiOiJKV1Q...', 123, 'GET')\n#2 \/home\/evopulse\/public_html\/evotracker\/vendor\/fusio\/impl\/src\/Filter\/Authentication.php(62): Fusio\\Impl\\Service\\Security\\TokenValidator->assertAuthorization('GET', 'Bearer eyJ0eXAi...', Object(Fusio\\Impl\\Loader\\Context))\n#3 \/home\/evopulse\/public_html\/evotracker\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): Fusio\\Impl\\Filter\\Authentication->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#4 \/home\/evopulse\/public_html\/evotracker\/vendor\/fusio\/impl\/src\/Filter\/AssertMethod.php(95): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#5 \/home\/evopulse\/public_html\/evotracker\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): Fusio\\Impl\\Filter\\AssertMethod->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#6 \/home\/evopulse\/public_html\/evotracker\/vendor\/psx\/http\/src\/Filter\/UserAgentEnforcer.php(43): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#7 \/home\/evopulse\/public_html\/evotracker\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): PSX\\Http\\Filter\\UserAgentEnforcer->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#8 \/home\/evopulse\/public_html\/evotracker\/vendor\/psx\/framework\/src\/Loader\/Loader.php(123): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#9 \/home\/evopulse\/public_html\/evotracker\/vendor\/psx\/framework\/src\/Loader\/Loader.php(102): PSX\\Framework\\Loader\\Loader->execute(Array, Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#10 \/home\/evopulse\/public_html\/evotracker\/vendor\/psx\/framework\/src\/Dispatch\/Dispatch.php(125): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(Fusio\\Impl\\Loader\\Context))\n#11 \/home\/evopulse\/public_html\/evotracker\/vendor\/psx\/framework\/src\/Environment\/WebServer\/Engine.php(47): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#12 \/home\/evopulse\/public_html\/evotracker\/vendor\/psx\/framework\/src\/Environment\/Environment.php(67): PSX\\Framework\\Environment\\WebServer\\Engine->serve(Object(PSX\\Framework\\Dispatch\\Dispatch), Object(PSX\\Framework\\Config\\Config))\n#13 \/home\/evopulse\/public_html\/evotracker\/public\/index.php(29): PSX\\Framework\\Environment\\Environment->serve()\n#14 {main}",
  "context": "130         }\n131 \n132         \/\/ Check if this token has expired.\n133         if (isset($payload-&gt;exp) &amp;&amp; ($timestamp - static::$leeway) &gt;= $payload-&gt;exp) {\n<b>134             throw new ExpiredException('Expired token');\n<\/b>135         }\n136 \n137         return $payload;\n138     }\n"
}

**Comment by chriskapp** [comment]
ok, I see this is a valid point, we should add a try catch around the JWT decode to return the fitting status code.

**Comment by chriskapp** [comment]
I have just commited a fix for this issue s.: https://github.com/apioo/fusio-impl/commit/a0be8847c02a504cd1d072b7538c4182c7e5d1d1
This fix is then included in the next release.

**Comment by EvoPulseGaming** [comment]
Thank you, glad it was an easy one for once! Have a great day
