### ISSUE TITLE
Incomplete description of Oauth2 authentication

### ISSUE THREAD

**Issue by soundpress** [apioo/fusio#269]
I was not able to pass Oauth2 authentication using all 4 available docs:

https://demo.fusio-project.org/developer/documentation/authorization
https://demo.fusio-project.org/documentation/#!/page/getting-started
https://fusio.readthedocs.io/en/latest/concept/authorization.html#oauth2
https://tools.ietf.org/html/rfc6749#section-4

After playing with parameters I succeeded and draw short instruction. Resulted doc may be worth to be included into above descriptions. Please find it here - https://api.miami211.openreferral.org/developer/documentation/authorization

**Comment by chriskapp** [comment]
Hi, thanks for the feedback. The docs are great, I will include them as you suggested at the authorization page. This should help also beginners to easily get started with the OAuth2 flow.

**Comment by chriskapp** [comment]
We have just updated the apps on the marketplace so the new documentation is now included.
