### ISSUE TITLE
Multiple parameters in the php sandbox testing area (right hand side)

### ISSUE THREAD

**Issue by EvoPulseGaming** [apioo/fusio#273]
I'm using the backend, in the php sandbox, in the parameter section:

Attempting to input multiple parameters during testing ends up with the first parameter having all the parameters added to it like its a long string. 

Example:
In:
id=10 version=1
Out:
id=10 version=1
version=null

Example 
In:
id=10,version=1
Out:
id=10,version=10
version=null

Is there a delimiter that can be used in the backend of the php sandbox?

**Comment by EvoPulseGaming** [comment]
Nevermind, I found that you can use "&" to join params

In:
id=10&version=1
Out:
id=10
version=1

Maybe put an example on the backend? (I realize this is "common" knowledge for most people xD)

**Comment by chriskapp** [comment]
Hi, yes it basically uses the query string format to provide values. In the background it uses the `parse_str` function to decode the values. I will close this issue since it is solved.
