### ISSUE TITLE
Class PhpParser\Parser\Php7 not found in.....

### ISSUE THREAD

**Issue by EvoPulseGaming** [apioo/fusio#274]
So this happens randomly, where I can no longer use the sandbox. There is no rhyme or reason for when it does this. This most recent time, I believe was a month.

One way I've found to fix this is to delete the nikic folder, and then re-run composer update.

I will reference this issue I've commented on, hopefully it gets properly resolved: https://github.com/nikic/PHP-Parser/issues/291

**Comment by chriskapp** [comment]
I will close this issue since it is duplicate to #275
