### ISSUE TITLE
Can't create new user

### ISSUE THREAD

**Issue by ratsey** [apioo/fusio#278]
This has been working - I added a new user a few weeks ago. This morning I tried to add a new user and get an error

`/scopes/0 must be of type string in /home/ratsey5/fusio/vendor/psx/schema/src/SchemaTraverser.php on line 439`

**Comment by chriskapp** [comment]
Hi, could you show me the request payload from the browser, it looks like the scopes array contains a non string value.

**Comment by ratsey** [comment]
This is the request - not sure how a null is getting in there. All I did is choose one of the scopes in my list of available scopes.

`{"status":0,"name":"susan","email":"example@gmail.com","scopes":[null,"oms"],"password":"shhhsecret"}`

<a href="https://ibb.co/yqRTkV2"><img src="https://i.ibb.co/nj021Rp/Annotation-2019-12-14-200635.png" alt="Annotation-2019-12-14-200635" border="0"></a>

**Comment by EvoPulseGaming** [comment]
Open the Fusio data base, and look at the scopes table, look at oms and see if it appears corrupted

**Comment by EvoPulseGaming** [comment]
How did you add this scope? Via the Fusio gui or with a REST call?

**Comment by ratsey** [comment]
I checked the DB - the `fusio_scope` table is clean, nothing unexpected in there. preorder and oms were both added using the Fusio GUI.

**Comment by chriskapp** [comment]
ok, so if you uncheck all checkboxes at the UI is the `null` value still there? It sounds like a problem at the frontend but I could not reproduce the problem yet.

**Comment by ratsey** [comment]
Yes! Checking and then checking all scope boxes worked.

**Comment by chriskapp** [comment]
ok, great that it worked, But Iam curious why there are still these empty scopes. I would guess these are scopes which you have assigned to the app and which were removed later on?

**Comment by ratsey** [comment]
All I did was add the two new scopes 'oms' and 'preorder' to the existing set. I have setup an app now, but that was only to try using OAUTH2 after this was failing. Not an issue for me now, but I can see how it might be frustrating to you! I'll wait for the new version with the refreshable simple token and see if it still happens.

**Comment by kidino** [comment]
I get this too somtimes. And just so that I could create the user, I would copy the JSON and the token, fix the JSON, and send it using a REST client. I use Insomnia.

**Comment by chriskapp** [comment]
@ratsey ok, it sounds indeed like a frontend issue. I could not yet reproduce the issue. @kidino does this occur randomly to you or is there a system to reproduce the problem on a fresh Fusio installation?

**Comment by EvoPulseGaming** [comment]
So i just ran into this issue myself...

You have to select the first scope, plus any others you want, THEN edit the user, and remove the first scope

**Comment by chriskapp** [comment]
ok, so I have just found and fixed the issue see https://github.com/apioo/fusio-backend/commit/ff98e459005f248552bba3092e0d51be95eac42d
This fix is then included in the next release, also I have added a select all checkbox to the scopes list.
