### ISSUE TITLE
add example for multiple URI Fragments or Parameters 

### ISSUE THREAD

**Issue by EvoPulseGaming** [apioo/fusio#279]
Right now in the php sandbox, your examples only provide for one input:
Optional the available uri fragments i.e. news_id=10
Optional the available parameters i.e. count=10

I remember I once figured this out, but since forgot... This is very time consuming...

I've tried "," and ";" as delimiters, but doesn't work

**Comment by EvoPulseGaming** [comment]
ah, the delimiter is the "&" symbol! So:

Optional the available uri fragments i.e. news_id=10&count=10
Optional the available parameters i.e. count=10&completed=true

**Comment by chriskapp** [comment]
Hi, yes this is correct the delimiter parameter is `&`, it basically is like an url query string. I have also just commited those examples which should help new users:
https://github.com/apioo/fusio-backend/commit/e6ff58e6673df5f80e5cb13d3bcd71f445113718
