### ISSUE TITLE
Webhook system

### ISSUE THREAD

**Issue by chriskapp** [apioo/fusio#28]
In the future we may want to add a webhook system where a user can configure webhooks for specific events of the system i.e.: a route was deployed or app was registered. This could help users to add functionalities to Fusio which are not supported by default. I.e. someone could create a webhook which sends an SMS to a specific person if a new app was registered. This is not possible by the Fusio system but could be implemented through webhooks.

**Comment by k42b3** [comment]
With the 0.9.2 release we have implemented the symfony event dispatcher which triggers events for specific actions. So we now simply need to write a fitting listener and a config panel.

**Comment by chriskapp** [comment]
This is already implemented
