### ISSUE TITLE
can Fusio receive file upload?

### ISSUE THREAD

**Issue by asutarko** [apioo/fusio#280]
Hi. can Fusio receive file from request? I find error as :
{
    "success": false,
    "title": "PSX\\Schema\\ValidationException",
    "message": "/gmb must be of type file in /home/www/andre/yoyic/vendor/psx/schema/src/SchemaTraverser.php on line 477",
    "trace": "#0 /home/www/andre/yoyic/vendor/psx/schema/src/SchemaTraverser.php(101): PSX\\Schema\\SchemaTraverser->assertTypeConstraints(Object(stdClass), Object(PSX\\Schema\\PropertyType))\n#1 /home/www/andre/yoyic/vendor/psx/schema/src/SchemaTraverser.php(240): PSX\\Schema\\SchemaTraverser->recTraverse(Object(stdClass), Object(PSX\\Schema\\PropertyType), Object(PSX\\Schema\\Visitor\\TypeVisitor))\n#2 /home/www/andre/yoyic/vendor/psx/schema/src/SchemaTraverser.php(140): PSX\\Schema\\SchemaTraverser->traverseObject(Array, Object(PSX\\Schema\\PropertyType), Object(PSX\\Schema\\Visitor\\TypeVisitor))\n#3 /home/www/andre/yoyic/vendor/psx/schema/src/SchemaTraverser.php(83): PSX\\Schema\\SchemaTraverser->recTraverse(Object(stdClass), Object(PSX\\Schema\\PropertyType), Object(PSX\\Schema\\Visitor\\TypeVisitor))\n#4 /home/www/andre/yoyic/vendor/psx/data/src/Processor.php(110): PSX\\Schema\\SchemaTraverser->traverse(Object(stdClass), Object(Fusio\\Impl\\Schema\\LazySchema), Object(PSX\\Schema\\Visitor\\TypeVisitor))\n#5 /home/www/andre/yoyic/vendor/psx/framework/src/Http/RequestReader.php(80): PSX\\Data\\Processor->read(Object(Fusio\\Impl\\Schema\\LazySchema), Object(PSX\\Data\\Payload), Object(PSX\\Schema\\Visitor\\TypeVisitor))\n#6 /home/www/andre/yoyic/vendor/fusio/impl/src/Controller/SchemaApiController.php(222): PSX\\Framework\\Http\\RequestReader->getBodyAs(Object(PSX\\Http\\Request), Object(Fusio\\Impl\\Schema\\LazySchema), NULL)\n#7 /home/www/andre/yoyic/vendor/psx/framework/src/Controller/SchemaApiAbstract.php(136): Fusio\\Impl\\Controller\\SchemaApiController->parseRequest(Object(PSX\\Http\\Request), Object(PSX\\Api\\Resource\\Post))\n#8 /home/www/andre/yoyic/vendor/psx/framework/src/Controller/ControllerAbstract.php(172): PSX\\Framework\\Controller\\SchemaApiAbstract->onPost(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#9 /home/www/andre/yoyic/vendor/psx/framework/src/Controller/SchemaApiAbstract.php(99): PSX\\Framework\\Controller\\ControllerAbstract->onRequest(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#10 /home/www/andre/yoyic/vendor/psx/framework/src/Controller/ControllerAbstract.php(138): PSX\\Framework\\Controller\\SchemaApiAbstract->onRequest(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#11 /home/www/andre/yoyic/vendor/psx/http/src/Filter/FilterChain.php(110): PSX\\Framework\\Controller\\ControllerAbstract->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#12 /home/www/andre/yoyic/vendor/fusio/impl/src/Filter/Logger.php(68): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#13 /home/www/andre/yoyic/vendor/psx/http/src/Filter/FilterChain.php(110): Fusio\\Impl\\Filter\\Logger->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#14 /home/www/andre/yoyic/vendor/fusio/impl/src/Filter/RequestLimit.php(75): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#15 /home/www/andre/yoyic/vendor/psx/http/src/Filter/FilterChain.php(110): Fusio\\Impl\\Filter\\RequestLimit->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#16 /home/www/andre/yoyic/vendor/fusio/impl/src/Filter/Authentication.php(66): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#17 /home/www/andre/yoyic/vendor/psx/http/src/Filter/FilterChain.php(110): Fusio\\Impl\\Filter\\Authentication->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#18 /home/www/andre/yoyic/vendor/fusio/impl/src/Filter/AssertMethod.php(95): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#19 /home/www/andre/yoyic/vendor/psx/http/src/Filter/FilterChain.php(110): Fusio\\Impl\\Filter\\AssertMethod->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#20 /home/www/andre/yoyic/vendor/psx/http/src/Filter/UserAgentEnforcer.php(43): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#21 /home/www/andre/yoyic/vendor/psx/http/src/Filter/FilterChain.php(110): PSX\\Http\\Filter\\UserAgentEnforcer->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#22 /home/www/andre/yoyic/vendor/psx/framework/src/Loader/Loader.php(123): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#23 /home/www/andre/yoyic/vendor/psx/framework/src/Loader/Loader.php(102): PSX\\Framework\\Loader\\Loader->execute(Array, Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#24 /home/www/andre/yoyic/vendor/psx/framework/src/Dispatch/Dispatch.php(125): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(Fusio\\Impl\\Loader\\Context))\n#25 /home/www/andre/yoyic/vendor/psx/framework/src/Environment/WebServer/Engine.php(47): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#26 /home/www/andre/yoyic/vendor/psx/framework/src/Environment/Environment.php(67): PSX\\Framework\\Environment\\WebServer\\Engine->serve(Object(PSX\\Framework\\Dispatch\\Dispatch), Object(PSX\\Framework\\Config\\Config))\n#27 /home/www/andre/yoyic/public/index.php(29): PSX\\Framework\\Environment\\Environment->serve()\n#28 {main}",
    "context": "473         $type = $property-&gt;getType();\n474         if ($type !== null) {\n475             if (is_string($type)) {\n476                 if (!$this-&gt;isOfType($type, $data)) {\n<b>477                     throw new ValidationException($this-&gt;getCurrentPath() . ' must be of type ' . $type, 'type', $this-&gt;pathStack);\n</b>478                 }\n479             } elseif (is_array($type)) {\n480                 $found = false;\n481                 foreach ($type as $typ) {\n"
}

**Comment by ratsey** [comment]
I'm using Fusio to accept PDFs without issue. This is my API action:

```
<?php

namespace App\OMS\Order\Document;

use Fusio\Engine\ActionAbstract;
use Fusio\Engine\ContextInterface;
use Fusio\Engine\ParametersInterface;
use Fusio\Engine\RequestInterface;
use PSX\Http\Exception as StatusCode;

class Insert extends ActionAbstract
{
    public function handle(RequestInterface $request, ParametersInterface $configuration, ContextInterface $context)
    {
        /** @var \Doctrine\DBAL\Connection $connection */
        $connection = $this->connector->getConnection('oms');

        $order_id = $request->getUriFragment('order_id');
        $filename = basename($_FILES["file"]["name"]);
        $path = "../../serverpathhere/documents/";

        $originalName = $_FILES['file']['name'];
        $ext = '.' . pathinfo($originalName, PATHINFO_EXTENSION);
        $generatedName = md5($_FILES['file']['tmp_name']) . $ext;
        $filePath = $path . $generatedName;

        // Create an entry in the document table to get a file reference Id
        $connection->insert('document', [
            'filename' => $generatedName,
            'order_id' => $order_id
        ]);

        // Obtain the newly inserted Id
        $newFileName = $connection->lastInsertId();

        // Save the file with the new name
        move_uploaded_file($_FILES["file"]["tmp_name"], $filePath);  


        return $this->response->build(201, [], [
            'success' => true,
            'message' => 'Insert successful',
        ]);
    }
}
```

**Comment by chriskapp** [comment]
Hi, yes like @ratsey has written you can always use the native PHP upload functions. If you post data via `multipart/form-data` to Fusio the `$request->getBody()` method should also contain the information of the `$_FILES` array so that you dont need to use the global `$_FILES` array but in the end both works. You also need to set the schema to Passthru since you cant validate such file uploads through json schema.
