### ISSUE TITLE
Fusions has multi tenancy feature? 

### ISSUE THREAD

**Issue by jothikannan** [apioo/fusio#283]
Do Fusio has feature to share same Api with multiple users without conflicting each other records? Which means If an User A has access to App 1, and User B who has the access to same App 1, can we store and retrieve the records separately from the request by both the User A and User B?

**Comment by chriskapp** [comment]
Hi, yes so if you build your app you can use the `userId` and `appId` from the [context](https://www.fusio-project.org/documentation/php/$context) and store them in your table. Based on these information you can create the fitting queries to return only the records for the specific user and app combination.

**Comment by jothikannan** [comment]
thank you @chriskapp , it makes sense. I have assumed a flow to achieve this, I am attaching it here, could you please confirm it? correct me if I am wrong

1. Create API
2. Create Routes
3. Create Scopes to routes- Group all the needed routes into a scope
4. Create an app with the selected scopes 
5. Assign the app to a user(consumer)
6. The developer can log in into the developer portal to see the List of assigned apps and can get the App Key and App Secret key to be used in the REST API implementation.

**Comment by chriskapp** [comment]
Yes the flow makes sense, but with step 4 to 6 you basically create an app for the user. The original idea was that we assign allowed scopes to the user and the user can then create an app at the developer portal by himself. Similar to i.e. Github or Facebook where the user also can create apps for his use case.

**Comment by jothikannan** [comment]
> The original idea was that we assign allowed scopes to the user and the user can then create an app at the developer portal by himself.

Could you please elaborate on this? how we can assign the scopes to the users? I can't see any options to assign scopes to the users. instead, I can see create an app to the user with the allowed scopes.

**Comment by chriskapp** [comment]
sure, so if you create a new user you can also define the scopes which are allowed for this user.
