### ISSUE TITLE
phpunit not working

### ISSUE THREAD

**Issue by jothikannan** [apioo/fusio#284]
Hi,

When I try to run phpunit command I am getting the following message:

```
Time: 1.43 seconds, Memory: 8.00MB

No tests executed!
```

Composer.json code

```
"autoload": {
    "psr-4": {
      "App\\": "src/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "App\\Tests\\": "tests/"
    }
  }
```

Could anyone help me to run phpunit for the inbuilt Todo app, so I can extend it to my app.

**Comment by chriskapp** [comment]
Hi, so maybe phpunit can not find the `phpunit.xml` which defines where to find the tests and the bootstrap file see https://github.com/apioo/fusio/blob/master/phpunit.xml

**Comment by jothikannan** [comment]
Hi,
I am already having Phpunit.xml in my root directory.

**Comment by chriskapp** [comment]
Ok, you can also take a look at our travis setup https://travis-ci.org/apioo/fusio/jobs/635052563 which executes theses tests on every commit, so Iam currently not sure why the tests are not executed in your case.

**Comment by jothikannan** [comment]
I found the issue, my xamp has already installed with old phpunit version, so I have uninstalled and installed the compose version of phpunit, and now the test is running, but the command I need to run the test is `vendor\bin\phpunit`
