### ISSUE TITLE
phpunit throws error for my api endpoints

### ISSUE THREAD

**Issue by jothikannan** [apioo/fusio#287]
```
PHPUnit 6.0.0 by Sebastian Bergmann and contributors.

FF                                                                  2 / 2 (100%)

Time: 923 ms, Memory: 12.00MB

There were 2 failures:

1) App\Tests\Api\Events\CollectionTest::testGet
{
    "success": false,
    "title": "Internal Server Error",
    "message": "Unknown location"
}
Failed asserting that 404 matches expected 200.

G:\xampp\htdocs\projects\fusio\tests\Api\Events\CollectionTest.php:48

2) App\Tests\Api\Events\EntityTest::testGet
{
    "success": false,
    "title": "Internal Server Error",
    "message": "Unknown location"
}
Failed asserting that 404 matches expected 200.

G:\xampp\htdocs\projects\fusio\tests\Api\Events\EntityTest.php:54

FAILURES!
Tests: 2, Assertions: 2, Failures: 2.
```
I am getting above error when I try to run PHPUnit,  But when I configure the phpunit.xml for the given todo app no error all the cases are passed, could anyone help me to figure out the issue?

CollectionTest.php
```
class CollectionTest extends ApiTestCase
{
	    public function testGet()
    {
        $response = $this->sendRequest('/events', 'GET', [
            'User-Agent'    => 'Fusio TestCase',
        ]);

        $actual = (string) $response->getBody();
        $actual = preg_replace('/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/', '0000-00-00 00:00:00', $actual);
        $expect = <<<'JSON'
{
  "totalResults": 2,
  "entry": [
    {
      "id": "01a5404e-97b1-4a16-a77a-3b83b88930f3",
      "title": "sdsd",
      "body": "dsds",
      "field_event_start": "2020-01-09T08:54:57+00:00",
      "field_event_end": "2020-01-09T08:54:57+00:00"
    },
    {
      "id": "680f156d-1496-4e19-b5a8-d9ede96e0971",
      "title": "sdsdsdsd",
      "body": "dsdsdsd",
      "field_event_start": "2020-01-09T11:41:28+00:00",
      "field_event_end": "2020-01-09T11:41:28+00:00"
    }
  ]

}
JSON;

        $this->assertEquals(200, $response->getStatusCode(), $actual);
        $this->assertJsonStringEqualsJsonString($expect, $actual, $actual);
    }

}
```
EntityTest.php
```
class EntityTest extends ApiTestCase
{
     public function testGet()
    {
        $response = $this->sendRequest('/events/01a5404e-97b1-4a16-a77a-3b83b88930f3', 'GET', [
            'User-Agent'    => 'Fusio TestCase',
        ]);

        $actual = (string) $response->getBody();
        //$actual = preg_replace('/\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}/', '0000-00-00 00:00:00', $actual);
        $expect = <<<'JSON'
{
      "id": "01a5404e-97b1-4a16-a77a-3b83b88930f3",
      "title": "sdsd",
      "body": "dsds",
      "field_event_start": "2020-01-09T08:54:57+00:00",
      "field_event_end": "2020-01-09T08:54:57+00:00"
}
JSON;

        $this->assertEquals(200, $response->getStatusCode(), $actual);
        //$this->assertJsonStringEqualsJsonString($expect, $actual, $actual);
    }
  
}

```
I am using `Http` connection with authentication for my endpoints. On bootstrtap.php I have changed the connection id to 6 which is my connection

 `$connection->update('fusio_connection', ['class' => \Fusio\Impl\Connection\Native::class], ['id' => 6]);`

**Comment by chriskapp** [comment]
Hi, do you have configured your routes at the `resources/routes.yaml` file, it looks like the system can simply not find the declared routes?

**Comment by jothikannan** [comment]
@chriskapp thank you so much for the prompt response.

No, I haven't configured my routes at `resources/routes.yaml`. I was trying to add my routes but I was getting some error when I do deploy command. is there a command to generate routes.YAML ? and schema.json for my routes? or should I do this manually?

**Comment by jothikannan** [comment]
Hello @chriskapp 

I have configured resources/routes.yaml for my events endpoints, after that when I try to run deploy I am getting the following error:

```
Deploy contained 2 errors!

- /events: Route was deleted
- /events/:event_id: Route was deleted
```

**Comment by jothikannan** [comment]
Hello @chriskapp 

It would be helpful if you give documentation for how to configure resources/routes.yaml ? After configuring schema for my endpoints I am getting different errors. Please help me. I am fed up with this issue

```
There were 2 failures:

1) App\Tests\Api\Events\CollectionTest::testGet
{
    "success": false,
    "title": "Internal Server Error",
    "message": "The server encountered an internal error and was unable to complete your request."
}
Failed asserting that 500 matches expected 200.

G:\xampp\htdocs\projects\fusio\tests\Api\Events\CollectionTest.php:47

2) App\Tests\Api\Events\EntityTest::testGet
{
    "success": false,
    "title": "Internal Server Error",
    "message": "The server encountered an internal error and was unable to complete your request."
}
Failed asserting that 500 matches expected 200.

G:\xampp\htdocs\projects\fusio\tests\Api\Events\EntityTest.php:54

FAILURES!
Tests: 2, Assertions: 2, Failures: 2.
```

**Comment by jothikannan** [comment]
![testing](https://user-images.githubusercontent.com/4100047/72727049-f2f9e380-3baf-11ea-80d8-51ae2579fb43.png)

Please refer the attached image for more details,

**Comment by chriskapp** [comment]
Hi @jothikannan, it looks like you have routes in your Fusio instance which are deleted because of this you cant create them through the deploy. You could change the status of your routes database to active, then you should be able to run the deploy command.

**Comment by jothikannan** [comment]
Thank you so much, now I can run the deploy without any issues. But still I am getting issue while running the phpunit command, I am getting the following error


```
There were 2 failures:

1) App\Tests\Api\Events\CollectionTest::testGet
{
    "success": false,
    "title": "Internal Server Error",
    "message": "The server encountered an internal error and was unable to complete your request."
}
Failed asserting that 500 matches expected 200.

G:\xampp\htdocs\projects\fusio\tests\Api\Events\CollectionTest.php:47

2) App\Tests\Api\Events\EntityTest::testGet
{
    "success": false,
    "title": "Internal Server Error",
    "message": "The server encountered an internal error and was unable to complete your request."
}
Failed asserting that 500 matches expected 200.

G:\xampp\htdocs\projects\fusio\tests\Api\Events\EntityTest.php:54

FAILURES!
Tests: 2, Assertions: 2, Failures: 2.
```
So I believe there is no issue with the routes now, do we need to change any configuration or anything in bootstrap.php? Please could you please list out what are the things we need to do for this phpunit to be work.

**Comment by jothikannan** [comment]
@chriskapp What are the necessary steps we have to run the phpunit? I am I missing anything? Please help me, I am unable to move further and stuck with PHPUnit

**Comment by chriskapp** [comment]
Ok, so in your test case your API endpoint returns a 500. In the file `tests/ApiTestCase.php:49` you could set the debug mode to true which then should return the real exception. Then we can further debug whether the problem is inside your action or elsewhere.

**Comment by jothikannan** [comment]
thanks, I have enabled the debug true, now I can see an exception. 

```
"success": false,
"title": "Fusio\\Engine\\Exception\\ConnectionNotFoundException",
"message": "Could not found connection Waisli"
```
But I have this connection in my connections list, also my actions are working fine when I execute from Actions, Swagger-UI, Documentation. Do we need to define this connection somewhere else for PHPUnit?

**Comment by jothikannan** [comment]
Finally, I got figured out the issue.
We have to define the `connection: !include resources/connections.yaml` in `tests/.fusio.yml` after that there are no more issues and I can get the results for my test cases.

**Comment by chriskapp** [comment]
ok great
