### ISSUE TITLE
Assigned Scope is not visible in developer portal

### ISSUE THREAD

**Issue by jothikannan** [apioo/fusio#289]
I have created a user with a Scope assigned. When the user logged in to the developer portal and trying to create an App given scope is not visible near the checkbox. I Beleive this might be a bug, please refer the attached image for your reference

![createapp](https://user-images.githubusercontent.com/4100047/72963333-050c9980-3ddd-11ea-847b-1300092734ab.png)

**Comment by chriskapp** [comment]
Hi, mhh it looks like you have a scope without description, if you enter a description to a scope this should be shown there.

**Comment by jothikannan** [comment]
Yes, that was the issue, Please make the description as a mandatory field so that no one can miss it.
