### ISSUE TITLE
Error executing an action with Mysql

### ISSUE THREAD

**Issue by ronnyvillamar99** [apioo/fusio#292]
I found an error when executing a query in mysql using the 'all rows' mode, when querying it threw an error, it was a syntax error.
I solved it by adding 'as _query' at the end of the query in '/vendor/fusio/adapter-sql/src/Action/SqlTable.php'
this:
` $totalResults = (int) $connection->fetchColumn('SELECT COUNT(*) AS cnt FROM (' . $query . ')', $params);`
for this:
` $totalResults = (int) $connection->fetchColumn('SELECT COUNT(*) AS cnt FROM (' . $query . ') AS _query', $params);`

in case you throw the same mistake.

haha it worked for me but I don't know if I'll have problems after this.

**Comment by chriskapp** [comment]
Hi, yes this is the correct fix. We have also already fixed this at the action see: https://github.com/apioo/fusio-adapter-sql/blob/master/src/Action/SqlSelect.php#L70
This fix is then included in the next release.

**Comment by chriskapp** [comment]
So this is now fixed at the latest release.
