### ISSUE TITLE
Invalid hash of downloaded app

### ISSUE THREAD

**Issue by jothikannan** [apioo/fusio#293]
When I try to install the Market place apps, I am getting error like 

`Invalid hash of downloaded app in H:\laragon\www\api\vendor\fusio\impl\src\Service\Marketplace\Installer.php on line 158`

May I know the reason for this error?

Note: this happens only on installing developer (0.2) and documentation (0.2) only, other apps are installing successfully.

**Comment by chriskapp** [comment]
Hi, so the reasons for this is that the hash of the zip file does not match to the [marketplace.yaml](https://github.com/apioo/fusio/blob/master/marketplace.yaml) file. I have just updated the hashes so please try to install this app again it should now work as expected.

**Comment by chriskapp** [comment]
For your information to prevent this in the future we have added an integration test for Fusio which periodically checks whether all hashes are up-to-date and which also checks the upgrade path of legacy Fusio versions s. https://travis-ci.org/apioo/fusio-integration
