### ISSUE TITLE
fresh install, install.php not working (manual install cant login)

### ISSUE THREAD

**Issue by magseras** [apioo/fusio#307]
hi,
my name harri, i just installed this application and cant login to http://<IP>/public/fusio.
i am using centos 7 and also try at ubuntu. but when i try to access http://<IP>/public/install.php my browser said HTTP ERROR 500. 
i try to installed using "php bin/fusio install" and also success to add user using ""php bin/fusio adduser" but when i login it said wrong username password.
i try to used PHP 7.1 and 7.4 centos and Ubuntu but the output still same. can you help me about this?

thanks

**Comment by chriskapp** [comment]
Hi, ok could you take a look at the error log of the web server to see whether it contains an error message. It could be a problem regarding the permissions of the `cache/` folder, since Fusio needs write access to this folder.

**Comment by magseras** [comment]
i found the solusion,
**disabled selinux** on my centos. not sure about ubuntu since i am not really familiar with ubuntu.
