### ISSUE TITLE
I can't edit or delete anything

### ISSUE THREAD

**Issue by ronnyvillamar99** [apioo/fusio#309]
I have a problem, I can add routes, actions, but I cannot delete them, nor edit them, also for the same with the marketplace extensions, they can only be installed, not deleted from fusion,
can you help me, why is this?

**Comment by chriskapp** [comment]
Hi, this looks like your webserver does not allow PUT and DELETE requests. Which webserver do yo use?

**Comment by ronnyvillamar99** [comment]
my PHP Version 7.2.29

**Comment by ronnyvillamar99** [comment]
my web server does not have ssl, I don't know if that has something to do
Here are some additional specifications:

nginx/1.16.1
Version of client : libmysql - mysqlnd 5.0.12-dev 
PHP extension: mysqliDocumentación curlDocumentación mbstringDocumentación
PHP version: 7.3.13

phpMyAdmin 4.9.0.1

Server: xxxxxx.com via TCP / IP
Server type: MySQL
Server connection: SSL is not being used Documentation
Server version: 5.7.29 - MySQL Community Server (GPL)
Protocol version: 10
User: fusiouser@xxxxxx
Server character set: cp1252 West European (latin1)


It is located in the subdirectory of my web
something like that
www.xxxxx.server.com/api/public/fusio
www.xxxxx.server.com/api/public / ....

try to fix it by editing .htaccess but it doesn't fix
my .htacces of  root directory www.xxxxx.server.com/api/

`RewriteEngine on
RewriteCond %{REQUEST_URI} !public/
RewriteRule (.*) /public/$1 [L]

<IfModule mod_alias.c>
RedirectMatch 301 ^/$ http://xxxx.server.com/api/public/index.php
</IfModule>

<IfModule mod_rewrite.c>
RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /public/index.php [L]
</IfModule>
`

The .htaccess of the public directory has not been changed

**Comment by chriskapp** [comment]
Hi, so SSL is not a requirement, in general I would recommend to create a separate vhost entry with a fitting subdomain i.e. http://api.xxxx.server.com for your Fusio installation where the web root points to the public folder, you can see an example config at our documentation: https://fusio.readthedocs.io/en/latest/setup/apache.html
Then you dont need to create such a htaccess redirect.

**Comment by ronnyvillamar99** [comment]
Yes, of course, but the problem is that it is not a server of its own, I have a hosting and I manage the subdomains by directories, although I could create a subdomain only for fusion, so it would work without problems?

**Comment by chriskapp** [comment]
Yes, this should work without problems. In the past we had also other users who have used shared-hosting provider so you maybe want to take a look at: https://fusio.readthedocs.io/en/latest/setup/shared_hosting.html
Which shows a htaccess file to redirect such requests, so maybe this works also for your case.

**Comment by ronnyvillamar99** [comment]
I will try it and comment on any news so far I tried adding the commands to the root folder of fusio but it still doesn't work
the root folder would be www.xxx.server.com/api/
Right?

the directories in my hosting are organized like this
home_directory / server.com
home_directory / subdomain1.server.com
home_directory / subdomain2.server.com
and so...
the directory where the .htaccess would go would be
home_directory / subdomain1.server.com / 'here

or
home_directory / subdomain1.server.com / api / 'here

**Comment by chriskapp** [comment]
I think you should need to place it in the `home_directory/subdomain1.server.com/api/` folder, which then redirects the requests to `home_directory/subdomain1.server.com/api/public/`

**Comment by ronnyvillamar99** [comment]
It does not work, I still have the same problem, I can not edit anything or delete, they are only added, check the permissions on the mysql users and they are all there,
I removed and reinstalled everything, files and database and it remains the same,
the .htaccess works great for requests, I don't have to direct api / public / index.php / just / api /
but the problem persists, it doesn't even show me any error, it just doesn't work, it doesn't show any message at all,

I also tried to use the subdomain only for the api but it did not work, I do not understand why, on a local server everything works fine, only on this hosting that does not work,

**Comment by ronnyvillamar99** [comment]
I used my browser's java script debugger and this appears when trying to delete

`fusio.min.js:188 DELETE http://scs.syterox.com/api/public/index.php/backend/action/6 405 (Not Allowed)`

**Comment by ronnyvillamar99** [comment]
I used my browser's java script debugger and this appears when trying to delete

`DELETE http://xxx.server.com/api/public/index.php/backend/action/6 405 (Not Allowed)`

**Comment by chriskapp** [comment]
@ronnyvillamar99 ok, so with the next release we have added also a [.htaccess](https://github.com/apioo/fusio/blob/master/.htaccess) file at our root folder so that Fusio can be easily used in a sub directory. Regarding your problem, I think the problem is that the PUT and DELETE HTTP method are not allowed. You could change the env setting `FUSIO_ENV` to `dev` which returns then more debug information. Could you show me the HTTP response of the `DELETE` request which you have posted?

**Comment by ronnyvillamar99** [comment]
/api/public/index.php/backend/action/6:1 Failed to load resource: the server responded with a status of 405 (Not Allowed)
DevTools failed to load SourceMap: Could not load content for http://server.com/api/public/fusio/dist/bootstrap-theme.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE


http://server.com/api/public/index.php/backend/action/6 405 (Not Allowed)
(anonymous) @ fusio.min.js:188
sendReq @ fusio.min.js:187
serverRequest @ fusio.min.js:187
processQueue @ fusio.min.js:188
(anonymous) @ fusio.min.js:189
$digest @ fusio.min.js:189
$apply @ fusio.min.js:189
(anonymous) @ fusio.min.js:191
defaultHandlerWrapper @ fusio.min.js:185
eventHandler @ fusio.min.js:185

**Comment by chriskapp** [comment]
ok, the source map request is no problem but could you show me the complete HTTP response and not only the 405 status code, maybe the body contains some more information, you can see this in the network tab.

**Comment by ronnyvillamar99** [comment]
Ah ok,
this?
Request URL: http://server.com/api/public/index.php/backend/action/6
Request Method: DELETE
Status Code: 405 Not Allowed
Remote Address: 82.194.68.25:80
Referrer Policy: no-referrer-when-downgrade
Allow: GET, POST, HEAD
Connection: keep-alive
Content-Length: 552
Content-Type: text/html
Date: Sat, 02 May 2020 15:27:59 GMT
Server: nginx
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate
Accept-Language: es,es-419;q=0.9,es-MX;q=0.8
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC9zY3Muc3l0ZXJveC5jb21cL2FwaVwvcHVibGljIiwic3ViIjoiMzE2ZGYwNDItMWQzZC01ZmMyLWI0NDAtMDJlNWI1MDhlZjI4IiwiaWF0IjoxNTg4NDMzMjQ1LCJleHAiOjE1ODg0MzY4NDUsIm5hbWUiOiJzd3NtYXN0ZXIifQ.u9iRpYhtmLRRYKvyQo1j0Ur7ze-yX6wK6guR3dK8aXw
Connection: keep-alive
Cookie: wordpress_logged_in_29df1c2459ec8f00adc450d116e153d9=syterox_wzc7kctf%7C1587823508%7C6ocQPgJVK6NmPRzi7Yfd03ckZbdxaJI33xDBcsfJicG%7C53f52d982db75c8c322c242c9a5d0c39badd18d5f2de1506aaadb575d568424d
Host: scs.syterox.com
Origin: http://server.com
Referer: http://server.com/api/public/fusio/
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36 OPR/68.0.3618.63


help me, please

**Comment by ronnyvillamar99** [comment]
I was looking for something and I found this, I think this is the problem, my hosting uses an nginx server and it seems to show this error when using the directory index to make requests or something, I do not quite understand, but I think that you do
How could I solve it?
this is the link of the topic
https://stackoverflow.com/questions/30154875/right-way-to-enable-requests-with-method-delete-in-nginx

**Comment by chriskapp** [comment]
Ok, so the "Allow" header in your response indicates that only "GET, POST, HEAD"
are allowed. In your link there is a problem regarding webdav, but you should not need to use the DAV extension. Could you post your nginx config to debug this further.

**Comment by chriskapp** [comment]
So with the latest release we have also added a fitting .htaccess file so you can also use Fusio without a specific sub domain (at least if you use Apache as webserver)
