### ISSUE TITLE
JS app which handles authorization and app management

### ISSUE THREAD

**Issue by chriskapp** [apioo/fusio#31]
At the moment we have only the developer app where consumers of the API can register and manage their app keys/secrets. This app is designed as a developer portal. For SPAs we only need the login/register and app management part. We should build an app which handles only this and which can be easily integrated into any SPA.

**Comment by k42b3** [comment]
We have added a simple jquery based app which show cases the login flow. This jquery code is probably applicable to other js apps:
https://github.com/apioo/fusio-sample-jquery

**Comment by EvoPulseGaming** [comment]
Should this be closed now, as in 1.8.0 JS was removed?

**Comment by chriskapp** [comment]
Yes, so I will close this issue since we have already #245 which basically has a similar goal.
