### ISSUE TITLE
Unable to install marketplace apps and login

### ISSUE THREAD

**Issue by mzch** [apioo/fusio#312]
Version: 1.9.3

Unable to install marketplace apps by using web installer (install.php)
And after executing `bin/fusio install` and `bin/fusio user:add`, I can't login to backend app.
Fusio reported `Authentication failed`.

Any idea?

**Comment by chriskapp** [comment]
Hi, ok can you install an app from the marketplace through the command `php bin/fusio -d marketplace:install fusio` this should also install the backend app. We have also just fixed a wrong app alias on the new introduced marketplace. So please try again to run the installer.

**Comment by mzch** [comment]
@chriskapp I tried `php bin/fusio marketplace:install backend`, etc, but failed, so I downloaded .zip file and extracted it into `public` directory.
But I can't login yet.

**Comment by chriskapp** [comment]
ok, so the name of the backend app is "fusio" and not "backend" so the command would be `php bin/fusio -d marketplace:install fusio` the `-d` flag only disables SSL verification. If you manually download the zip you need to replace the `${API_URL}` variable at the `index.html` which is normally replaced by the marketplace installer.

**Comment by mzch** [comment]
I recreate database and reinstall Fusio again. In this time web installer works well.
But plugins haven't been installed. I tried `php bin/fusio -d marketplace:install fusio`, then printed `App already installed`. But Fusio doesn't show login form at `https://susvc.com/fusio/`, yes, it isn't installed.

**Comment by mzch** [comment]
I found them in `apps` directory. but can't login at `https://susvc.com/fusio/`.

<img width="1001" alt="ScreenShot" src="https://user-images.githubusercontent.com/621178/81612490-e2e46900-9417-11ea-90b5-a04bcb822047.png">

**Comment by chriskapp** [comment]
Ok, so all apps get installed at the `apps/` folder, in your screenshot it looks like the javascript and css could not be loaded of the app. If an app is installed through the marketplace the installer replaces also specific variables at the `index.html` file, if you simply copy the app you also need to replace those values.

**Comment by mzch** [comment]
I installed marketplace apps thru web installer.

**Comment by chriskapp** [comment]
Do you still have problems regarding an app which you have installed through the marketplace, otherwise I would close this issue?

**Comment by mzch** [comment]
Hi, I found I made a misconfiguration in Apache.
When I installed Fusio from scratch, I have did it successfully.
Thanks!
