### ISSUE TITLE
getBody response blank in postman

### ISSUE THREAD

**Issue by hamzakaya** [apioo/fusio#316]
why is this different response data
just postman like this 

![Screenshot from 2020-05-12 20-39-49](https://user-images.githubusercontent.com/3410203/81727144-2a5b0b80-9491-11ea-8b7e-6282c3d097a3.png)
![Screenshot from 2020-05-12 20-39-38](https://user-images.githubusercontent.com/3410203/81727165-32b34680-9491-11ea-8cb8-897c5ddc52ed.png)

**Comment by chriskapp** [comment]
Hi, ok maybe your route has not a fitting schema set i.e. `Passthru` to forward all incoming data to your action. You can also define a specific schema which describes the allowed input.

**Comment by hamzakaya** [comment]
I am experimenting with the default todo application, what do I need to do extra?

**Comment by chriskapp** [comment]
So in your route you could change the `/todo/:todo_id` you could change the request schema to `Passthru` which basically means that all data is passed to the action.

**Comment by chriskapp** [comment]
Ok, I think I have found your problem, if you use the `Passthru` Schema at your route you receive as body a `PassthruRecord` instance, on this you can call the `getPayload` method to get the complete payload.
