### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by Stanixia** [apioo/fusio#317]
Hello,

I did a docker installation with the documentation  https://fusio.readthedocs.io/en/latest/setup/docker.html but following the git clone and the docker-compose up -d the localhost returns me `{
    "message": "Congratulations the installation of Fusio was successful",
    "apiVersion": "v4.4.8@fc2aba51f856e47e36f9f1df1cc5e7e5de6191ca",
    "links": [
        {
            "rel": "about",
            "name": "http:\/\/fusio-project.org"
        }
    ]
}` but the localhost/fusio answers me `{
    "success": false,
    "title": "Internal Server Error",
    "message": "Unknown location"
}`

thank you,
good night

**Comment by chriskapp** [comment]
Hi, so if you visit `localhost` it should return the success message. The `/fusio` endpoints is basically a route which currently not exists at your server.

**Comment by Stanixia** [comment]
ok, sorry I configured a domain locally and I manage to join the backend with apps.acme.com but I cannot identify myself with the information of `FUSIO_BACKEND_USER` and `FUSIO_BACKEND_PW`

**Comment by jiarara** [comment]
I have the same question , is it a bug ?    it is "Internal Server Error"   where  visit localhost/fusio

**Comment by chriskapp** [comment]
So in general the `FUSIO_BACKEND_USER` and `FUSIO_BACKEND_PW` should work. Can you maybe check whether a javascript error occurred during the login?

**Comment by chriskapp** [comment]
Is this issue still relevant, otherwise I would close the issue?

**Comment by mzch** [comment]
I downloaded and unzpped fusio_1.9.4.zip, then configured `.env`
When I visits https://susvc.com/fusio/ (my instance), the same error is printed.

- .env
```sh
# Fusio
FUSIO_PROJECT_KEY="project_key"
FUSIO_URL="https://${FUSIO_HOST}"
FUSIO_HOST="susvc.com"
FUSIO_URL="https://${FUSIO_HOST}/public"
FUSIO_APPS_URL="https://apps.${FUSIO_HOST}"
FUSIO_ENV="prod" # dev or prod
FUSIO_DB_NAME="fusio"
FUSIO_DB_USER="fusio"
FUSIO_DB_PW="password"
FUSIO_DB_HOST="192.168.207.10"

# Config (resources/config.yaml)
# Login provider
PROVIDER_FACEBOOK_KEY=""
PROVIDER_FACEBOOK_SECRET=""
PROVIDER_GOOGLE_KEY=""
PROVIDER_GOOGLE_SECRET=""
PROVIDER_GITHUB_KEY=""
PROVIDER_GITHUB_SECRET=""

# Register captcha
RECAPTCHA_SECRET="6Lcqxxx"
RECAPTCHA_KEY="6Lcqxxx"
```

**Comment by chriskapp** [comment]
Ok, could you point the sub-domain `app.susvc.com` to the `apps/` folder. Then you should be able to visit the backend at `app.susvc.com/fusio`

**Comment by mzch** [comment]
Oh, I correct apache.conf, ServerAlias apps.susvc.com and tried to access to `https://apps.susvc.com/fusio`:

```json
{
  "success": false,
  "title": "Internal Server Error",
  "message": "Unknown location"
}
```

**Comment by chriskapp** [comment]
Mhh, this looks like the sub-domain does not point to the `apps/` folder inside Fusio since the response comes from the API. The `apps/` folder inside Fusio has a simple `index.php` which lists all installed apps s. https://github.com/apioo/fusio/tree/master/apps so visiting `https://apps.susvc.com` should give you an overview of all installed apps.
