### ISSUE TITLE
No login page after successful installation

### ISSUE THREAD

**Issue by Hakkey** [apioo/fusio#318]
Hi, i'm new to this fusio.

I've installed it in my local, the installation was successful but the login page does not show up.

This is the message i got after i add "/fusio" at the end of the URL

![fusio bug](https://user-images.githubusercontent.com/66235760/83375923-17d65100-a403-11ea-8a2a-9dc9c64cb8be.png)

Any idea how can i fix this?

**Comment by chriskapp** [comment]
Hi, so the Fusio backend app is available at `fusio/apps/fusio` path under the `fusio/apps` path you can see all installed apps. We have changed the location in the last release so that your API paths are not limited by the installed apps.

**Comment by Hakkey** [comment]
Alright man, I'll check it out tomorrow.

Great work, thanks!
