### ISSUE TITLE
How to disable CORS in Fusio UI?

### ISSUE THREAD

**Issue by colinvv2** [apioo/fusio#319]
Hi, in the admin panel you can set the `CORS` header under settings `cors_allow_origin` and then use `*` or a specific url. Each API response contains then the `Access-Control-Allow-Origin` header.

_Originally posted by @chriskapp in https://github.com/apioo/fusio/issues/52#issuecomment-323405322_

But there is no CORS options under Settings of the latest version?

**Comment by chriskapp** [comment]
Hi, in my comment I was referring to a setting `psx_cors_origin` at the `configuration.php` file, this is not a setting which you can configure through the backend admin panel. The `cors_allow_origin` backend setting was removed in a later Fusio version.

**Comment by colinvv2** [comment]
I did that as well. At the bottom of the 'configuration.php' file, I have...
`'psx_cors_origin' => '*',`
Still does not work. I do see in the Chrome inspector that there are JS errors trying to check the CORS. I am running Docker version 0.6.0.

**Comment by chriskapp** [comment]
Ok, could you try to run the latest `v1.9.3` docker version and check whether this is still a problem.

**Comment by ratsey** [comment]
Running 1.9.4 from source install and still getting the CORS errors, despite having my configuration.php set:

```
<?php

if (!getenv('FUSIO_ENV')) {
    $dotenv = new \Symfony\Component\Dotenv\Dotenv();
    $dotenv->load(__DIR__ . '/.env');
}

return [

    'psx_cors_origin'         => '*',
    
    // Whether the implicit flow is allowed. This is mostly needed for 
    // javascript apps
    'fusio_grant_implicit'    => true,
```

**Comment by ratsey** [comment]
@chriskapp  
Update: Playing around with _vendor/psx/framework/src/Http/CorsPolicy.php_ and if I place this as the first line, it seems to be working. Which makes me think that it's either not setting the header at all, or it's not the first header being written?

`$response->setHeader('Access-Control-Allow-Origin: *');`

Even if I take that line out now, it's still working - perhaps cached? Is this as simple as an order of headers and cacheing?

**Comment by ratsey** [comment]
Noticed that I'm getting HTTP 429 responses against the Request Method: OPTIONS when I get the CORS errors. 429 is 'too many requests'. I'm assuming that when some internal 'timeout' expires, my requests start working again and that perhaps this isn't really a CORS issue at all?

**Comment by ItsMattNorman** [comment]
> Noticed that I'm getting HTTP 429 responses against the Request Method: OPTIONS when I get the CORS errors. 429 is 'too many requests'. I'm assuming that when some internal 'timeout' expires, my requests start working again and that perhaps this isn't really a CORS issue at all?
> 
> I have a page that makes several API requests. I'm seeing a mix of 429 that show an x-ratelimit-limit:60 and HTTP 200 x-ratelimit-limit:60 and HTTP 200 x-ratelimit-limit:720
> 
> These are the values for Default (720) and Default-Anonymous (60)
> 
> Since I'm authenticated I don't see why I'd see a mix of the two? I'm going to try increasing these values to see if it goes away.
> 
> Update: I switched the limits on rate for both auth and unauth to 1000/minute, essentially switching it off. All my CORS errors went away.

Where did you set/change the limit rates?

**Comment by ItsMattNorman** [comment]
> > Noticed that I'm getting HTTP 429 responses against the Request Method: OPTIONS when I get the CORS errors. 429 is 'too many requests'. I'm assuming that when some internal 'timeout' expires, my requests start working again and that perhaps this isn't really a CORS issue at all?
> > I have a page that makes several API requests. I'm seeing a mix of 429 that show an x-ratelimit-limit:60 and HTTP 200 x-ratelimit-limit:60 and HTTP 200 x-ratelimit-limit:720
> > These are the values for Default (720) and Default-Anonymous (60)
> > Since I'm authenticated I don't see why I'd see a mix of the two? I'm going to try increasing these values to see if it goes away.
> > Update: I switched the limits on rate for both auth and unauth to 1000/minute, essentially switching it off. All my CORS errors went away.
> 
> Where did you set/change the limit rates?

Found it ahahah right under my nose

**Comment by chriskapp** [comment]
Ok, yes so you can change those limit at the backend under Consumer / Rate. I will close this issue since it looks like it is solved.
