### ISSUE TITLE
 custom connection 

### ISSUE THREAD

**Issue by jiarara** [apioo/fusio#325]
according this instruction "
To develop a custom connection you need to create a class which implements the interface Fusio\Engine\ConnectionInterface. Then you can add this class to the provider.php file. Thus it is possible to select this connection at the backend. 
" 
I develop a clickhouse connection ,  I cannot find class when create it , 
![image](https://user-images.githubusercontent.com/5716373/89532478-6c8fb100-d824-11ea-8e1b-1d15974d7180.png)

my clickhouse php file :
namespace Fusio\Adapter\ClickHouse\Connection;

use Fusio\Engine\ConnectionInterface;
use Fusio\Engine\Form\BuilderInterface;
use Fusio\Engine\Form\ElementFactoryInterface;
use Fusio\Engine\ParametersInterface;

/**
 * ClickHouse
 *
 * @author  Christoph Kappestein <christoph.kappestein@gmail.com>
 * @license http://www.gnu.org/licenses/agpl-3.0
 * @link    http://fusio-project.org
 */
class Hive implements ConnectionInterface
{
    public function getName()
    {
        return 'ClickHouse';
    }

    /**
     * @param \Fusio\Engine\ParametersInterface $config
     * @return new ClickHouseDB\Client
     */
    public function getConnection(ParametersInterface $config)
    {
        $host = $config->get('host');
        $port = $config->get('port');
        if (empty($port)) {
            $port = 8123;
        }

        $username = $config->get('username') ?: null;
        $password = $config->get('password') ?: null;
	$config = [
                  'host' => $host,
                  'port' => $port,
                  'username' => $username,
                  'password' => $password
                  ];
        $db = new ClickHouseDB\Client($config);
        $db->database('default');
        $db->setTimeout(1.5);      // 1500 ms
        $db->setTimeout(10);       // 10 seconds
        $db->setConnectTimeOut(15); // 5 seconds
        return $db;
    }

    public function configure(BuilderInterface $builder, ElementFactoryInterface $elementFactory)
    {
        $builder->add($elementFactory->newInput('host', 'Host', 'text', 'The hostname'));
        $builder->add($elementFactory->newInput('port', 'Port', 'text', 'Optional the port (default is 10000)'));
        $builder->add($elementFactory->newInput('username', 'Username', 'text', 'Optional username for authentication'));
        $builder->add($elementFactory->newInput('password', 'Password', 'text', 'Optional password for authentication'));
    }
}

my provider.php 

return [
    'action' => [
        \Fusio\Adapter\File\Action\FileProcessor::class,
        \Fusio\Adapter\GraphQL\Action\GraphQLProcessor::class,
        \Fusio\Adapter\Http\Action\HttpProcessor::class,
        \Fusio\Adapter\Php\Action\PhpProcessor::class,
        \Fusio\Adapter\Php\Action\PhpSandbox::class,
        \Fusio\Adapter\Sql\Action\SqlSelect::class,
        \Fusio\Adapter\Sql\Action\SqlTable::class,
        \Fusio\Adapter\Util\Action\UtilABTest::class,
        \Fusio\Adapter\Util\Action\UtilCache::class,
        \Fusio\Adapter\Util\Action\UtilJsonPatch::class,
        \Fusio\Adapter\Util\Action\UtilStaticResponse::class,
    ],
    'connection' => [
        \Fusio\Adapter\File\Connection\Ftp::class,
        \Fusio\Adapter\GraphQL\Connection\GraphQL::class,
        \Fusio\Adapter\Http\Connection\Http::class,
        \Fusio\Adapter\Smtp\Connection\Smtp::class,
        \Fusio\Adapter\Soap\Connection\Soap::class,
        \Fusio\Adapter\Sql\Connection\Sql::class,
        \Fusio\Adapter\Sql\Connection\SqlAdvanced::class,
        \Fusio\Adapter\Hadoop\Connection\Hive::class,
        \Fusio\Adapter\Hadoop\Connection\Impala::class,
        \Fusio\Adapter\ClickHouse\Connection\ClickHouse::class,
    ],
    'payment' => [
    ],
    'user' => [
        \Fusio\Impl\Provider\User\Facebook::class,
        \Fusio\Impl\Provider\User\Github::class,
        \Fusio\Impl\Provider\User\Google::class,
    ],
    'routes' => [
        \Fusio\Adapter\Sql\Routes\SqlTable::class,
    ],
];

**Comment by jiarara** [comment]
i get it , the classname is wrong  in ClickHouse.php file ,it should be  ClickHouse  , not Hive

**Comment by chriskapp** [comment]
Yes so the classname must be like the filename, otherwise the connection looks fine.
