### ISSUE TITLE
Error on fresh installation "must be of type integer"

### ISSUE THREAD

**Issue by RightInTwo** [apioo/fusio#327]
When doing a fresh install of Fusio, I get the following error message:

´´´
An error occurred on deploy:

- [UPDATED] schema Todo
- [UPDATED] schema Todo-Collection
- [UPDATED] schema Message
- [UPDATED] action App_Todo_Collection
- [UPDATED] action App_Todo_Insert
- [UPDATED] action App_Todo_Row
- [UPDATED] action App_Todo_Delete
- [FAILED] routes /todo: /config/0/methods/GET/responses/200 must be of type integer
- [FAILED] routes /todo/:todo_id: /config/0/methods/GET/responses/200 must be of type integer

Deploy contained 2 errors!

- /todo: /config/0/methods/GET/responses/200 must be of type integer
- /todo/:todo_id: /config/0/methods/GET/responses/200 must be of type integer
´´´

Is there a workaround so I can finish the installation?

**Comment by chriskapp** [comment]
Hi, this is probably a problem regarding your PHP version, you need at least PHP 7.2, which version do you currently use?

**Comment by RightInTwo** [comment]
@chriskapp, thank you! That is a good point. I had been using the docker container, which was of course working. Now the system itself only has 7.1...

Maybe a version check such as this could be part of the install script?

´´´
if(version_compare(phpversion(), '7.2') == -1)
    show_error('This version of PHP is too old!');
´´´

**Comment by RightInTwo** [comment]
This issue disappeared after the upgrade of php to 7.4.
