### ISSUE TITLE
Add different backend roles

### ISSUE THREAD

**Issue by chriskapp** [apioo/fusio#33]
At the moment we have only one admin role. The admin can configure the complete system and has access to every aspect of the system. We should add also a developer role. An admin could assign specific routes to a developer and the developer is responsible to implement those routes. We could also create a different UI for developers which is especially designed for developing/debugging/testing a specific route.

Through the adapter system is currently already possible that a developer can build API endpoints without touching the production system. The developer must create an composer `fusio-adapter` package (on an private or public packagist). The admin then only needs to register this adapter and assign the developed actions to a specific route.

For this change we would need some sort of a right system which is a big feature. So the question is: Is this something Fusio needs or it is probably better to solve this on another level like described above or through other solutions i.e. creating multiple instances of Fusio.

**Comment by k42b3** [comment]
With the 0.9.2 release we have created a `UserContext` which is passed to every service so it would be easy to write a right check. But this would be an all or nothing right check it would be not possible to allow only specifc records. Also we would need to have a right panel where a admin can configure the rights of each user.

**Comment by chriskapp** [comment]
We should create a new table `fusio_user_rights` which has the columns `resource`, `resource_id`, `view`, `create`, `update`, `delete`. Through this we could set global rights if the `resource_id` is NULL or specific rights if we set a concrete id. The `resource` column basically is a string which represents a concrete resource. For the backend we could create resources like: `action`, `routes`, `schema`, etc.

**Comment by EvoPulseGaming** [comment]
Should cross reference the idea of having child users of a parent user. with inherited scopes....

As creating multiple installations was one of my own possible solutions (still went with managing my own copy of the user database)

**Comment by chriskapp** [comment]
The next release will include specific scopes for the backend i.e.:
![image](https://user-images.githubusercontent.com/2505846/72222184-5fe2fd00-3562-11ea-8b55-ca1d7f22dfac.png)
Through this it will be possible to allow a user only specific rights to the backend. Through this it is possible to create different roles by allowing specific scopes for a user. Also if a user has i.e. the `backend` scope he automatically has access to all `backend.*` sub scopes.
