### ISSUE TITLE
Backend login in 1.9.4

### ISSUE THREAD

**Issue by atanugarai** [apioo/fusio#331]
I was using much earlier version and then trying to deployed the latest one in local. I could access the backend at /fusio/apps/fusio/#!/login but the user created using php bin/fusio adduser doesnt work. The user exists in mySQL fusio_user table,

Any idea?

**Comment by chriskapp** [comment]
Hi, maybe your url "psx_url" at the configuration.php file is not correctly configured, then the backend app cannot access the correct API endpoint.
