### ISSUE TITLE
I want to know the settings to close or off the fusio logs

### ISSUE THREAD

**Issue by anas-gaditek** [apioo/fusio#332]
Disable database storing ?
Its urgent!!!!

**Comment by chriskapp** [comment]
Hi, what do you mean exactly by disable database storing?

**Comment by anas-gaditek** [comment]
Hello, fusio logs currently storing in the database, so that I want to stop them.

**Comment by chriskapp** [comment]
We have now a command `system:log_rotate` which rotates the logs and truncates the existing tables.
