### ISSUE TITLE
CORS issues and Internal Server Errors

### ISSUE THREAD

**Issue by ratsey** [apioo/fusio#334]
I've not used my app in a while, today go to use it and get CORS errors when trying to authenticate. I have the '*' setting in my config but that never really seemed to work.

Not only that, but when I try to login to my server admin page now, I get a 500 (Internal Server Error) from https://mydomain.com/index.php/backend/token

These both worked the last time I used the app (it was probably back in March or April). Note that I'm using 0.6.0, at least that's what it says when I try to login to the admin backend.

Update:
I took a backup of my current server setup and installed the latest source from git. I created a new DB and got the backend working again. However, my original database seems to have no content other than the defaults in any tables other than the fusio_log. Is there any way to 'recover' my actions and routes from the log? I even restored a copy of the fusio DB that my host took yesterday, but it's the same - nothing anywhere except the fusio_log table. Where are the actions and routes stored?!

**Comment by chriskapp** [comment]
Hi, the actions are stored at the table `fusio_action` and the routes at `fusio_routes`. Do you have an error additional error logs of the 500 response.

**Comment by ratsey** [comment]
I must have run the install which overwrote my original data but left the log? I'm rebuilding my routes from YAML configs now, which is a more maintainable way anyway.

Still get the CORS errors though - feel like I've never been able to get CORS working. This is the start of /configuration.php

```
<?php

if (!getenv('FUSIO_ENV')) {
    $dotenv = new \Symfony\Component\Dotenv\Dotenv();
    $dotenv->load(__DIR__ . '/.env');
}

return [

    'psx_cors_origin'         => '*',
    
    // Whether the implicit flow is allowed. 
```

**Comment by ratsey** [comment]
Update: I noticed in my route entity.yaml file that the scope was set wrong. I corrected it and now don't get the same CORS error. Seems somewhat unrelated?

**Comment by ratsey** [comment]
Closing this issue since there are other CORS related issues open
