### ISSUE TITLE
Installation issue for ver1.9.4 (CurlFactory.php line 201: cURL error 60: SSL certificate problem)

### ISSUE THREAD

**Issue by firdaussoberi** [apioo/fusio#335]
Hi,

I am using the public/install.php script to install fusio on my wamp server but on step 5/7 it gives this error:
Could not install backend app, you can install the backend app later on using the command bin/fusio marketplace:install fusio

Checking the script, it uses .runCommand('marketplace:install', ['--disable_ssl_verify', 'name' => 'fusio'], $exitCode) 
which outputs this $e error:

CurlFactory.php line 201: cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/ libcurl-errors.html) marketplace:install [-d|--disable_ssl_verify] [--]

I think this is somehow a curl and ssl issue, because I used ver1.8.0 and install the backend app fine using the install.php script.
Can you look at it? Thanks

**Comment by firdaussoberi** [comment]
Nvm. Solved it. For anyone looking, turns out curl.cainfo was commented out by default in php.ini and you need to have certificate for curl installed. Follow this step: https://stackoverflow.com/a/49071524. Closing issue.

**Comment by chriskapp** [comment]
Ok, for people who can not correctly setup a cainfo, it is also possible to use the `--disable_ssl_verify` flag which deactivates the SSL verify option but it is highly recommend to verify HTTPS connections.
