### ISSUE TITLE
Fusio backend app issues

### ISSUE THREAD

**Issue by designermonkey** [apioo/fusio#345]
The backend app is downloaded automatically in docker into `/apps/fusio` yet it seems that the app JS is aiming requests at `backend` instead of `fusio`.

**Comment by chriskapp** [comment]
Yes so /backend contains the API endpoints which are used by the Fusio app.

**Comment by designermonkey** [comment]
Ok, what I'm meaning is that any calls to `/apps/backend` are going nowhere.

**Comment by designermonkey** [comment]
I've revisited this, rebuilding the containers and it is working ok now.
