### ISSUE TITLE
A very serious production problem

### ISSUE THREAD

**Issue by boy-xiaozhang** [apioo/fusio#348]
Hello, when I use Action for a query, the query results will be returned in milliseconds, but when I use Route for interface requests, the return rate is very slow. What are the bottlenecks?My actions are measured in milliseconds

![image](https://user-images.githubusercontent.com/60912722/99545297-33083d80-29f0-11eb-9240-32cabe39bf91.png)

![image](https://user-images.githubusercontent.com/60912722/99545502-68ad2680-29f0-11eb-8d13-9cb3a0447b66.png)

Please help to solve it, I will be very grateful

**Comment by chriskapp** [comment]
Hi, if your API receives many requests it could be that the log table slows you down, you could use the "system:log_rotate" command to rotate existing log entries.

**Comment by boy-xiaozhang** [comment]
> Hi, if your API receives many requests it could be that the log table slows you down, you could use the "system:log_rotate" command to rotate existing log entries.

I've tried using the command, but it's still very slow, even reaching 2s

**Comment by boy-xiaozhang** [comment]
> Hi, if your API receives many requests it could be that the log table slows you down, you could use the "system:log_rotate" command to rotate existing log entries.

Thank you so much for your assistance.

**Comment by boy-xiaozhang** [comment]
> Hi, if your API receives many requests it could be that the log table slows you down, you could use the "system:log_rotate" command to rotate existing log entries.
Hello, may I ask if the dashboard will refresh automatically? How should I disable it

**Comment by boy-xiaozhang** [comment]
> Hi, if your API receives many requests it could be that the log table slows you down, you could use the "system:log_rotate" command to rotate existing log entries.

Hello, may I ask if the dashboard will refresh automatically? How should I disable it

**Comment by chriskapp** [comment]
Hi, so the dashboard does not automatically refresh, it only loads the data in case you load the page. I will close this issue since it looks like the problem is solved.
