### ISSUE TITLE
The Token was successfully obtained, and the expiration time of the Token was adjusted, but it remains unrequited

### ISSUE THREAD

**Issue by boy-xiaozhang** [apioo/fusio#351]
The Token was successfully obtained, and the expiration time of the Token was adjusted, but it remains unrequited

curl -X GET -H 'Authorization:eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC8xNzIuMTYuOTIuMTg1Iiwic3ViIjoiNTM3M2Q2Y2EtMzYzNC01OTMxLThkZGItYjAxMjgzMDAxNmYzIiwiaWF0IjoxNjA2NzU4MDk3LCJleHAiOjE2MDc0MDYwOTcsIm5hbWUiOiJ0ZXN0MDEifQ.0G7mFOiB7iWjZniX-yVR2D3ao-SKrAYISelRg82KDK0' 'http://apifusio.com/index.php/testtt'

{
    "success": false,
    "title": "Internal Server Error",
    "message": "Missing authorization header"
}

**Comment by chriskapp** [comment]
Hi, this looks like the `Authorization` header is not passed to Fusio. Please take a look at you web server configuration, if you use Apache you may have not activated `mod_rewrite`.
