### ISSUE TITLE
× Close /config/0/methods/GET/responses/200 must be of type integer

### ISSUE THREAD

**Issue by mit255** [apioo/fusio#354]
We add fusio old version( fusio_1.9.4 ) base on php 7.1 supported 
we have not created routes 200 response not integer error display on top.
Please give me solution if you have know this.

**Comment by chriskapp** [comment]
Hi, version 1.9.4 requires PHP 7.2 or higher I think this is probably also the reason of this error. I would recommend to update the PHP version since PHP 7.1 is also end of life please take a look at https://www.php.net/supported-versions.php
