### ISSUE TITLE
Error in install.php when using a MySQL password containing "$"

### ISSUE THREAD

**Issue by conca** [apioo/fusio#362]
Using `install.php`. My MySQL password had the `$` symbol (for example `"mypass$123"`). 
I was getting the following error:

> An exception occurred in driver: SQLSTATE[HY000] [1045] Access denied for user 'admin'@'localhost' (using password: YES)

Since it wasn't working, I tried the manual instructions. My password was `"mypass$123"`, but in the `.env` file it was written`FUSIO_DB_PW="mypass3"`. Then I figured out it was an issue with the `$` symbol. 

I changed the MySQL password (replaced the `$` symbol), and tried `install.php` again. This time it worked!

**Comment by chriskapp** [comment]
Yes, ok so this is probably due to a wrong escaping at the installer. I have just commited a fix s. https://github.com/apioo/fusio/commit/ee9f0ed423ae2d239e1bb70da7b268f95846d52f Could you check whether this solves the problem for you?

**Comment by conca** [comment]
Now it is setting the password correctly in the `.env` file.
Thanks.
