### ISSUE TITLE
Login to fusion app, not work(German & English)

### ISSUE THREAD

**Issue by felischmi2003** [apioo/fusio#367]
German:
Kann mir dabei bitte jemand Helfen?
Ich habe das Script auf meinem Plesk Server installiert über install.php, ich habe darüber auch das Admin konto erstellt. Aber wenn ich jetzt auf `/apps/fusio` gehe, dann muss ich mich ja anmelden mit dem erstellten Admin konto, aber wenn ich meine daten eingebe passiert nichts, aber wenn ich auf den zurück pfeil gehe, dann kommt das Dash board.
Kann mir bitte jemand helfen, ich verzweifele schon, ich habe es sochon neu installiert nix passiert.
Mit freundlichen grüßen,
Felix Schmitt

English:
Can someone help me with this please?
I installed the script on my Plesk server via install.php, I also used it to create the admin account. But if I go to `/apps/fusio` now, then I have to log in with the admin account that was created, but when I enter my data nothing happens, but when I click the back arrow, the dashboard appears.
Can someone help me please, I'm already desperate, I have just reinstalled it, nothing happened.
With best regards,
Felix Schmitt

**Comment by chriskapp** [comment]
Hi, so we have currently a problem with the installer. The installer does not adjust the ".env" file correactly s. https://github.com/apioo/fusio/issues/365 Could you try to copy the latest version of the install.php script from https://github.com/apioo/fusio/blob/master/public/install.php and check whether the installation works.

**Comment by felischmi2003** [comment]
Ok, thanks for info

**Comment by chriskapp** [comment]
This should be solved with the latest release
