### ISSUE TITLE
Fail to run "deploy"

### ISSUE THREAD

**Issue by williamn** [apioo/fusio#368]
Hello, 
After a successful installation, I tried to run `php bin/fusio deploy` but got the following message 

`Found no existing token, please request a token through the login command`. 

How can I make the "fusio" command identify the token?
Regards.

**Comment by chriskapp** [comment]
Hi, you can simply use the `php bin/fusio login` command to authenticate yourself, then you can issue an deploy

**Comment by williamn** [comment]
thanks, it works.
