### ISSUE TITLE
Alternative OpenAPI viewer app

### ISSUE THREAD

**Issue by chriskapp** [apioo/fusio#369]
Currently we have the [swaggerui](https://github.com/apioo/fusio-apps-swaggerui) app to view the generated OpenAPI spec. There are also several other tools available which we could integrate as app. The following list gives an overview s. https://nordicapis.com/7-open-source-openapi-documentation-generators/ So if there is an interest in a specific tool please let us know.

**Comment by dataforce-troy** [comment]
Would definitely be interested to see support for a few other doc generators added to Fusio. Currently using ReDoc myself

**Comment by chriskapp** [comment]
We have added the redoc app s. https://www.fusio-project.org/marketplace which you can install also from the marketplace.

**Comment by dataforce-troy** [comment]
Well done @chriskapp !
