### ISSUE TITLE
Deploy .fusio.yml with password for Acme-Mysql

### ISSUE THREAD

**Issue by SchwarzwaldFalke** [apioo/fusio#37]
Currently it's not possible to set a password for the Acme-Mysql connection in .fusio.yml.
The password is set to "" during deploy/import in [SystemAbstract.php](https://github.com/apioo/fusio-impl/blob/a7a7a6e77986bd68bdeac29f0b659f085ee6d981/src/Service/System/SystemAbstract.php#L216)

Steps to reproduce:

1. Create a MySQL database for the news example (password required)
2. Set the database credentials in .fusio.yml
3. Execute `php bin/fusio deploy`
4. Deployment fails because the password is set to "" and the connection to Acme-Mysql fails

Output of `php bin/fusio deploy`

> Deploy successful!
> The following actions were done:
>
>- [ERROR] connection Acme-Mysql: An exception occured in driver: SQLSTATE[HY000] [1045] >Access denied for user 'news_test'@'localhost' (using password: NO) in ***/fusio/impl/src/Service/Connection.php on line 131
>- [UPDATED] schema News-Collection
>- [UPDATED] schema News-Entity
>- [UPDATED] action News-Collection
>- [UPDATED] action News-Insert
>- [UPDATED] routes /news
>- [ERROR] Acme-Mysql resources/sql/v1_schema.sql: Could not found connection Acme-Mysql

Is this wanted behavour? How should I set the password for Acme-Mysql (Maybe add a hint to http://fusio-project.org/bootstrap)?

**Comment by k42b3** [comment]
Hi, thx for the report. This is actually a bug, it should be possible to set the
mysql password through the `.fusio.yml` deploy config. I have commited a [fix](https://github.com/apioo/fusio-impl/commit/f86a94f5507f71dd2f60eac0f2dba23db040afa3) 
which should solve this problem. As workaround you could change the 
connection password through the backend ui.

**Comment by SchwarzwaldFalke** [comment]
Perfect, thanks (really fast response!). 

Backend workaround (just in case someone else has the same problem): 
You can't change the password through the backend ui, because there's no connection (deploy script fails before the connection is added). 
So I added a new connection:
- Name: Acme-Mysql
- Class: SQL
- Type: MySQL

**Comment by k42b3** [comment]
great, I plan to release the 0.7.3 version in the upcoming week which then includes also this fix and a solution for apioo/fusio-impl#1

**Comment by k42b3** [comment]
This issue is fixed in the latest version
