### ISSUE TITLE
Apps do not save scopes on Fusio 2.x.x

### ISSUE THREAD

**Issue by Alvie** [apioo/fusio#372]
The "Fusio" app available does not update the App scopes on clicking save and are automatically reverted back to original settings:

![fusio not updating](https://user-images.githubusercontent.com/8447791/107974003-dcd67680-6fad-11eb-9826-02263fed9c3e.gif)

I am assuming that this is due to the app being for 1.x.x and not for the 2.x.x implementation just yet, but it could be that I am doing something wrong? The public and cache folders are in ownership by www-data:www-data if that makes a difference.

**Comment by chriskapp** [comment]
Ok, thanks for the info we will ne to take a look at it and try to reproduce the issue.

**Comment by chriskapp** [comment]
So I have found the problem, it is an issue at the frontend app if you create an app without selecting a scope on creation. I have just commited a fix and also created a new release of the backend app which you can either download manually at https://github.com/apioo/fusio-apps-backend or you can also update the app through the marketplace backend. So please check whether the fix works for your case.

**Comment by Alvie** [comment]
Awesome, thank you so much, I'll test it out tomorrow and report back

**Comment by Alvie** [comment]
Thanks, the update to the backend fixed the issue :)
