### ISSUE TITLE
Installation error: Dependencies

### ISSUE THREAD

**Issue by flyinggman** [apioo/fusio#38]
Hi,

When trying to install (php bin/fusio install), I get the following error:
"You need to set up the project dependencies through composer"

My environment:
- Debian 8
- Lamp stack (PHP 7)

Support is appreciated.

**Comment by k42b3** [comment]
Hi, 

Fusio uses composer as dependency manager. This means you have to run the `composer install` command (to install all dependencies) before running `php bin/fusio install`. A short introduction about composer is available at their [website](https://getcomposer.org/doc/00-intro.md). In the end the `composer install` command creates a `vendor` folder which contains the code of the dependencies.

You can also [download](https://github.com/apioo/fusio/releases) an official release where all dependencies are already installed and you can directly run the `php bin/fusio install` command.
