### ISSUE TITLE
Cors Policy Error on Login

### ISSUE THREAD

**Issue by Alvie** [apioo/fusio#385]
Hello!
I've noticed when using the php bin/fusio login command, I get this error from psx that it is trying to inject a non existing corsPolicy service. This happens with both ways of using the command (i.e. `php bin/fusio login` as well `php bin/fusio login --username=USERNAME --password=PASSWORD`

I think it may be similar to issue #334 from @ratsey which is now closed and #52 , #319  are quite similar. I don't think this is to do with rate limiting. I am using PHP 7.4.16. Below is the stack trace:

```
psx.ERROR: Trying to inject a not existing service corsPolicy in /path/to/fusio/vendor/psx/dependency/src/ObjectBuilder.php on line 115
Stack trace:
#0 /path/to/fusio/vendor/psx/framework/src/Dispatch/ControllerFactory.php(69): PSX\Dependency\ObjectBuilder->getObject()
#1 /path/to/fusio/vendor/psx/framework/src/Loader/Loader.php(100): PSX\Framework\Dispatch\ControllerFactory->getController()
#2 /path/to/fusio/vendor/psx/framework/src/Dispatch/Dispatch.php(126): PSX\Framework\Loader\Loader->load()
#3 /path/to/fusio/vendor/fusio/impl/src/Console/Transport.php(74): PSX\Framework\Dispatch\Dispatch->route()
#4 /path/to/fusio/vendor/fusio/cli/src/Service/Authenticator.php(68): Fusio\Impl\Console\Transport->request()
#5 /path/to/fusio/vendor/fusio/cli/src/Command/Auth/LoginCommand.php(98): Fusio\Cli\Service\Authenticator->requestAccessToken()
#6 /path/to/fusio/vendor/symfony/console/Command/Command.php(256): Fusio\Cli\Command\Auth\LoginCommand->execute()
#7 /path/to/fusio/vendor/symfony/console/Application.php(971): Symfony\Component\Console\Command\Command->run()
#8 /path/to/fusio/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#9 /path/to/fusio/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#10 /path/to/fusio/bin/fusio(47): Symfony\Component\Console\Application->run()
#11 {main}
The server encountered an internal error and was unable to complete your request.
```

**Comment by chriskapp** [comment]
Hi, have you used `composer update` on your installation? With the next release we have made some changes to the internal framework which removes the cors policy service, if you use the `composer.lock` file which we have published with the release everything should work as expected. With the next release we will then also update the `composer.lock` file.

**Comment by Alvie** [comment]
Yes, it was after a `composer update`. Thanks for the explanation. So are you suggesting not to use composer update and instead only update when the composer lock changes?

**Comment by chriskapp** [comment]
Yes normally it is recommended to simply run `composer install` which installs the versions defined in the `composer.lock` file. If you run `composer update` composer will try to update your dependencies according to the version constraints. Normally this should be not a problem but sometimes this could go wrong like in this case, so if you want a stable system it is recommended to use the `composer.lock` file from the release.

**Comment by udliveio** [comment]
Hi @chriskapp I am getting this error again.

I have copied the composer.json and composer.lock files exactly as it is in the github and even removed the vendor folder and ran `composer install` (not `composer update`) again

**Comment by chriskapp** [comment]
Hi ok, could you delete all files in the cache/ folder this could also solve the problem.

**Comment by udliveio** [comment]
> Hi ok, could you delete all files in the cache/ folder this could also solve the problem.

Thanks, that worked! Is there a way to do this via a command? such as `system:clear_cache` but that seems to do something else?
