### ISSUE TITLE
LDAP Authentication Mechanism Support

### ISSUE THREAD

**Issue by rohan-97** [apioo/fusio#392]
Hello,

I am new to fusio.
I was planning to add API gateway in my existing App.

I wanted to know is there any plugin/Authentication mechanism to support LDAP authentication?
If not how can I develop one?

Thanks in advance!

**Comment by chriskapp** [comment]
Hi, so currently we have no LDAP support but we have an extensible OAuth2 system which you could use i.e. to add other providers. At the moment we support Facebook, Github and Google s. `src/Provider/User/Facebook.php:73`. Iam also not sure whether it would be worth it to add an LDAP auth. In the future I would rather try to add a SCIM api to sync users and groups with a remote system. If you are required to use LDAP you could take a look at the `authenticateUser` method of `src/Service/User.php:124` which would be probably the place to handle the LDAP bind.

**Comment by rohan-97** [comment]
@chriskapp , 
Thanks a lot for information!
