### ISSUE TITLE
Outputting CSV instead of JSON

### ISSUE THREAD

**Issue by zaibatsu92** [apioo/fusio#408]
Hi,
is there a way to output CSV? I think I can write a converter myself but I don't know how I could integrate it into fusio. Is there a way to get the JSON-data from the response object and then fill it with CSV-encoded data? The fusio doc doesn't provide much info about the response object.

**Comment by zaibatsu92** [comment]
Okay I looked further into this and noticed that the response object contains the data in arrays. So the conversion to Json is done after the Action handle-method returns. So implementing this probably needs rewriting the fusio source code.

**Comment by chriskapp** [comment]
Hi, so you could create a custom serializer, we have also a chapter regarding this topic at our manual s.
https://fusio.readthedocs.io/en/latest/internal/serialization.html

**Comment by zaibatsu92** [comment]
Thank you. This worked really nice. Only one thing: When I open the the endpoint with ?format=csv in a browser it downloads the the file with the name of the endpoint (without a ".csv"). Can I somehow make it so that the file is named endpoint.csv instead?

**Comment by chriskapp** [comment]
Great, mhh so in this case you would need to set somehow a `Content-Disposition` header to set the filename. In general you could do this in your action, you could also set this as a hack in your serializer through the `header` function but in general I would recommend to use set this inside your action.

**Comment by zaibatsu92** [comment]
How can I do that from the Action? What object holds the information and how can I access it? 

Thank you for your answers so far.

**Comment by chriskapp** [comment]
So that depends a bit on your action type but in most cases you set a custom header i.e. with:
```php
$headers = [
    'Content-Disposition' => 'attachment; filename="my_file.csv"'
];
return $this->response->build(200, $headers, $myData);
```

**Comment by zaibatsu92** [comment]
Thank you. That worked and solved it.
