### ISSUE TITLE
MySQL tables not updating

### ISSUE THREAD

**Issue by christiaanvaken** [apioo/fusio#409]
When I remove a route or connection from the Fusio web interface, the record is not deleting from the MySQL database but it is gone from the web interface. Any idea? I am using NGINX / PHP 7.4 and MySQL 8.0.

**Comment by Alvie** [comment]
I think this is intentional, the status should get updated to 0 which is a flag for it to not be used. It still exists in the database, which makes it easier to fix if it was an accident or if needed for auditing purposes (to check if that route / connection did exist at some point).

**Comment by christiaanvaken** [comment]
Okay if you say it like that it makes sense. But then it would be better if there is a disable button instead. And if you really want to remove it a delete button.

**Comment by chriskapp** [comment]
Hi, yes so @Alvie is right we only set the status to 0. This is also because you use the connection name in your actions and if you delete the connection those actions are still working. We have also a command `system:restore` if you want to bring the connection back to the list.

**Comment by christiaanvaken** [comment]
Okay thanks, it would be a great feature if you can choose between disable and delete.

**Comment by froschi123** [comment]
And how would i delete a route if i want to delete it? I created a route /user to test something and than deleted it. Now i con no longer create a new route /user - i will get an internal server error. 
How do i use the system:restore command?
