### ISSUE TITLE
Mixed Content - The content must be served over HTTPS

### ISSUE THREAD

**Issue by dev-2-4-h** [apioo/fusio#412]
Hi, 
Setting up Fusio on a load-balanced environment where HAProxy is handling HTTPS encryption and the internal server is running on HTTP,  this error comes when I try to log in:
`Mixed Content: The page at 'https://dev.DOMAIN.eu/apps/fusio/#!/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://dev.DOMAIN.eu/index.php/authorization/token'. This request has been blocked; the content must be served over HTTPS.`

**The .env file :**
> FUSIO_PROJECT_KEY="xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
> FUSIO_HOST="dev.DOMAIN.eu"
> FUSIO_URL="https://${FUSIO_HOST}"
> FUSIO_APPS_URL="${FUSIO_URL}/apps"
> FUSIO_ENV="prod" # dev or prod
> FUSIO_DB_NAME="db"
> FUSIO_DB_USER="user"
> FUSIO_DB_PW="xxxxxxxxxxxxxxxxxxx"
> FUSIO_DB_HOST="localhost"
> FUSIO_DB_DRIVER="pdo_mysql"

I was unable to find any hint in the documentation or with Google. My guess is that the code checks that the server runs on HTTP and is not using the ${FUSIO_URL} from the .env file. A problem that I encountered previously with Joomla.

I don't know if this classifies as a BUG, but I need to get this working, even if I have to introduce changes to the source myself.

Thanks for reading 
Claus

**Comment by chriskapp** [comment]
Hi, so the problem is here that your backend app contains a `http://` url, could you update the `index.html` at `public/apps/fusio/index.html` to use `https` then it should work as expected.

**Comment by dev-2-4-h** [comment]
Thanks for this tip - I check it first thing tomorrow.

**Comment by dev-2-4-h** [comment]
Would this be this oart of index.html?
`fusioApp.config(['fusioProvider', function(fusioProvider) {
        /**
         * Url to the Fusio API endpoint. Change this to the fitting url to the
         * backend API. If not provided Fusio will try to guess the correct url.
         * I.e.: http://127.0.0.1/projects/fusio/public/index.php/
         *
         * If you change the first argument of guessFusioEndpointUrl from false
         * to true all API calls are made without index.php/
         */
        fusioProvider.setBaseUrl('https://dev.DOMAIN.eu/index.php/');
`
That was set correctly! 

Below is the error displayed in the console. I'm not that good at coding.

>fusio.min.js:formatted:45863 Mixed Content: The page at 'https://dev.DOMAIN.eu/apps/fusio/#!/login' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://dev.DOMAIN.eu/index.php/authorization/token'. This request has been blocked; the content must be served over HTTPS.
(anonymous) @ fusio.min.js:formatted:45863
(anonymous) @ fusio.min.js:formatted:45706
(anonymous) @ fusio.min.js:formatted:45749
(anonymous) @ fusio.min.js:formatted:47358
(anonymous) @ fusio.min.js:formatted:47368
$digest @ fusio.min.js:formatted:47756
$apply @ fusio.min.js:formatted:47867
(anonymous) @ fusio.min.js:formatted:50825
defaultHandlerWrapper @ fusio.min.js:formatted:42932
eventHandler @ fusio.min.js:formatted:43113
fusio.min.js:formatted:46483 TypeError: Cannot read properties of null (reading 'error_description')
    at fusio.min.js:formatted:30233
    at fusio.min.js:formatted:47358
    at fusio.min.js:formatted:47368
    at Scope.$digest (fusio.min.js:formatted:47756)
    at Scope.$apply (fusio.min.js:formatted:47867)
    at done (fusio.min.js:formatted:45730)
    at completeRequest (fusio.min.js:formatted:45883)
    at XMLHttpRequest.requestError (fusio.min.js:formatted:45836) 'Possibly unhandled rejection: {}'

**Comment by dev-2-4-h** [comment]
@chriskapp  - Danke Christoph, dein tipp brachte mich auf die richtige Spur.

Found the root cause : there is another .env file in the folder [./public/apps/fusio] - didn't notice hat before.
Once filled out correctly, the 'Mixed Content' error disappeared. 
Next error now: 
> /index.php/authorization/token 404 (Not Found)
 
but this issue is solved
 
 Thanks for the help
Claus
