### ISSUE TITLE
Call to undefined method stdClass::hasProperty() when using table methods

### ISSUE THREAD

**Issue by ratsey** [apioo/fusio#423]
I have GET SqlQueryRow method calls working nicely, it's a real timesaver being able to provide the SQL direct to Fusio and not have to create PHP classes.

I'm now trying to insert data with POST and update with PATCH, but not having any luck. If I use the 'Designer' tool, my test JSON will happily update a row in my test table. But if I try to use the route with Insomnia as my client, I get an error 

```
Call to undefined method stdClass::hasProperty() in \/home\/xxxxxxxxx\/vendor\/fusio\/adapter-sql\/src\/Action\/SqlActionAbstract.php on line 87",
  "trace": "#0 \/home\xxxxxxx\/vendor\/fusio\/adapter-sql\/src\/Action\/SqlInsert.php(60): 
```

I get the same error when I try to insert a row with POST. I'm also not sure how I'd get the ```:id``` parameter from the route into the update. Does it have to be explicitly provided in the JSON payload?

**Comment by chriskapp** [comment]
Hi, ok do you have configured a specific schema for your route or do you use the Passthru schema? Regarding the `SqlInsert` action, in general we get the id from the database through an auto increment so you dont need to provide the id.

**Comment by ratsey** [comment]
Using Passthru.

I use identity fields so get that for the insert, but on an update I would
like to use a route such as Customer/123 and update with a PATCH with the
id as 123 rather than having to put it in the JSON.

**Comment by ratsey** [comment]
Still having a problem trying to insert a row using POST. 

I have a route `/Customers` that exposes a POST end point with passthru for parameters and request. That route calls an action `addCustomer `that uses class `Fusio\Adapter\Sql\Action\SqlInsert` and engine `Fusio\Engine\Factory\Resolver\PhpClass`. The config is setup with the appropriate connection and table.

If I use the designer tool to Execute a test using this payload, the row is successfully inserted into the table

```
{ 
	"value1": "testing value 1",
	"value2": "testing value 2"
}
```

```
Response 201
{
    "success": true,
    "message": "Entry successful created",
    "id": "3"
}
```

If I try to use Insomnia with the same payload, to the same enpoint, using a POST method, I get the error:
```
{
	"success": false,
	"title": "Error",
	"message": "Call to undefined method stdClass::hasProperty() in \/home\/xxx\/xxx\/vendor\/fusio\/adapter-sql\/src\/Action\/SqlActionAbstract.php on line 87",
	"trace": "#0 \/home\/xxx\/xxx\/vendor\/fusio\/adapter-sql\/src\/Action\/SqlInsert.php(60): Fusio\\Adapter\\Sql\\Action\\SqlActionAbstract->getData(Object(Fusio\\Engine\\Request\\HttpRequest), Object(Doctrine\\DBAL\\Connection), Object(Doctrine\\DBAL\\Schema\\Table), true)\n#1 \/home\/xxx\/xxx\/vendor\/fusio\/engine\/src\/Processor.php(86): Fusio\\Adapter\\Sql\\Action\\SqlInsert->handle(Object(Fusio\\Engine\\Request\\HttpRequest), Object(Fusio\\Engine\\Parameters), Object(Fusio\\Engine\\Context))\n#2 \/home\/xxx\/xxx\/vendor\/fusio\/impl\/src\/Service\/Action\/Invoker.php(89): Fusio\\Engine\\Processor->execute('addCustomer', Object(Fusio\\Engine\\Request\\HttpRequest), Object(Fusio\\Engine\\Context))\n#3 \/home\/xxx\/xxx\/vendor\/fusio\/impl\/src\/Controller\/SchemaApiController.php(244): Fusio\\Impl\\Service\\Action\\Invoker->invoke(Object(Fusio\\Engine\\Request\\HttpRequest), Object(Fusio\\Engine\\Context))\n#4 \/home\/xxx\/xxx\/vendor\/fusio\/impl\/src\/Controller\/SchemaApiController.php(183): Fusio\\Impl\\Controller\\SchemaApiController->executeAction(Object(Fusio\\Engine\\Record\\PassthruRecord), Object(PSX\\Http\\Environment\\HttpContext))\n#5 \/home\/xxx\/xxx\/vendor\/psx\/framework\/src\/Controller\/SchemaApiAbstract.php(128): Fusio\\Impl\\Controller\\SchemaApiController->doPost(Object(Fusio\\Engine\\Record\\PassthruRecord), Object(PSX\\Http\\Environment\\HttpContext))\n#6 \/home\/xxx\/xxx\/vendor\/psx\/framework\/src\/Controller\/ControllerAbstract.php(179): PSX\\Framework\\Controller\\SchemaApiAbstract->onPost(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#7 \/home\/xxx\/xxx\/vendor\/psx\/framework\/src\/Controller\/ControllerAbstract.php(145): PSX\\Framework\\Controller\\ControllerAbstract->onRequest(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#8 \/home\/xxx\/xxx\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): PSX\\Framework\\Controller\\ControllerAbstract->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#9 \/home\/xxx\/xxx\/vendor\/fusio\/impl\/src\/Controller\/Filter\/Logger.php(68): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#10 \/home\/xxx\/xxx\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): Fusio\\Impl\\Controller\\Filter\\Logger->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#11 \/home\/xxx\/xxx\/vendor\/fusio\/impl\/src\/Controller\/Filter\/RequestLimit.php(74): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#12 \/home\/xxx\/xxx\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): Fusio\\Impl\\Controller\\Filter\\RequestLimit->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#13 \/home\/xxx\/xxx\/vendor\/fusio\/impl\/src\/Controller\/Filter\/Authentication.php(66): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#14 \/home\/xxx\/xxx\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): Fusio\\Impl\\Controller\\Filter\\Authentication->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#15 \/home\/xxx\/xxx\/vendor\/fusio\/impl\/src\/Controller\/Filter\/AssertMethod.php(99): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#16 \/home\/xxx\/xxx\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): Fusio\\Impl\\Controller\\Filter\\AssertMethod->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#17 \/home\/xxx\/xxx\/vendor\/psx\/http\/src\/Filter\/UserAgentEnforcer.php(43): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#18 \/home\/xxx\/xxx\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): PSX\\Http\\Filter\\UserAgentEnforcer->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#19 \/home\/xxx\/xxx\/vendor\/psx\/http\/src\/Filter\/CORS.php(107): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#20 \/home\/xxx\/xxx\/vendor\/psx\/http\/src\/Filter\/FilterChain.php(110): PSX\\Http\\Filter\\CORS->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Http\\Filter\\FilterChain))\n#21 \/home\/xxx\/xxx\/vendor\/psx\/framework\/src\/Loader\/Loader.php(123): PSX\\Http\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#22 \/home\/xxx\/xxx\/vendor\/psx\/framework\/src\/Loader\/Loader.php(102): PSX\\Framework\\Loader\\Loader->execute(Array, Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#23 \/home\/xxx\/xxx\/vendor\/psx\/framework\/src\/Dispatch\/Dispatch.php(126): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(Fusio\\Impl\\Framework\\Loader\\Context))\n#24 \/home\/xxx\/xxx\/vendor\/psx\/engine\/src\/WebServer\/Engine.php(58): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#25 \/home\/xxx\/xxx\/vendor\/psx\/framework\/src\/Environment\/Environment.php(70): PSX\\Engine\\WebServer\\Engine->serve(Object(PSX\\Framework\\Dispatch\\Dispatch))\n#26 \/home\/xxx\/xxx\/public\/index.php(28): PSX\\Framework\\Environment\\Environment->serve()\n#27 {main}",
	"context": "83                  continue;\n84              }\n85  \n86              $value = null;\n<b>87              if ($body-&gt;hasProperty($column-&gt;getName())) {\n<\/b>88                  $value = $body-&gt;getProperty($column-&gt;getName());\n89              } elseif (!$validateNull) {\n90                  continue;\n91              } elseif ($column-&gt;getDefault()) {\n"
}
```

**Comment by chriskapp** [comment]
Ok, could you show me a screenshot of your route configuration then I could try to reproduce the issue locally.

**Comment by ratsey** [comment]
This is the route:
![image](https://user-images.githubusercontent.com/7027608/146616617-9e3dd6b6-c238-472f-bc45-afecd205fd31.png)

the action:
![image](https://user-images.githubusercontent.com/7027608/146616665-a771fb4f-c129-45be-a920-417f6901b998.png)

and the test table I'm playing with in MariaDB
![image](https://user-images.githubusercontent.com/7027608/146616741-4005ac69-c8f2-4163-9e41-6fa7e6905261.png)

**Comment by chriskapp** [comment]
Hey @ratsey I have just looked at this issue and there is indeed a problem if your route does not use a schema, if you use a schema like:
![image](https://user-images.githubusercontent.com/2505846/146642739-1988b957-9f65-4f2e-9728-1a0fe4998e33.png)
everything works as expected, but if you use the Passthru schema this problem occurs. I have just commited a fix s. https://github.com/apioo/fusio-adapter-sql/commit/a2a67c3381f76fb279c0467ae62fde2c66317a07 and tagged a new version v4.0.6, so if you update the adapter to the latest version the problem should be fixed.

**Comment by ratsey** [comment]
Confirmed that works for the POST command, thanks! Not a huge issue, but a PATCH against a non-existent ID still returns a success message. Ideally it would return a 'not found' or similar.

**Comment by ratsey** [comment]
@chriskapp Getting something vaguely similar when trying to issue an HTTP DELETE command from an Angular app.

This is the payload - note that the JSON object in Angular doesn't have quoted names, but this works quite well for the PATCH and POST commands.

```
{id: 36, name: "test", wholesale_price: "0.00", is_physical: 1, is_shippable: 1}

"PropertyAccessor requires a graph of objects or arrays to operate on, but it found type "NULL" while trying to traverse path "id" at property "id". in /home/xxx/xxx/vendor/symfony/property-access/PropertyAccessor.php on line 344"
```

If I issue the quoted version in Insomnia, it works as expected.
`{"id": 36, "name": "test", "wholesale_price": "0.00", "is_physical": 1, "is_shippable": 1}`

Is this related to the above fix?

![image](https://user-images.githubusercontent.com/7027608/147298292-b62d34f5-3cf8-4353-9aaf-93c513070baf.png)
![image](https://user-images.githubusercontent.com/7027608/147298321-29be39fd-8344-4439-8d23-cf2ab89be1ea.png)

**Comment by chriskapp** [comment]
@ratsey so I think its probably not related to the fix since PHP is not able to decode non quoted JSON so I would also assume that this does also not work for other request methods. But if you use something like `JSON.stringify` at you Angular app you will get automatically the fitting quoted JSON.

**Comment by ratsey** [comment]
Thanks for the confirmation @chriskapp. That prompted me to dig further and discover that the Angular httpclient doesn't treat the body in the same way as other operations in a delete and has to have it explicitly declared.  Now working.  I will close out this issue.  Fusio rocks.
