### ISSUE TITLE
Too many columns in SQL table

### ISSUE THREAD

**Issue by mat02** [apioo/fusio#426]
I have a table with over 100 columns defined. Unfortunately, if SelectAll SQL action has more than 43 columns Fusio returns with empty response. However, when SelectRow is called, it returns all columns just fine.
There is nothing in the server log (should I enable the debug/verbose mode somehow?). 

What can cause such issue?

**Comment by chriskapp** [comment]
Hi, ok, so in general there is no limit by Fusio which restricts the response, so I would guess that somehow the complete payload is too big. You could set the `FUSIO_ENV` in your `.env` file to `dev` then the error message of Fusio returns also a stacktrace. Otherwise you could also take a look a at the log of your web server which may contain additional information.

**Comment by mat02** [comment]
Thanks for prompt reply.
I've set the FUSIO_ENV to dev, but there is no error log whatsoever. I don't get any response from the Fusio endpoint.
Only log line I get in the log is from the apache:
`10.0.1.24 - - [09/Dec/2021:19:41:03 +0000] "GET /erp/defdok HTTP/1.0" 200 288 "https://mydomain.com/apps/fusio/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.51 Safari/537.36"`
![image](https://user-images.githubusercontent.com/1629659/145465342-2772e32b-f2bf-4517-a5f9-12a8a78a4685.png)

I've placed some debugging lines in the Fusio\Adapter\Sql\Action\SqlSelectAll handle() method and it appears to be working fine, i.e. this function returns correct data, so the problem is not on the DB side.

I don't know the architecture of Fusio so well, so maybe you could point me to the right place in the source code to investigate further?

**Comment by mat02** [comment]
Thanks, will try that 👍 
I've noticed, that if I pass the count parameter with values up to 5 it works correctly. I guess this has to be something with the size of the response, although the biggest working response (with 5 items) is 26 kB (including headers), so not that big.

**Comment by mat02** [comment]
Ok, so the problem was not in the size of data, but with the database connection charset. It just happend that the problematic data was in the sixth row ... The JSON encoder was failing to parse ISO8859-2-encoded data. 
Anyway, setting charset to UTF-8 resolved the issue. Thanks for your help :)
