### ISSUE TITLE
Is this project production ready?

### ISSUE THREAD

**Issue by coldwinds** [apioo/fusio#43]
Looks promising.

**Comment by k42b3** [comment]
Hi, thx, so the project has not reached a stable 1.0 release so I wont call it production ready. But it is currently in use at several private projects so it is stable enough for the most use cases. Feel free to checkout and test the current version.

**Comment by coldwinds** [comment]
Thank you for your work, nice job and keep it up,  I'll give it more test:)

**Comment by k42b3** [comment]
You are welcome ;), if you have any further questions please let me know.
