### ISSUE TITLE
Migrations on Update

### ISSUE THREAD

**Issue by wehowski** [apioo/fusio#432]
Hello nach Düsseldorf,
first thank you for the great work! I consider to contribute, promote or donate for it ...

There is only one thing left I still get some problems with:
First I would like to suggest one possible solution I used before with success in other projects: https://github.com/GaneshKandu/kdbv

When I try to update an existing fusio-api instance in a production environment I could not migrate the existing DB to the new schemas while keeping the data without manual hacking.

Maybe it is my fail and I did not use the migration correctly?

Instead of creating the DB from scratch, I would like to compare the new and the old schema and process the diffs by alter the tables while keeping existing data.

regards,
Till

**Comment by chriskapp** [comment]
Hey @wehowski thanks for the great feedback. I was not aware of the tool you posted, it is only related to mysql or does it handle also other databases like postgres? But in general the doctrine migration library which we use under the hood should be able to do this i.e. if we release a new version and you want to adjust your schema you can run:

```
php bin/fusio migration:migrate
```

which then executes all table changes to the latest version. There is also a dry run if you just want to test the update:

```
php bin/fusio migration:migrate --dry-run
```

or you can also use the write-sql option to get the SQL which gets executed:

```
php bin/fusio migration:migrate --write-sql
```

with the SQL you could then also see directly which changes are executed before executing the actual update.

**Comment by wehowski** [comment]
Hello Chris,
thank you! I will try this on the next update...

**Comment by wehowski** [comment]
`php bin/fusio migration:migrate`
This was working for me now. 
Thank you!
