### ISSUE TITLE
Backend API documentation not available

### ISSUE THREAD

**Issue by dgambin** [apioo/fusio#442]
Hi,

I am trying to reach documentation for backend API endpoints. I went to https://docs.fusio-project.org/ and clicked on "Backend API" which points to https://demo.fusio-project.org/apps/internal/#!/page/about. But the requested page is not found. Is there some other link where I can see all the backend API endpoints explained? Specifically, I am interested in available endpoints for token management (getting informations about active tokens etc.)

regards, dejan

**Comment by chriskapp** [comment]
Hi Dejan, this is true, so you could take a look at the https://demo.fusio-project.org/apps/documentation/#!/api/ and choose there at the "category" either the "consumer" or "backend" category to see all endpoints. I will also try to update the link so that it points to the correct url.

**Comment by chriskapp** [comment]
So I have updated also the doc website with the correct link
