### ISSUE TITLE
TypeError: Failed to fetch  if json are to long

### ISSUE THREAD

**Issue by dochardi** [apioo/fusio#448]
Hello we get always are "TypeError: Failed to fetch" it the json are to long this are us action

`Class: Fusio\Adapter\Http\Action\HttpProcessor

Engine:Fusio\Engine\Factory\Resolver\PhpClass

Config:
{
  "url": "https://hidenserverurl.de/api/test.php",
  "type": "application/json",
  "version": "1.1"
}
`

this are the json 

This not work:
`{"statusCode":"200","info":"7f2b531e-dd87-46f8-b227-ea815867a6e2","art":"png"}`

But this work

`{"statusCode":"200","info":"7f2b531e-dd87-46f8-b227-e","art":"png"}`

<html>
<body>
<div style="box-sizing: border-box; color: rgb(59, 65, 81); font-family: sans-serif; font-size: medium; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgba(97, 175, 254, 0.1); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><h4 style="box-sizing: border-box; font-size: 12px; margin: 10px 0px 5px; font-family: sans-serif; color: rgb(59, 65, 81);">Request URL</h4><div class="request-url" style="box-sizing: border-box;"><pre class="microlight" style="box-sizing: border-box; font-family: monospace; font-size: 12px; margin: 0px; padding: 10px; white-space: pre-wrap; word-break: break-word; hyphens: auto; border-radius: 4px; background: rgb(51, 51, 51); overflow-wrap: break-word; font-weight: 600; color: rgb(255, 255, 255);">http://apis.....:8383/api-infos</pre></div></div><h4 style="box-sizing: border-box; font-size: 12px; margin: 10px 0px 5px; font-family: sans-serif; color: rgb(59, 65, 81); font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgba(97, 175, 254, 0.1); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Server response</h4>

Code | Details
-- | --
Undocumented | TypeError: Failed to fetch

</body>
</html>

**Comment by chriskapp** [comment]
Hi, ok this sounds strange, if I see this correctly the JSON response only differs in this 11 characters? If you invoke your remote endpoint directly without Fusio, this works then as expected? In general Fusio has no limitation regarding the response size.

**Comment by dochardi** [comment]
On the origin server its work only in Fusio its not work i have try it on the demo server frome Fusio and on me hosted both give that issuse

**Comment by chriskapp** [comment]
ok, I have just checked the action at the demo and the problem is probably that your API endpoint does not return a fitting `Content-Type`, the JSON is served as `text/html`. Could you set at your API the `Content-Type` to `application/json` and check whether this works?

**Comment by dochardi** [comment]
I have don that no changen
 That what header are send back



HTTP/1.1 200 OK
--
Fri, 18 Mar 2022 21:04:11 GMT
Apache
PHP/7.3.16
*
User-Agent
application/json


</body>
</html>

**Comment by chriskapp** [comment]
Ok, this looks indeed fine, could you send me a striped down version of the script which produces the API response so that I can locally reproduce this error?

**Comment by chriskapp** [comment]
In the latest release we have also made several improvements to the `HttpProcessor` so please try to use the current version and check whether the problem still exists.
