### ISSUE TITLE
Failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by eodidiet** [apioo/fusio#455]
Hi, I created a HelloWorld.php class as follows
```
namespace App\Action;

use Fusio\Engine\ActionAbstract;
use Fusio\Engine\ContextInterface;
use Fusio\Engine\ParametersInterface;
use Fusio\Engine\RequestInterface;

class HelloWorld extends ActionAbstract
{
    public function handle(RequestInterface $request, ParametersInterface $configuration, ContextInterface $context): mixed
    {
        return $this->response->build(200, [], [
            'hello' => 'world'
        ]);
    }
}
```

 added it to the src file and updated composer.json as shown below:
```
"autoload": {
    "psr-4": {
      "App\\": "src/"
    }
  }
```
then did a composer update.

However i am getting stuck at adding this class when creating an action through the dashboard. I keep getting this error:

Failed to open stream: No such file or directory in ..   with file path: src/Action/HelloWorld.php. Could you let me know what i am doing wrong.

Thanks

**Comment by eodidiet** [comment]
Hi, Found where the problem was.

i mis-typed the name of the php file: i saved the file as HellowWorld.php instead of HelloWorld.php

secondly, after adding it to the provider.php, all i had to do was select the Class from the Action Class dropdown list. However this is not so clear in the tutorial (https://docs.fusio-project.org/docs/use_cases/develop_custom_action/#integration). 

The text under this code
```
<?php

return [
    'action' => [
        // ...
        \App\Action\HelloWorld::class,
    ],
    // ...
];
```
Should read as something like this: 

**Then you can also select this class from the dropdown list of Action classes at the fusio backend** instead of 
~Then you can also select this action at the backend~

**Comment by chriskapp** [comment]
Great, I have also adjusted the docs s. https://github.com/apioo/fusio-docs/commit/3d884d3a62b55d25322ceb66efeb29d6c944d491
Also please feel free to make any suggestions directly through Github, at the bottom of the documentation there is an "Edit this page" button which points to the fitting markdown file.
