### ISSUE TITLE
Unknown column 'event_schema'

### ISSUE THREAD

**Issue by ratsey** [apioo/fusio#456]
I did a manual upgrade to Fusio a few weeks ago by copying the new vendor code over. It seems to run OK, but when I try to add a new user from the UI I get an error:

`An exception occurred while executing 'SELECT id, category_id, status, name, description, event_schema FROM fusio_event WHERE (name = ?) ORDER BY id DESC LIMIT 1' with params ["fusio.user.update"]: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'event_schema' in 'field list' in /home/xxxxx/xxxxxx/vendor/psx/sql/src/TableAbstract.php on line 217`

The table fusio_event doesn't have that field in my DB. Did it get setup in a later version than I have installed?

**Comment by chriskapp** [comment]
Hi, yes so the column name has changed from `event` to `event_schema` since `event` is a reserved keyword at some DB vendors but if you execute the `bin/fusio install` command the migration should rename the column.

**Comment by ratsey** [comment]
I get permission denied when I try to run `bin/fusio install` from a shell. Opened up the `Install.php` but concerned about the 

`Connection credentials to the database. Please be aware that Fusio needs a dedicated database, it will delete any table on the database which does not belong to the Fusio schema.`

phrasing. Is there documentation on the Fusion schema that I can just manually update to the correct structure? This is a DEV database but I really don't want to wipe it if at all possible.

**Comment by chriskapp** [comment]
Ok great, regarding the schema so you can always take a look at the migration file at `vendor/fusio/impl/src/Migrations/Version/Version20200905081453.php` to get the latest schema but your fix should also work.
