### ISSUE TITLE
Response result page

### ISSUE THREAD

**Issue by runners911** [apioo/fusio#458]
I have Action that use Class SQLQueryAll and set the limit to 10. My question, how to go to the specific page of results if my totalResults is more than 10? My Body Request is null.
![image](https://user-images.githubusercontent.com/106133138/169945770-8a6b3139-1016-48e2-abbe-11cbdbf1ddef.png)

**Comment by chriskapp** [comment]
Hey, you can use the `startIndex` and `count` query parameters to control the results.

**Comment by runners911** [comment]
Thank you very much.
