### ISSUE TITLE
ItemsPerPage limit

### ISSUE THREAD

**Issue by Maximebaker** [apioo/fusio#477]
Hi, I am trying to make an api call and get more than 16 items per page... But I can't figure out how to do it. Can someone help me with that please?

**Comment by chriskapp** [comment]
Hi, sure so you can simply use the `count` query parameter at most endpoints to adjust the collection size.

**Comment by Maximebaker** [comment]
I just tried that and it work for value under 16. But can't go higher... :(

**Comment by chriskapp** [comment]
@Maximebaker ok can you show me which action class do you actually use, then we can check whether there is a hard limit set.

**Comment by Maximebaker** [comment]
> @Maximebaker ok can you show me which action class do you actually use, then we can check whether there is a hard limit set.
> 

Here it is my friend :
Fusio\Adapter\Sql\Action\Query\SqlQueryAll

**Comment by Maximebaker** [comment]
@chriskapp Here it is my friend :
Fusio\Adapter\Sql\Action\Query\SqlQueryAll

**Comment by chriskapp** [comment]
@Maximebaker ok so there you can use the `count` query parameter but you have probably not configured a limit, in this case the default is 16. The limit basically tells Fusio the maximum possible count value, to prevent misuse, if you set the limit to i.e. 32 then you can also use 32 at the `count` query parameter s.
https://github.com/apioo/fusio-adapter-sql/blob/master/src/Action/Query/SqlQueryAll.php#L55

**Comment by Maximebaker** [comment]
@chriskapp Where do I need to configure the limit?

**Comment by Maximebaker** [comment]
@chriskapp Omg... Ok... I just found it! Thank you my friend!
