### ISSUE TITLE
Deleting a user and re-adding the user with the same username doesn't work

### ISSUE THREAD

**Issue by dnng** [apioo/fusio#48]
# Description

When deleting a user through the portal, the UI (admin portal) responds that the request was successful. This can be verified by typing  `php bin/fusio user:list` in the server and checking that the user was indeed deleted. When trying to re-add the user using the same name, the UI (admin portal) displays the following error:

> The server encountered an internal error and was unable to complete your request.

When I tried adding the user via command line (`php bin/fusio user:add`), the following error is displayed:

```
[Doctrine\DBAL\Exception\UniqueConstraintViolationException]
  An exception occurred while executing 'INSERT INTO fusio_user (provider, status, name, email, password, date) VALUES (?, ?, ?, ?, ?, ?)' with params [1, 1, "ruth", "foo@bar.com", "$2y$10$HrDho8u
  D\/a2wCb4g9GoUtuiFb\/iug1Mc.YvX9w64Wjvx1Vvt4ShYW", "2017-08-11 01:38:56"]:
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'foo' for key 'UNIQ_5680E95E5E237E06'


  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'foo' for key 'UNIQ_5680E95E5E237E06'


  [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'foo' for key 'UNIQ_5680E95E5E237E06'
```

# Steps to reproduce

1. Access `http://localhost:1234/fusio` with the default user
2. Create user `foo` with type `Administrator`
3. Delete user `foo`
4. Add user `foo` again

# Expected resut

User is re-added with no problem

# Observed behavior

Fusio server throws exceptions `UniqueConstraintViolationException` and `PDOException`

# Additional information

1. System installed using `fusio-docker` version v0.9.1
2. Running under an Ubuntu virtual machine 16.04
3. Docker version is `Docker version 17.06.0-ce, build 02c1d87`
4. Chrome version is `60.0.3112.90 (Official Build) (64-bit)`

**Comment by k42b3** [comment]
Hi, thanks for the detailed report. So this behaviour is because we dont actually delete a user, we only set a status flag to deleted. The name column of the user table has also a unique index so it is not possible to add the same user again (since the deleted record still exists). We dont actually delete the user record because the id is maybe referenced in another table i.e. the log table. So this is a known behaviour, as alternative solution we could probably add an option to reactivate a deleted user.

**Comment by k42b3** [comment]
Hi so I have created a new issue #53 which contains the feature to reactivate a deleted record.
