### ISSUE TITLE
Undelete route

### ISSUE THREAD

**Issue by GwNih** [apioo/fusio#491]
I was delete a route, can i undo it? Or can i create a new one with same path?

**Comment by chriskapp** [comment]
Hi, there is a "Trash" Panel under System where you can see and restore all deleted records s.
![image](https://user-images.githubusercontent.com/2505846/212745782-ed4816e5-8535-4ae8-91be-b9aa21f98e7e.png)

**Comment by GwNih** [comment]
My mistake, i'm not choose routes in trash, thats why i'm not see it there.
Thanks for the answer.
