### ISSUE TITLE
Refresh developer page cause internal server error

### ISSUE THREAD

**Issue by cococonuts** [apioo/fusio#502]
I use nginx. Do you know how to solve the issue? Is it related to Nginx? configuration? or router

Description:
I can navigate to Authorization page by clicking "Authorization" on the nav bar
![1](https://user-images.githubusercontent.com/10249233/235232920-32efcb2a-c07e-4a23-b15c-2d8e06aabcd4.jpg)

However, when I am on Authorization page then refresh Authorization page, it raise "internal server error"
![2](https://user-images.githubusercontent.com/10249233/235233102-7ec41aaa-a524-408e-8e54-fea74cb891f2.jpg)

**Comment by cococonuts** [comment]
Is it related to rewrite config in nginx or 
// To enable clean urls you need to set this to '' this works only in case mod rewrite is activated
    'psx_dispatch'            => 'index.php/',

**Comment by cococonuts** [comment]
More information about this issue. Does anybody knows how to fix it?

When I click "Get started" on navigation bar , in debug console, it shows 
GET https://myhost.com/index.php/consumer/page/~getting-started
It works.

when I click "Get started" on the page, in debug console, it shows 
scheme | https
host | myhost.com
filename | /apps/developer/bootstrap
response: "internal server error"

![screenshot](https://user-images.githubusercontent.com/10249233/235581831-60b6d76d-9eff-47f3-9b35-b8e0d18a5153.jpg)

**Comment by cococonuts** [comment]
Is it an issue of Angular router?

**Comment by cococonuts** [comment]
@chriskapp Thank you for response.

I added a rule in nginx which may be equivalent with RewriteCond %{REQUEST_URI} !^/apps/ in apache.
if ($uri !~ ^/apps/) {
        rewrite ^(.*)$ /index.php?$1 last;
  }
But it doesn't work.
`server {
root /var/www/fusio/html/public;
index index.html index.htm index.nginx-debian.html index.php;
server_name antaresapi.com;

location / {
  if ($uri !~ ^/apps/) {
        rewrite ^(.*)$ /index.php?$1 last;
  }
  try_files $uri $uri/ /index.php$is_args$args;
}

my nginx config
`server {
root /var/www/fusio/html/public;
index index.html index.htm index.nginx-debian.html index.php;
server_name myhost.com;

location / {
  if ($uri !~ ^/apps/) {
        rewrite ^(.*)$ /index.php?$1 last;
  }
  try_files $uri $uri/ /index.php$is_args$args;
}

location ~ \.php$ {
  include snippets/fastcgi-php.conf;
      fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;

  fastcgi_split_path_info ^(.+\.php)(/.*)$;
      include fastcgi_params;
      fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
      fastcgi_param DOCUMENT_ROOT $realpath_root;
}
}`

Could you share some documents about how to host apps in a sub-domain?

**Comment by cococonuts** [comment]
I took a look at the the rewrite rule log of nginx:
Using navigation bar(works correctly):
http upstream request: "/index.php?/index.php/consumer/page/~getting-started"

Click "Get started" in page or refresh page(works incorrectly):
http upstream request: "/apps/developer/bootstrap"
with rewrite rule:
it will be "/index.php/apps/developer/bootstrap" but with this url, it still can't go to the right place.

I just guess, it might be a issue in Angular App. 
I have not dig fusio deep. I might be wrong.

Do you have any thoughts?

**Comment by cococonuts** [comment]
I took a look at the the rewrite rule log of nginx:
Using navigation bar(works correctly):
http upstream request: "/index.php?/index.php/consumer/page/~getting-started"

Click "Get started" in page or refresh page(works incorrectly):
http upstream request: "/apps/developer/bootstrap"
with rewrite rule:
it will be "/index.php/apps/developer/bootstrap" but with this url, it still can't go to the right place.

I just guess, it might be a issue in Angular App. 
I have not dig fusio deep. I might be wrong.

Do you have any thoughts?

**Comment by cococonuts** [comment]
@chriskapp 
I found your demo site also use nginx. Would you mind sharing your nginx config?
<img width="1359" alt="image" src="https://user-images.githubusercontent.com/10249233/236060911-b86c3cd4-c4a4-4111-884a-7a7940afaabd.png">

**Comment by cococonuts** [comment]
@chriskapp Thank you very much!
I host developer app on a separated sub-domain as you said. It works for me now.

**Comment by chriskapp** [comment]
@cococonuts great that this works, in general regarding the demo, we also only use nginx as reverse proxy to our docker image so the complete rewrite config is still using  apache and mod rewrite which is configured at our [docker image](https://github.com/apioo/fusio-docker).

**Comment by dev-cz** [comment]
@cococonuts can you share an example of your nginx config for the subdomain you configured?
