### ISSUE TITLE
How does Fusio integrate OAuth2.0 licensing?

### ISSUE THREAD

**Issue by ghs619** [apioo/fusio#51]
Does Fusio not bring its own OAuth2.o authorization module? If I want to do authorization function inside it, do I need to set up a separate authentication server?

**Comment by k42b3** [comment]
Hi, Fusio uses OAuth2 for authorization so you dont need a special module for this. The details are describe at: http://demo.fusio-project.org/documentation/#!/page/getting-started

**Comment by k42b3** [comment]
I close this issue since it looks like the problem was solved. If this is not the case feel free to reopen the issue.
