### ISSUE TITLE
How to re-generate 'spec-openapi' for ReDoc after I created a new operation?

### ISSUE THREAD

**Issue by wdhwang** [apioo/fusio#510]
If I re-installed Fusio, I could see all APIs in ReDoc (like ![redoc1](https://github.com/apioo/fusio/assets/10345015/61e944b3-3d1b-431c-b6d1-67b96f0b83df)). 
But I cannot see the new API in ReDoc after I created a new operation (like ![redoc2](https://github.com/apioo/fusio/assets/10345015/0721ca6e-3935-4351-931f-e42040695664)). 
Is there any way to re-generate 'spec-openapi' for ReDoc after I created a new operation?

**Comment by chriskapp** [comment]
@wdhwang so you can simply delete the `cache/psx` folder, this should then refresh OpenAPI spec. Regarding this issue we have also recently added a fix to automatically clear the cache if you create, update or delete an operation s. https://github.com/apioo/fusio-impl/blob/master/src/EventListener/CacheInvalidateListener.php so this problem should be solved with the next release.

**Comment by wdhwang** [comment]
It works. Thanks for your prompt reply.
