### ISSUE TITLE
My swagger-ui cannot fetch 'http://master1:8080/system/export/openapi/*/*' 

### ISSUE THREAD

**Issue by wdhwang** [apioo/fusio#512]
Hi, I installed the swagger-ui from marketplace. When I opened the swagger-ui, it appeared the error message, like ![error](https://github.com/apioo/fusio/assets/10345015/d4097a25-99fa-4635-a1f4-3285a53f4006).
So I modified the index.html of swagger-ui to 'FUSIO_URL = 'http://master1:8080/system/generator/spec-openapi';'.
I am not sure this way is correct or not.

Thanks & Regards.

**Comment by chriskapp** [comment]
@wdhwang the marketplace currently provides an older 1.x version of the swagger-app, for the new release you would need to use the 2.x version s. https://github.com/apioo/fusio-apps-swaggerui/tags where we have also adjusted the url but you can also manually adjust this url like you have did. If we make the final 4.0 release we will also update the marketplace.

**Comment by wdhwang** [comment]
Thank you for your response, hope to see it soon.
