### ISSUE TITLE
What's the difference between public API and private API in Developer UI?

### ISSUE THREAD

**Issue by wdhwang** [apioo/fusio#519]
Hi, what's the difference between public API and private API in Developer UI?
Here are the all test APIs in Operation.

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/wdhwang/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/wdhwang/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
</head>

<body link="#0563C1" vlink="#954F72">

Operation | Status | Stability | Name | HTTP_Path
-- | -- | -- | -- | --
TestAPI1 | Active, Public | Experimental | TestAPI1 | /testapi1
TestAPI2 | Active, Public | Experimental | TestAPI2 | /testapi2
TestAPI3 | Active, Public | Experimental | TestAPI3 | /testapi3
TestAPI4 | Active, Private | Experimental | TestAPI4 | /testapi4

</body>
</html>

From Developer UI, I could see 3 test APIs on the left side, like the picture as follows.
![develop-ui1](https://github.com/apioo/fusio/assets/10345015/7155175d-2203-49ee-bd18-6d1057bbdc72)

But If I click the 'user' on the up-left corner, I could see 4 test APIs on the left side.
![develop-ui2](https://github.com/apioo/fusio/assets/10345015/eed1c5c7-8991-4b0c-a4df-5a2f276b5e60)

I have no idea about the difference between the two actions.

**Comment by chriskapp** [comment]
@wdhwang so "private" basically means that you need to provide an `Authorization` header containing an access token to requests this endpoint,

**Comment by wdhwang** [comment]
I got it, thanks a lot.
