### ISSUE TITLE
{Question}how do permanently delete in Fusio apps?

### ISSUE THREAD

**Issue by dyah02** [apioo/fusio#521]
Anyone could help me, please?
I face a problem when I was config this route with status Production. I want to change this route for status Development, but it can't.
I already deleted it before and created new one with the same path route, but it can't.
I already restored this route from Trash menu after deleted for re-used it with status Development but still can't.
![image](https://github.com/apioo/fusio/assets/21309334/cd3d54d6-8135-40c6-9128-bbd615f11e56)

could it be permanently deleted in Trash menu so I can use it again with the same path route?

**Comment by chriskapp** [comment]
Hi @dyah02 so in general there is an option to permanently delete a record from the trash, otherwise you could of course also delete the record directly from the database. Also it looks like you are still using an older Fusio version, in general we recommend to use the new Fusio 4.0 version.

**Comment by dyah02** [comment]
Hello @chriskapp , thank you so much for answering my question.  I will try it from database for permanently deleted. 
but I just tought, why the status Production in Route menu can't reconfigure after I created it (Fusio 2.0.0)?

this one when I config for the first time
![image](https://github.com/apioo/fusio/assets/21309334/e0e79583-08d7-4b6d-8eea-98446e05350e)

and this one when I want to change the config
![image](https://github.com/apioo/fusio/assets/21309334/a8c22c41-57a9-48fa-8d6b-15c20102457d)
