### ISSUE TITLE
Action class not found with custom PHP Action

### ISSUE THREAD

**Issue by kidino** [apioo/fusio#525]
I have been getting this error since the past few version updates. I am trying to create a new custom action with PHP. 

File location : src/Action/Sample.php
Namespace : App\Action\Sample

```php
<?php 
namespace App\Action; 

use Fusio\Engine\ActionAbstract;
use Fusio\Engine\ContextInterface;
use Fusio\Engine\ParametersInterface;
use Fusio\Engine\RequestInterface;

class Sample extends ActionAbstract {
    public function handle(RequestInterface $request, ParametersInterface $configuration, ContextInterface $context): mixed
    {
        return $this->response->build(200, [], [
            'hello' => 'world'
        ]);
    }

}
```

But I couldn't get past the Create Action modal dialog, with the error

*Action class App\Action\Sample not found in C:\laragon\www\api-gateway\vendor\fusio\engine\src\Factory\Action.php on line 50*

I am on Laragon on Windows, PHP version 8.1.10

![image](https://github.com/apioo/fusio/assets/1450433/32ad5bca-7b38-4399-8b23-4499605573c1)

![image](https://github.com/apioo/fusio/assets/1450433/92828889-dcef-4d76-b653-ae1b921202ce)

**Comment by chriskapp** [comment]
Hi @kidino starting with Fusio 4.0 you also need to load the action classes in the DI container config s.
https://github.com/apioo/fusio-sample-cms/blob/master/resources/container.php#L11

if you add this line everything should work as expected.

**Comment by kidino** [comment]
Got it! Thanks.

**Comment by kidino** [comment]
Thank you for the reply. I am closing this.
