### ISSUE TITLE
[SOLVED] - Installing on a shared hosting without ssh access

### ISSUE THREAD

**Issue by jcnavamorffe** [apioo/fusio#54]
I have a shared hosting, well, i installed on a devbox vps server step by step, then, a migrate the files and the database schema, the i update the configuration file, and i configure the document root of my subdomain... well, i can login on the back end but something weird happening with 2 things..

1.- when i try use with a mysql connection on the test module of my action, show me this:

Response 500
Primary column not available in /home/****/vendor/fusio/adapter-sql/src/Action/SqlTable.php on line 295

2.- when i test the "test-action" from video tutorial show me this:

{
    "success": false,
    "title": "PSX\\Framework\\Loader\\InvalidPathException",
    "message": "Unknown location in \/home\/***\/vendor\/psx\/framework\/src\/Loader\/Loader.php on line 133",
    "trace": "#0 \/home\/****\/vendor\/psx\/framework\/src\/Dispatch\/Dispatch.php(120): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Loader\\Context))\n#1 \/home\/****\/api.mydomain.online\/index.php(30): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#2 {main}",
    "context": "129             }\n130 \n131             return $controller;\n132         } else {\n<b>133             throw new InvalidPathException('Unknown location', $request);\n<\/b>134         }\n135     }\n136 \n137     \/**\n"
}

What do you think is happening... 

Thanks

**Comment by k42b3** [comment]
Hi, so the first error occurs because the `SqlTable` action requires a primary key on the table. This is needed to identify one record through an id. So you have correctly configured the table but I guess the table has no primary key.

The second error looks simply like the route was not found. Do you have configured the correct `psx_url` in your configuration and used the currect `route` to access the action.

**Comment by jcnavamorffe** [comment]
1. IM SURE, i ve a primary key, AUTOINCREMENT id. I dont know whats wrong.

2. DONE... ALL RIGHT. :)

thanks.

**Comment by k42b3** [comment]
ok ;), mhh could you show me the structure of the table through the sql query `DESCRIBE table_name`

**Comment by jcnavamorffe** [comment]
Field | Type | Null | Key | Default | Extra |  
-- | -- | -- | -- | -- | -- | --
id | int(11) | NO | PRI | NULL | auto_increment
numero | varchar(64) | YES |   | NULL |  
empresa | varchar(64) | YES |   | NULL |  
nif | varchar(64) | YES |   | NULL |  
direccion | varchar(256) | YES |   | NULL |  
telefono | varchar(64) | YES |   | NULL |  
email | varchar(64) | YES |   | NULL |  
notas | text | YES |   | NULL |  
customdata | text | YES |   | NULL |  
modificado | timestamp | YES |   | NULL | on update CURRENT_TIMESTAMP
creado | datetime | YES |   | NULL |  



that is happening when i migrated.... :(

**Comment by k42b3** [comment]
This looks indeed perfectly fine, I will try to reproduce the issue to see where the problem is.

**Comment by jcnavamorffe** [comment]
Response 500
Primary column not available in /home/userdev/vendor/fusio/adapter-sql/src/Action/SqlTable.php on line 295

#0 /home/userdev/vendor/fusio/adapter-sql/src/Action/SqlTable.php(127): Fusio\Adapter\Sql\Action\SqlTable->getPrimaryKey(Object(Doctrine\DBAL\Schema\Table))
#1 /home/userdev/vendor/fusio/adapter-sql/src/Action/SqlTable.php(105): Fusio\Adapter\Sql\Action\SqlTable->doGetCollection(Object(Fusio\Engine\Request), Object(Doctrine\DBAL\Connection), Object(Doctrine\DBAL\Schema\Table))
#2 /home/userdev/vendor/fusio/adapter-sql/src/Action/SqlTable.php(65): Fusio\Adapter\Sql\Action\SqlTable->doGet(Object(Fusio\Engine\Request), Object(Doctrine\DBAL\Connection), Object(Doctrine\DBAL\Schema\Table))
#3 /home/userdev/vendor/fusio/engine/src/Processor.php(72): Fusio\Adapter\Sql\Action\SqlTable->handle(Object(Fusio\Engine\Request), Object(Fusio\Engine\Parameters), Object(Fusio\Engine\Context))
#4 /home/userdev/vendor/fusio/impl/src/Service/Action/Executor.php(101): Fusio\Engine\Processor->execute(2, Object(Fusio\Engine\Request), Object(Fusio\Engine\Context))
#5 /home/userdev/vendor/fusio/impl/src/Backend/Api/Action/Execute.php(77): Fusio\Impl\Service\Action\Executor->execute(2, 'GET', Array, Array, Array, Object(PSX\Record\Record))
#6 /home/userdev/vendor/psx/framework/src/Controller/SchemaApiAbstract.php(112): Fusio\Impl\Backend\Api\Action\Execute->doPost(Object(PSX\Record\Record))
#7 /home/userdev/vendor/psx/framework/src/Filter/ControllerExecutor.php(60): PSX\Framework\Controller\SchemaApiAbstract->onPost()
#8 /home/userdev/vendor/psx/framework/src/Filter/FilterChain.php(79): PSX\Framework\Filter\ControllerExecutor->handle(Object(PSX\Http\Request), Object(PSX\Http\Response), Object(PSX\Framework\Filter\FilterChain))
#9 /home/userdev/vendor/psx/framework/src/Filter/Oauth2Authentication.php(86): PSX\Framework\Filter\FilterChain->handle(Object(PSX\Http\Request), Object(PSX\Http\Response))
#10 /home/userdev/vendor/psx/framework/src/Filter/FilterChain.php(79): PSX\Framework\Filter\Oauth2Authentication->handle(Object(PSX\Http\Request), Object(PSX\Http\Response), Object(PSX\Framework\Filter\FilterChain))
#11 /home/userdev/vendor/psx/framework/src/Filter/UserAgentEnforcer.php(41): PSX\Framework\Filter\FilterChain->handle(Object(PSX\Http\Request), Object(PSX\Http\Response))
#12 /home/userdev/vendor/psx/framework/src/Filter/FilterChain.php(79): PSX\Framework\Filter\UserAgentEnforcer->handle(Object(PSX\Http\Request), Object(PSX\Http\Response), Object(PSX\Framework\Filter\FilterChain))
#13 /home/userdev/vendor/psx/framework/src/Loader/Loader.php(158): PSX\Framework\Filter\FilterChain->handle(Object(PSX\Http\Request), Object(PSX\Http\Response))
#14 /home/userdev/vendor/psx/framework/src/Loader/Loader.php(126): PSX\Framework\Loader\Loader->executeController(Object(Fusio\Impl\Backend\Api\Action\Execute), Object(PSX\Http\Request), Object(PSX\Http\Response))
#15 /home/userdev/vendor/psx/framework/src/Dispatch/Dispatch.php(120): PSX\Framework\Loader\Loader->load(Object(PSX\Http\Request), Object(PSX\Http\Response), Object(PSX\Framework\Loader\Context))
#16 /home/userdev/api.misprocesos.online/index.php(30): PSX\Framework\Dispatch\Dispatch->route(Object(PSX\Http\Request), Object(PSX\Http\Response))
#17 {main}

**Comment by k42b3** [comment]
Ok, I think I have found the problem. If you select a connection which does not contain the table which you have provided in the config this primary error occurs. So does you connection points to a database which contains the table of the config? Otherwise you need to create a new connection with the fitting database.

To simplify debugging this problem I have just added a new exception for this case see:
https://github.com/apioo/fusio-adapter-sql/blob/master/src/Action/SqlTable.php#L259

**Comment by jcnavamorffe** [comment]
i think, the problem is the migration, the server missing something...
could you show me how install Fusio on a shared hosting without ssh access?

**Comment by jcnavamorffe** [comment]
@k42b3 Christoph, I FOUND THE PROBLEM... 

When I create the table, I forgot to put the primary key, after testing and saw the error, set the primary key and still giving error.

The problem was the CACHE, Fusio apparently stores the structure in the cache.

Delete the files from the cache and it seems to work.

It is important to note this in the documentation and if possible create cache options in the Fusion Backend.

Thanks for the support.

**Comment by k42b3** [comment]
Ok, thats great. Yes the cache exists because of performance reasons. At the moment it is only possible to delete the cache by deleting the content of the `cache/` folder. But I will try to improve the documentation of this action.
