### ISSUE TITLE
Error when reloading the page. "PSX\\Framework\\Loader\\InvalidPathException"

### ISSUE THREAD

**Issue by julioAgustin** [apioo/fusio#559]
First of all, a pleasure to greet this great community.

I installed FUSIO (I have the latest version installed) and all its corresponding applications a couple of days ago. What happens is that when I enter the FUSIO application and for some reason I want to reload the page I get the following error:

{
    "success": false,
    "title": "PSX\\Framework\\Loader\\InvalidPathException",
    "message": "Unknown location in /var/www/fusio/html/vendor/psx/framework/src/Loader/Loader.php on line 74",
    "trace": "#0 /var/www/fusio/html/vendor/psx/framework/src/Dispatch/Dispatch.php(86): PSX\\Framework\\Loader\\Loader->load()\n#1 /var/www/fusio/html/vendor/psx/engine/src/WebServer/Engine.php(51): PSX\\Framework\\Dispatch\\Dispatch->route()\n#2 /var/www/fusio/html/vendor/psx/framework/src/Environment/Environment.php(49): PSX\\Engine\\WebServer\\Engine->serve()\n#3 /var/www/fusio/html/public/index.php(29): PSX\\Framework\\Environment\\Environment->serve()\n#4 {main}",
    "context": "70              $this-&gt;eventDispatcher-&gt;dispatch(new RouteMatchedEvent($result, $context));\n71  \n72              $this-&gt;execute($context-&gt;getSource(), $result, $response, $context);\n73          } else {\n<b>74              throw new InvalidPathException(&#039;Unknown location&#039;, $request);\n</b>75          }\n76      }\n77  \n78      public function execute(mixed $source, RequestInterface $request, ResponseInterface $response, Context $context): void\n"
}

My configuration .env file is as follows:

APP_TENANT_ID=""
APP_PROJECT_KEY="APP_PROJECT_KEY"
APP_URL="https://apimanager.mnumbyla.com"
APP_APPS_URL="https://apimanager.mnumbyla.com/apps"
APP_ENV="dev"
APP_DEBUG="true"
APP_CONNECTION="pdo-mysql://userdatabase:somepassword@hostname/namedatabase"
APP_MAILER="native://default"
APP_MESSENGER="doctrine://default"
APP_MAIL_SENDER=""
APP_MARKETPLACE="off"
SDKGEN_CLIENT_ID=""
SDKGEN_CLIENT_SECRET=""

![image](https://github.com/apioo/fusio/assets/26796568/f1cd8157-9d12-4087-93fc-ff75b2bba939)

![image](https://github.com/apioo/fusio/assets/26796568/de6923e0-390f-4f6b-af06-33abf0aee64d)

![image](https://github.com/apioo/fusio/assets/26796568/da35aab9-d7ea-4606-b25c-f825b011f2f8)

I have it on Ubuntu using NGINX, I have installed a certificate so that it goes through https and I have port 80 closed by firewall and I also have http redirection to https.

Nginx site fusio configuration:

server {
    listen 443 ssl; # managed by Certbot
    listen [::]:443 ssl ipv6only=on; # managed by Certbot

    server_name apimanager.mnumbyla.com;

    root /var/www/fusio/html/public;
    index index.html index.htm index.nginx-debian.html index.php;

    ssl_certificate /certificate.pth; # managed by Certbot
    ssl_certificate_key /certificate.pth; # managed by Certbot
    include /options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /ssl-dhparams.pem; # managed by Certbot

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/var/run/php/php8.2-fpm.sock;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    error_log /var/log/nginx/fusio_error.log;
    access_log /var/log/nginx/fusio_access.log;

    location ~ /\.ht {
        deny all;
    }
}

server
{
    if ($host = apimanager.mnumbyla.com) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

        listen 80;
        listen [::]:80;
        server_name apimanager.mnumbyla.com;
    return 404; # managed by Certbot

}

I have censored some configuration paths for privacy and security reasons.

I have tried a lot to test before writing and I also read in Google forums about cases similar to this but without being resolved, I hope I have explained my problem correctly, my native language is not English but Spanish, therefore, Apologies for some translation errors.

**Comment by julioAgustin** [comment]
Update: When I downloaded the project and got ready to install, I did it without problems with the install.php script and the other applications using the php CLI. I provide this information about my installation in case it is necessary, I have followed the steps in your installation manual for Nginx.

I get the error mentioned above when reloading the pages (push F5): fusio, account and when I access some of the buttons that the developer portal has.

**Comment by chriskapp** [comment]
Hi @julioAgustin, the problem is probably that you tell nginx to redirect every request to Fusio, you would need to exclude all request to the `apps/` folder from this logic. For apache we have this rule s. https://github.com/apioo/fusio/blob/master/public/.htaccess#L2

Maybe you can try something like s.

```
location /apps {
    index  index.html;
    try_files $uri $uri/ /index.html;
}
```

so that requests at the apps/ folder are not redirected to the Fusio `index.php`

**Comment by julioAgustin** [comment]
I have tried what you have suggested, however I am getting the same error. I've even created one specifically for fusio. But, I am getting the same error.

 location /apps/fusio {
        index index.html;
        try_files $uri $uri/ /index.html;
    }

**Comment by julioAgustin** [comment]
Update: I have tried installing Apache instead of Nginx and it solved my problem.

**Comment by chriskapp** [comment]
Ok great, FYI I have also updated our documentation s. https://docs.fusio-project.org/docs/installation/nginx with a working nginx config
