### ISSUE TITLE
External URL ??

### ISSUE THREAD

**Issue by jcnavamorffe** [apioo/fusio#56]
Hello Team

Could i use a external URL.. a mean, use a external JSON source like..

https://jsonplaceholder.typicode.com/posts for example?

Thanks

**Comment by k42b3** [comment]
Hi,

yes, this is possible, you could simply enter the url as action. This proxies the HTTP request to the provided url and returns the response i.e.:

```yaml
version: 1
methods:
  GET:
    public: true
    responses: 
      200: Passthru
    action: "https://jsonplaceholder.typicode.com/posts"
```

**Comment by jcnavamorffe** [comment]
Show me This

I think is a SSL error... 

{
    "success": false,
    "title": "GuzzleHttp\\Exception\\ConnectException",
    "message": "cURL error 35: SSL connect error (see http:\/\/curl.haxx.se\/libcurl\/c\/libcurl-errors.html) in \/home\/cabox\/workspace\/fusio\/vendor\/guzzlehttp\/guzzle\/src\/Handler\/CurlFactory.php on line 186",
    "trace": "#0 \/home\/cabox\/workspace\/fusio\/vendor\/guzzlehttp\/guzzle\/src\/Handler\/CurlFactory.php(150): GuzzleHttp\\Handler\\CurlFactory::createRejection(Object(GuzzleHttp\\Handler\\EasyHandle), Array)\n#1 \/home\/cabox\/workspace\/fusio\/vendor\/guzzlehttp\/guzzle\/src\/Handler\/CurlFactory.php(103): GuzzleHttp\\Handler\\CurlFactory::finishError(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))\n#2 \/home\/cabox\/workspace\/fusio\/vendor\/guzzlehttp\/guzzle\/src\/Handler\/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))\n#3 \/home\/cabox\/workspace\/fusio\/vendor\/guzzlehttp\/guzzle\/src\/Handler\/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)\n#4 \/home\/cabox\/workspace\/fusio\/vendor\/guzzlehttp\/guzzle\/src\/Handler\/Proxy.php(51): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)\n#5 \/home\/cabox\/workspace\/fusio\/vendor\/guzzlehttp\/guzzle\/src\/PrepareBodyMiddleware.php(66): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)\n#6 \/home\/cabox\/workspace\/fusio\/vendor\/guzzlehttp\/guzzle\/src\/Middleware.php(30): GuzzleHttp\\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)\n#7 \/home\/cabox\/workspace\/fusio\/vendor\/guzzlehttp\/guzzle\/src\/RedirectMiddleware.php(70): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)\n#8 \/home\/cabox\/workspace\/fusio\/vendor\/guzzlehttp\/guzzle\/src\/Middleware.php(57): GuzzleHttp\\RedirectMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)\n#9 \/home\/cabox\/workspace\/fusio\/vendor\/guzzlehttp\/guzzle\/src\/HandlerStack.php(67): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)\n#10 \/home\/cabox\/workspace\/fusio\/vendor\/guzzlehttp\/guzzle\/src\/Client.php(277): GuzzleHttp\\HandlerStack->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)\n#11 \/home\/cabox\/workspace\/fusio\/vendor\/guzzlehttp\/guzzle\/src\/Client.php(125): GuzzleHttp\\Client->transfer(Object(GuzzleHttp\\Psr7\\Request), Array)\n#12 \/home\/cabox\/workspace\/fusio\/vendor\/guzzlehttp\/guzzle\/src\/Client.php(131): GuzzleHttp\\Client->requestAsync('GET', Object(GuzzleHttp\\Psr7\\Uri), Array)\n#13 \/home\/cabox\/workspace\/fusio\/vendor\/fusio\/adapter-http\/src\/Action\/HttpEngine.php(77): GuzzleHttp\\Client->request('GET', 'https:\/\/jsonpla...', Array)\n#14 \/home\/cabox\/workspace\/fusio\/vendor\/fusio\/adapter-http\/src\/Action\/HttpProcessor.php(48): Fusio\\Adapter\\Http\\Action\\HttpEngine->handle(Object(Fusio\\Engine\\Request), Object(Fusio\\Engine\\Parameters), Object(Fusio\\Engine\\Context))\n#15 \/home\/cabox\/workspace\/fusio\/vendor\/fusio\/engine\/src\/Processor.php(72): Fusio\\Adapter\\Http\\Action\\HttpProcessor->handle(Object(Fusio\\Engine\\Request), Object(Fusio\\Engine\\Parameters), Object(Fusio\\Engine\\Context))\n#16 \/home\/cabox\/workspace\/fusio\/vendor\/fusio\/impl\/src\/Controller\/SchemaApiController.php(275): Fusio\\Engine\\Processor->execute('2', Object(Fusio\\Engine\\Request), Object(Fusio\\Engine\\Context))\n#17 \/home\/cabox\/workspace\/fusio\/vendor\/fusio\/impl\/src\/Controller\/SchemaApiController.php(210): Fusio\\Impl\\Controller\\SchemaApiController->executeAction(Object(PSX\\Record\\Record))\n#18 \/home\/cabox\/workspace\/fusio\/vendor\/psx\/framework\/src\/Controller\/SchemaApiAbstract.php(103): Fusio\\Impl\\Controller\\SchemaApiController->doGet()\n#19 \/home\/cabox\/workspace\/fusio\/vendor\/psx\/framework\/src\/Filter\/ControllerExecutor.php(52): PSX\\Framework\\Controller\\SchemaApiAbstract->onGet()\n#20 \/home\/cabox\/workspace\/fusio\/vendor\/psx\/framework\/src\/Filter\/FilterChain.php(79): PSX\\Framework\\Filter\\ControllerExecutor->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Filter\\FilterChain))\n#21 \/home\/cabox\/workspace\/fusio\/vendor\/psx\/framework\/src\/Filter\/UserAgentEnforcer.php(41): PSX\\Framework\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#22 \/home\/cabox\/workspace\/fusio\/vendor\/psx\/framework\/src\/Filter\/FilterChain.php(79): PSX\\Framework\\Filter\\UserAgentEnforcer->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Filter\\FilterChain))\n#23 \/home\/cabox\/workspace\/fusio\/vendor\/psx\/framework\/src\/Loader\/Loader.php(158): PSX\\Framework\\Filter\\FilterChain->handle(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#24 \/home\/cabox\/workspace\/fusio\/vendor\/psx\/framework\/src\/Loader\/Loader.php(126): PSX\\Framework\\Loader\\Loader->executeController(Object(Fusio\\Impl\\Controller\\SchemaApiController), Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#25 \/home\/cabox\/workspace\/fusio\/vendor\/psx\/framework\/src\/Dispatch\/Dispatch.php(120): PSX\\Framework\\Loader\\Loader->load(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response), Object(PSX\\Framework\\Loader\\Context))\n#26 \/home\/cabox\/workspace\/fusio\/public\/index.php(30): PSX\\Framework\\Dispatch\\Dispatch->route(Object(PSX\\Http\\Request), Object(PSX\\Http\\Response))\n#27 {main}",
    "context": "182         );\n183 \n184         \/\/ Create a connection exception if it was a specific error code.\n185         $error = isset($connectionErrors[$easy-&gt;errno])\n<b>186             ? new ConnectException($message, $easy-&gt;request, null, $ctx)\n<\/b>187             : new RequestException($message, $easy-&gt;request, $easy-&gt;response, null, $ctx);\n188 \n189         return \\GuzzleHttp\\Promise\\rejection_for($error);\n190     }\n"
}

**Comment by jcnavamorffe** [comment]
done..

just put the URL without SSL, and its work

**Comment by jcnavamorffe** [comment]
it's work from the "test tool" on backend, but from the api url no.

:(

**Comment by k42b3** [comment]
The ssl error occurs probably because you have a self signed ssl certificate. By default guzzle tries to validate the certificate. What is the response if you access the API url? It could be a permission problem that Fusio has no right to write to the cache folder.

**Comment by jcnavamorffe** [comment]
the API Url is: https://jsonplaceholder.typicode.com/posts/

**Comment by jcnavamorffe** [comment]
Look the capture

![image](https://user-images.githubusercontent.com/11263629/29861262-ffa4d97a-8d68-11e7-8265-2b98089dfd3f.png)

But on the route fail.

**Comment by k42b3** [comment]
Mhh ok, could you show me the response of the url or some error so that I can try to identify the problem? Therefor enable the `psx_debug` parameter and take a look at the php error logs to find the error message. You could also try to delete the cache which may cause this problem.

**Comment by k42b3** [comment]
So I think the problem is solved otherwise please reopen the ticket or open another bug.

**Comment by ikyprima** [comment]
i have same problem , how to solve it

**Comment by chriskapp** [comment]
Hi, so you need to either use `http` in your url or use a valid SSL cert on your domain if you use `https`

**Comment by ikyprima** [comment]
> Hi, so you need to either use `http` in your url or use a valid SSL cert on your domain if you use `https`

hi chris, thanks for your respon , my problem solve :)
