### ISSUE TITLE
Fusio 5.1.1 Installation Issue

### ISSUE THREAD

**Issue by pinalgirkar** [apioo/fusio#563]
I was manually installing[ Fusio 5.1.1](https://github.com/apioo/fusio/releases/tag/v5.1.1) with following configuration: Alma Linux 8.10 (Cerulean Leopard), PHP 8.2 and MySQL 5.7, while installing the backend using this command (php bin/fusio marketplace:install fusio) it says ` "Invalid hash of downloaded app"`

<img width="437" alt="image" src="https://github.com/user-attachments/assets/3f8d1e3f-8125-415d-861d-5c963330b8b9">

Steps I followed for installation:

1. Download zip (https://github.com/apioo/fusio/releases/download/v5.1.1/fusio.zip) and extract it to a folder
2. Open .env files and made this Change APP_URL, APP_APPS_URL, APP_CONNECTION 
3. Run this command 

> php bin/fusio migrate

4. Run this command 

> php bin/fusio adduser

and fill the user details
5. Run this command (php bin/fusio marketplace:install fusio) and see the issue 

Can you please check if you are able to replicate this at your end?

**Comment by chriskapp** [comment]
Hi @pinalgirkar there was indeed a problem with the hash of the latest version but this should be now fixed, please check where you can install the app as expected.

**Comment by chriskapp** [comment]
Our markteplace has now an automatic sync so updating the version and hash happens automatically so that those errors should not occur anymore.
