### ISSUE TITLE
Return Blank

### ISSUE THREAD

**Issue by jcnavamorffe** [apioo/fusio#57]
Hi, Someone has happened that when they access the api (front) returns the blank page (code 200) ??

**Comment by k42b3** [comment]
Hi, could you turn the debug mode `psx_debug` to `true` in the configuration. Then you should see an error if you access the API. If this is not the case please take a look at the php error log. The error should provide enough information to identify the problem.

**Comment by jcnavamorffe** [comment]
ok thanks.

**Comment by k42b3** [comment]
I close this issue since it looks like the problem was solved. If this is not the case feel free to reopen the issue.
