### ISSUE TITLE
V8

### ISSUE THREAD

**Issue by jcnavamorffe** [apioo/fusio#58]
I try to use a V8 Processor but 

It looks like the PHP V8 extension is not installed. Please take a look at https://github.com/pinepain/php-v8 in /home/cabox/workspace/fusio/vendor/fusio/adapter-v8/src/Action/V8Engine.php on line 60

I try with: composer require --dev pinepain/php-v8-stubs but isn't work... how to install the library on Fusio?

Thanks

**Comment by k42b3** [comment]
Ok, if you want to work with the V8 engine you need to install the php v8 extension. This is a native PHP extension which you can not install through composer. The installation is a bit more complicated, depending on your current system. For ubuntu you can use (taken from the php-v8 readme):

```
$ sudo add-apt-repository -y ppa:ondrej/php
$ sudo add-apt-repository -y ppa:pinepain/php
$ sudo apt-get update -y
$ sudo apt-get install -y php7.1 php-v8
```

**Comment by jcnavamorffe** [comment]
Hello, im sorry for the delay...

ok i try to install...

About a way.. Fusio has some advanced documentation for using PHP processor or manage the processors?

Thanks

**Comment by k42b3** [comment]
No problem, if you want to use the PHP processor you have to provide an PHP file to the action. The file should look like i.e.: https://github.com/apioo/fusio/blob/master/src/Todo/collection.php

Then there is the readme file: https://github.com/apioo/fusio/blob/master/src/README.md in the src folder which describes roughly each processor. Also we have the documentation at: http://fusio.readthedocs.io/en/latest/deploy.html#connection
which basically describes each connection type and the API which gets returned by this connection. This should help to develop an action in PHP. But we want to improve the documentation so it would be interesting to know what you mean exactly by "managing" the processors.

**Comment by k42b3** [comment]
It looks like the problem is solved. If there is still a problem please reopen the issue or open another bug.
