### ISSUE TITLE
Can't log in - Could Not Authenticate

### ISSUE THREAD

**Issue by nsherzog** [apioo/fusio#581]
Hello, 

I installed a fresh install of Fusio. I ran both bin/fusio migrate and bin/fusio adduser without errors. When I go to login to /apps/fusio I get the error "Could Not Authenticate."

I noticed a couple of errors in the javascript console:
- Failed to load resource https://api.coremarketplace.org/consumer/identity?appKey=[censored]
- Failed to load resource https://api.coremarketplace.org/authorization/token
- Failed to load resource https://api.coremarketplace.org/apps/fusio/login

I saw in a number of other posts that mod_rewrite may be a culprit. However I've verified that it's definitely turned on and I have all the RewriteCond/RewriteRule lines in my .htaccess file. Obviously something's not working but I'm not sure where to look. Assistance appreciated.

**Comment by chriskapp** [comment]
Hi @nsherzog can you show me the `log/app.log` file and also the general php error logs.

**Comment by nsherzog** [comment]
Hi. Thanks for your quick response. There's nothing showing up as errors in either of those logs. It's baffling.

**Comment by nsherzog** [comment]
Good morning. I should add that I don't have admin control over the server. The server is running php v8.2.2. I've compared the base site config and my .htaccess file against what's recommended in the docs (and what's running on my test server which works great btw) and the only line that's different is AllowOverride. The docs say this should read "AllowOverride All" where as on the server it reads "AllowOverride Options AuthConfig FileInfo Indexes Limit." According to the Apache manual these lines are effectively the same? Maybe they're not? Maybe I'm looking in the wrong place for what is wrong.

**Comment by chriskapp** [comment]
ok, I have just noticed that the `public/` url is available s.
https://api.coremarketplace.org/public/apps/fusio

do you have created a fitting virtual host where the DocumentRoot points to the `public/` folder s.
https://docs.fusio-project.org/docs/installation/apache

Also it looks like the Fusio `APP_URL` config is not correct since it it contains the `public/` part.

**Comment by nsherzog** [comment]
Yeah - I was suspicious that the server document root setting wasn't working as advertised, so I removed the document root setting and reinstalled and left everything at default. I was hopeful but it still didn't let me log in.

I have since reset the directory root to 'public' and adjusted the .env file to fix the URL roots and fixed the the index.html in the /public/apps/fusio directory to fix that URL root as well. Now I can get all the way up to the actual login screen, but I still can't login. Same error as before. Nothing is showing up in either the log/app.log or the server error_log

**Comment by nsherzog** [comment]
Don't know if this matters, but when fusio tries to access /consumer/identity and /authorization/token the server returns a 403 error which suggests an authorization error?

**Comment by nsherzog** [comment]
So here's a thought: is it possible that there's something wrong with my admin account? I used the bin/fusio adduser command to add it and it appears to be in the database. When I do a simple auth request to my test fusio server (working) using /consumer/login [as outlined at https://docs.fusio-project.org/docs/concepts/authorization] I get a working token. When I try the same thing against the problem fusio server, I get an 'access denied' error.

**Comment by nsherzog** [comment]
Hello - 

I found the issue. Per the explanation posted here: https://stackoverflow.com/questions/14555996/no-input-file-specified it appears the code might be looking for a PATH_INFO variable where none existed in my server config. Altering the .htaccess file by editing this line fixed the problem by passing the URI as a QUERY_STRING variable which the code could find.
RewriteRule ^(.*)$ index.php?/$1 [L]
(note the inclusion of the ? - makes all the difference)

Hopefully this helps others with similar server config problems.

**Comment by Rob3487** [comment]
Hello,

I'm experiencing the same issue: "Could not authenticate" message.

I have applied the changes to the .htaccess, and the vhosts file ("RewriteRule ^(.*)$ index.php?/$1 [L]"),   ...however this has not remedied the problem for me.

I CAN login when using NO https:// in the address bar, however when using https:// there appears to be some dependencies that are attempting to load insecurely, please see the image attached.

I do have "https://api-01.xxxxxxxx.com" within the .env file for both the APP_URL and the APP_APPS_URL variables.

Any support is welcomed - thanks in advance.

![Image](https://github.com/user-attachments/assets/8bd91b7a-9324-4313-b9b4-e4fa7f660783)

**Comment by chriskapp** [comment]
Hi @Rob3487, which FUSIO_URL have you configured at the `.env` file, if you want to use `https` make sure it also start with `https`. You can also check the url by simply looking at the `index.html` source code, there is the `FUSIO_URL` variable.

**Comment by Rob3487** [comment]
Hi @chriskapp, thank you for your response.

When looking at the FUSIO_URL variable within the index.html it appears clear that this is the problem. 

I have caching turned off on cloudflare and purged all, I've cleard the browser cache, I've tried with multiple browsers types, and chrome using 'guest mode'.

Still the FUSIO_URL is without the "https".


Please see in the below image of my settings within the .env file, and also the html within the index.html file.

![Image](https://github.com/user-attachments/assets/85698caa-9f79-4d56-affd-18496c4c88d2)
