### ISSUE TITLE
Inactive operation is still reachable by clients

### ISSUE THREAD

**Issue by gpenin** [apioo/fusio#582]
Using dockerized Fusio 5.1.5, it seems that an operation that has been set to inactive is still reachable by clients.

Please find an example in attachment.

Regards,

![client_response](https://github.com/user-attachments/assets/5524448c-fbfa-4fab-9df7-28ff5ca0cb83)
![inactive_operation](https://github.com/user-attachments/assets/acdcb04e-24ad-492c-b875-f9b93cbdaa42)

**Comment by chriskapp** [comment]
Hi @gpenin this is indeed currently a wrong behaviour, I have just provided a commit s. https://github.com/apioo/fusio-impl/commit/201697160ac9bf285877caf3decd622280512cf7 to fix this which will be available in the next release

**Comment by gpenin** [comment]
Hi @chriskapp, I can confirm it now works as expected with your fix. Thanks a lot for all your work.
