### ISSUE TITLE
Delete cache on deployment

### ISSUE THREAD

**Issue by chriskapp** [apioo/fusio#59]
If we use the deploy command `bin/fusio deploy` to deploy an API configuration there are several entities which may have changed i.e. request/response schema, database schema etc. Since we dont exactly which of those are cached (i.e. the SqlTable action caches the table schema) we should delete the complete cache on deployment so that all caches are renewed. At the moment the user has to manually delete the cache.

**Comment by ratsey** [comment]
Cache should also be cleared when manually updating Actions in the backend UI.  For example, changing a `SELECT` statement on a `GET` operation will resolve to `No body returned for response` until the cache is reset or times out.

**Comment by chriskapp** [comment]
This is true, I have added this also to the 2.1.8 milestone.
