### ISSUE TITLE
Using JSON data from payload with DELETE Operations

### ISSUE THREAD

**Issue by gpenin** [apioo/fusio#596]
Hi,

We are trying to use Fusio API in front of our old API service (in order to achieve a smooth migration), but some of our DELETE API calls use JSON data from the payload.

It seems that DELETE Operations in Fusio API do not process/extract data from the payload ?

Is it possible for us to configure a specific DELETE behaviour (at least during our first migration step) so that the JSON data from the payload could be transmitted to the targeted Action (Fusio.Adapter.Http.Action.HttpProcessor) ?

Thanks a lot for your help.

Regards,

**Comment by chriskapp** [comment]
Hi @gpenin yes this is correct, Fusio only parses payloads for `POST`, `PUT` and `PATCH` methods, all other payloads are ignored, so currently there is no workaround for this.

**Comment by gpenin** [comment]
Hi @chriskapp,

Thanks for your help. We'll use an HAProxy ACL in order to directly forward those requests to the PHP Worker, until we move towards a standard usage.

Regards,
