### ISSUE TITLE
Add redis cache option in configuration.php

### ISSUE THREAD

**Issue by AhmadShamli** [apioo/fusio#61]
Hii,

How do I add redis cache option in configuration.php..?

`//'psx_cache_factory'       => null,`

thanks.

**Comment by k42b3** [comment]
Hi, so this is simple possible:

```php
'psx_cache_factory'       => function($config, $namespace){
	$client = new \Predis\Client([
		'scheme' => 'tcp',
		'host'   => '10.0.0.1',
		'port'   => 6379,
	]);

	return new \Doctrine\Common\Cache\PredisCache($client);
},
```

but therefor you need to install the `predis` library through composer.

```
composer require predis/predis
```

More information about the predis library at: https://github.com/nrk/predis

**Comment by AhmadShamli** [comment]
Thanks...it works. no more file cache created in cache folder.
