### ISSUE TITLE
Run Fusio installed from "docker pull fusio/fusio"

### ISSUE THREAD

**Issue by JAugustoGuimaraes** [apioo/fusio#62]
Hi All,

How could I run Fusio installed from "docker pull fusio/fusio"?
How shoud it be configured and be the docker command line?
There is any doc?

Thanks

**Comment by k42b3** [comment]
Hi,

so the best way is at the moment to clone the repository https://github.com/apioo/fusio-docker and run the command: `docker-compose up`

This creates a running environment by setting up a fusio, mysql and memcache instance.

**Comment by JAugustoGuimaraes** [comment]
Hi,

In our environment we can only run docker images!  :(

When you will have a fusio docker image available?

...Like we can do with https://hub.docker.com/_/kong/   or  https://getkong.org/install/docker/

**Comment by k42b3** [comment]
Inspired by the link you have posted I have adjusted the readme, which shows howto use the fusio docker image without docker-compose. Please take a look at https://github.com/apioo/fusio-docker#run and let me now whether this works for you.

**Comment by JAugustoGuimaraes** [comment]
# **Thank you!** 
I will start evaluate the Fusio :)
