### ISSUE TITLE
Is there any way to create user using action?

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#70]
The use case I have is custom registration where more than username, email, & password needed.

My current approach is:
* access `/customer/register` via HTTP connection.
* since it does not return the user's `id`, I have to make query to `fusio_user` database. Selecting by username.
* then do my thing with that user's `id`

Is there already API to do this?

**Comment by k42b3** [comment]
If you want to use internal services of Fusio i.e. to create a user you can use a PHP class as action. The following action shows how you can access the user service to create a user:

```php
<?php

namespace App\Todo;

use Fusio\Engine\ActionAbstract;
use Fusio\Engine\ContextInterface;
use Fusio\Engine\ParametersInterface;
use Fusio\Engine\RequestInterface;
use Fusio\Engine\Factory\ContainerAwareInterface;
use Fusio\Impl\Authorization\UserContext;
use Fusio\Impl\Table;
use Psr\Container\ContainerInterface;

class UserAction extends ActionAbstract implements ContainerAwareInterface
{
    /**
     * @var \Psr\Container\ContainerInterface
     */
    protected $container;

    public function handle(RequestInterface $request, ParametersInterface $configuration, ContextInterface $context)
    {
        /** @var \Fusio\Impl\Service\User $userService */
        $userService = $this->container->get('user_service');

        $userId = $userService->create(
            Table\User::STATUS_CONSUMER,
            'username',
            'user@host.com',
            'password',
            null,
            UserContext::newContext($context->getUser()->getId(), $context->getApp()->getId())
        );

        return $this->response->build(200, [], [
            'message' => 'User created',
        ]);
    }

    public function setContainer(ContainerInterface $container)
    {
        $this->container = $container;
    }
}
```

Despite this solution I think it would be a great idea to provide a parameters column for each user where someone could store variable key/value entries. A user could provide those key/value entries to the `/customer/register` endpoint. In an action you could access those parameters through the context `$context->getUser()->getParameter('key')`. Would this help you to solve your use case?

**Comment by zaniar** [comment]
Yes, it helps me.

I can use other internal services the same way, right?
It would be good if we have documentation of this.

**Comment by k42b3** [comment]
Great, yes so you can take a look at all available services at: https://github.com/apioo/fusio-impl/blob/master/src/Dependency/Services.php

The documentation regarding internal development with Fusio is currently lacking but I have plans to improve this if we have the 1.0 version released. Probably we need a separate developer manual for those information.
