### ISSUE TITLE
Action drop down only displayed part of actions

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#76]
Some action can not be selected from the drop down because they did not displayed there.

fusio-backend commit 318efe2166dc0d0cc26c066db131e0a7efcba7e2

**Comment by k42b3** [comment]
I could reproduce the problem and you are right the routes/cronjob dialog has also a limit of 16 entries on the action and schema dropdown. I have commited a fix https://github.com/apioo/fusio-backend/commit/f497634096c3aae52e7098400064f6a6044b19ee to select all routes. And thanks for the feedback this helps greatly to improve Fusio!

**Comment by zaniar** [comment]
That fix it. :smiley: 

Thanks.
