### ISSUE TITLE
Do Fusio allow single email to have multiple username?

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#80]
When I looking at `Fusio\Impl\Service\User->create`, it has these lines:
```php
        // check whether user exists
        $condition  = new Condition();
        $condition->notEquals('status', Table\User::STATUS_DELETED);
        $condition->equals('name', $name);
```
So I guess it is possible to have multiple username with single email.

Is it intended?

**Comment by k42b3** [comment]
Hi, so the table `fusio_user` has at the moment an unqiue index on the `name` and `email` column. Basically this means that the name and email must be unqiue across all users and you can not use a name or email twice. If you try to use the same email twice the database should throw an error.

**Comment by zaniar** [comment]
Should Fusio check it before trying to insert the email into database? So the user can get feedback that the email he/she trying to use is already registered, just like the username.

**Comment by k42b3** [comment]
Yes I think this is good idea, we should throw a proper exception in case the email already exists. This is better then an error from a database which is probably confusing.

**Comment by k42b3** [comment]
So just for your information, I have implemented the email detection so that the user service throws now a fitting exception see https://github.com/apioo/fusio-impl/commit/9d5f0a8f22dbd18ec132fbe2e49cb8d36ce1b9cc
