### ISSUE TITLE
Handle preflight request for every end points

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#82]
Currently `OPTIONS` request to end point `/todo` give me `405` response.
I suspect the other end point will do the same.

`/consumer/login` handle `OPTIONS` request just fine.

**Comment by k42b3** [comment]
Hi, yes this is true, currently the user API endpoints do not support OPTIONS request. Only the internal API endpoints handle those. But I think it would be good to cover those also for user endpoints to support i.e. CORS. I have already commited a first patch at https://github.com/apioo/fusio-impl/commit/5235edd38a8c5a98983571914e66a861d8ed80d3 I have plans to release soon the first 1.0 RC1 which then includes this fix.

**Comment by zaniar** [comment]
It worked, but it seems missing `Access-Control-Allow-Headers`.

**Comment by k42b3** [comment]
Ok, great. I am actually not exactly sure which HTTP headers we should return in the `Access-Control-Allow-Headers` header. It maybe also depends on specific headers per action. But as far as I know the browser should handle normal HTTP headers like i.e. `Content-Type` also if there is no `Access-Control-Allow-Headers` header.

**Comment by k42b3** [comment]
I have just released the first RC1 which should solve this problem. Therefore I will close this issue, if there are still other problems with the CORS headers please let me know.
