### ISSUE TITLE
Add user_approval setting

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#83]
`user_approval` will allow us to chose whether new users will need to activate their account via email or not.

It could be named `user_activation` or anything.

**Comment by k42b3** [comment]
This would be easy possible with a few changes at https://github.com/apioo/fusio-impl/blob/master/src/Service/User/Register.php#L87 There we could simply set the user directly to active. On the other side this would allow users to register with an invalid email, but in then end we have a captcha protection and a user can always register with a fake email. So I think we should add such a setting.

**Comment by k42b3** [comment]
Implemented in the latest 1.0.0-RC2 release
