### ISSUE TITLE
PHP's null encoded into JSON's empty string

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#84]
It should be encoded into `null`.

PHP's `json_encode` do this correctly.

**Comment by k42b3** [comment]
To better understand the problem. Do you mean that if you produce a response in an action like:
```
return $response->build(200, [], [
    'bar' => 'baz',
    'foo' => null,
]);
```

that then the `foo` key gets removed from the output?

**Comment by zaniar** [comment]
```php
return $response->build(200, [], [
    'bar' => 'baz',
    'foo' => null,
]);
```

will produce

```json
{
  "bar": "baz",
  "foo": "null"
}
```

It should be
```json
{
  "bar": "baz",
  "foo": null
}
```

**Comment by k42b3** [comment]
I could reproduce the problem and this was a bug in the underlying serialization library. I have commited a fix to handle null values correctly see: https://github.com/apioo/psx-data/commit/bba27157cd738a9b612bbaefb20cb7e62d737837

This fix is then included in the next release.
