### ISSUE TITLE
Update fusio/impl from <= 1.0.1 to >= 1.0.2 will makes action update & connection update in backend break.

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#85]
The problem is `Fusio/Impl/Backend/Api/Action/ListActions` is no longer exist. It is now replaced by `Fusio/Impl/Backend/Api/Action/Index` & `Fusio/Impl/Backend/Api/Action/Form`. But, in the database, table `fusio_routes` field `controller` for route `/backend/action/list` & `/backend/action/form` is not updated.

I think it is should be handled when we execute `bin/fusio system:install`.

I have not check it with Connection Update. But I suspect it is the same, judging from the message I got in Chrome DevTools.

**Comment by k42b3** [comment]
Thansk for the hint. Every version has a `executeUpgrade` Method which should update those routes but maybe the logic is missing to adjust already existing routes. I will check/fix this if this is not handeled correctly.

**Comment by k42b3** [comment]
The latest v1.0.0-RC1 should include a fix for this problem. So you should be able to update a Fusio `<= 1.0.1` to the latest version. Please let me know whether this works as expected.

**Comment by k42b3** [comment]
I will close this issue since it looks like the problem is fixed, if there is still an issue please reopen the ticket.
