### ISSUE TITLE
Failed to load resource: the server responded with a status of 401 (Unauthorized)

### ISSUE THREAD

**Issue by koswarabilly** [apioo/fusio#88]
i have logged in to fusio dashboard but it dont show anything
the console log error this : 

> Failed to load resource: the server responded with a status of 401 (Unauthorized)

is it my issue or the fusio issue?

**Comment by koswarabilly** [comment]
![screenshot from 2017-11-01 15-54-36](https://user-images.githubusercontent.com/29243760/32267610-65300fd0-bf1e-11e7-916a-b33dd9948993.png)

see the image please help me as soon as possible

**Comment by k42b3** [comment]
Hi, it looks like this is a problem with your webserver. The webserver does not forward the `Authorization` header to fusio, in most cases this problem exists beacse the Apache module `mod_rewite` is not activated. So please check whether this module is active.

**Comment by koswarabilly** [comment]
in my case, i have enabled mod_rewrite using a2enmod rewrite, it was enabled but still give me the error of authorization like above, what i did was i add this to my 000-default.conf file:

```
<Directory /var/www/fusio/public>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride all
                Order allow,deny
                allow from all
    </Directory>
```

i think you should update your documentation.... :)

**Comment by k42b3** [comment]
Ok great, I have added a apache default conf which can be easily used at: https://github.com/apioo/fusio/blob/master/build/apache.conf 
and also I have update the conf in the installation doc.
