### ISSUE TITLE
php processor error

### ISSUE THREAD

**Issue by koswarabilly** [apioo/fusio#93]
i am getting this error when trying to use php processor action

![screenshot from 2017-11-07 09-56-10](https://user-images.githubusercontent.com/29243760/32474950-f2ce075c-c3a1-11e7-8625-cdef7e5f650c.png)

this is  my code

```
<?php
  // Initialize Guzzle client
  $client = new GuzzleHttp\Client();
  require './vendor/autoload.php';
  // Create a POST request
  $response = $client->request(
      'POST',
      'http://192.168.51.45:8787/erp-ws-main/ws/postdata',
      [
          'form_params' => [
              'responseCode' => 'GET-DATA-LANGGANAN',
              'requestParam' => '{"GET_COLUMN":["KODE_LANGGANAN","NAMA_LANGGANAN","ALAMAT","NAMA_KOTA","NAMA_KATEGORI","NAMA_SKALA","TELEPON","HP"]}',
              'authParam' => '{}'
          ],
          'headers' =>[
            'Accept' => 'application/x-www-form-data',
            'Content-Type' => 'application/x-www-form-data'
          ]
      ]
  );

  // Parse the response object, e.g. read the headers, body, etc.
  $headers = $response->getHeaders();
  $body = $response->getBody();

  // Output headers and body for debugging purposes
  var_dump($headers, $body);

?>

```
am i doing it wrong?

**Comment by koswarabilly** [comment]
i copied postman code which is this

```
<?php

$curl = curl_init();

curl_setopt_array($curl, array(
  CURLOPT_PORT => "8787",
  CURLOPT_URL => "http://192.168.51.45:8787/erp-ws-main/ws/postdata?responseCode=GET-DATA-LANGGANAN&requestParam=%7B%22GET_COLUMN%22%3A%5B%22KODE_LANGGANAN%22%2C%22NAMA_LANGGANAN%22%2C%22ALAMAT%22%2C%22NAMA_KOTA%22%2C%22NAMA_KATEGORI%22%2C%22NAMA_SKALA%22%2C%22TELEPON%22%2C%22HP%22%5D%7D&authParam=%7B%7D",
  CURLOPT_RETURNTRANSFER => true,
  CURLOPT_ENCODING => "",
  CURLOPT_MAXREDIRS => 10,
  CURLOPT_TIMEOUT => 30,
  CURLOPT_HTTP_VERSION => CURL_HTTP_VERSION_1_1,
  CURLOPT_CUSTOMREQUEST => "POST",
  CURLOPT_HTTPHEADER => array(
    "cache-control: no-cache",
    "content-type: application/x-www-form-urlencoded",
    "postman-token: cff61310-1d25-c8a5-5b77-5395a3a69db6"
  ),
));

$response = curl_exec($curl);
$err = curl_error($curl);

curl_close($curl);

if ($err) {
  echo "cURL Error #:" . $err;
} else {
  echo $response;
}
```

i am able to get this respond even though fusio return Response 500
![screenshot from 2017-11-07 10-46-58](https://user-images.githubusercontent.com/29243760/32476299-0111c752-c3a9-11e7-8a89-e5242d0bf04c.png)

and when i create the route and try it , i am able to get data like this 
![screenshot from 2017-11-07 10-47-44](https://user-images.githubusercontent.com/29243760/32476316-1c579c62-c3a9-11e7-8973-d96ec0a4153d.png)

why fusio return error?
what if i want to post data with certain parameters with my app through fusio to a certain webservices
will fusio be able to get the parameters if i type it this way ??

> http://127.0.0.1/phppro?respondcode={'whateveritis'}

**Comment by zaniar** [comment]
Fusio return error because you did not return anything.
Fusio expecting a response to be returned by an action.

instead of
```php
$response = curl_exec($curl);
echo $response;
```

try

```php
$result= curl_exec($curl);
return $response->build(200, [], json_encode($result));
```

Do not use `$request`, `$context`, `$connector`, `$response`, `$processor`, `$logger`, & `$cache` to store any value in PHP action. It is reserved by Fusio.

**Comment by koswarabilly** [comment]
thankyou @zaniar now i have another issue
the return json is stringified json

![screenshot from 2017-11-07 12-34-34](https://user-images.githubusercontent.com/29243760/32478556-095d1e66-c3b8-11e7-969c-b21c4c81a9b9.png)

**Comment by koswarabilly** [comment]
thankyou @zaniar it works really well

**Comment by k42b3** [comment]
@zaniar is correct, you need to parse the response of your http request. Beside I would recommend to use `json_decode` instead of `json_encode` because then you return a PHP structure and Fusio can also transform the response into other Content-Types if needed. If you use `json_encode` it simply returns a static string which cant be changed. I.e. you can test this behaviour by adding i.e. a `format=jsonx` query parameter.

Regarding your first problem, this is because Guzzle throws be default an Exception if it receives an Status-Code >= 400 you need to disable this bevahiour through the option `http_errors => false`. You can also take a look at the HTTP adapter which makes also an Guzzle request: https://github.com/apioo/fusio-adapter-http/blob/master/src/Action/HttpEngine.php#L76

**Comment by zaniar** [comment]
Just as @k42b3 said, it should be `json_decode` since `curl_exec` is returning a `string`.
