### ISSUE TITLE
Invalid access token should use status code 401 instead of 400

### ISSUE THREAD

**Issue by zaniar** [apioo/fusio#97]
Status code 400 is too general.

Invalid token should be treated the same as no access token.
Currently, no access token use 401 which is correct.

some references:
https://stackoverflow.com/questions/20613088/what-status-code-should-i-use-when-session-token-is-invalid
https://stackoverflow.com/questions/8855297/token-expired-json-rest-api-error-code

**Comment by k42b3** [comment]
Yes you are right, 401 is a better response. I have fixed (https://github.com/apioo/psx-framework/commit/a182c6b3d53e4583a957f7381c43d0f50e0cb999) the endpoint to use a 401 response. This is then included in the next RC2 release.

**Comment by k42b3** [comment]
Fixed in the latest 1.0.0-RC2 release
