### ISSUE TITLE
how to get body in action (parameter parsing using postman)

### ISSUE THREAD

**Issue by CNX09** [apioo/fusio#98]
how can i get "body" parameter where i parsing in body postman..
![image](https://user-images.githubusercontent.com/22588362/32936420-c613a502-cba6-11e7-94bd-cd5e20f3ac83.png)

![image](https://user-images.githubusercontent.com/22588362/32936243-0af96162-cba6-11e7-9dbd-418dc61bdef1.png)
**form: { key1: 'my_body' } };**

what's method should i use to get the "form" json ?

which's the only available method is
![image](https://user-images.githubusercontent.com/22588362/32936307-596a90be-cba6-11e7-8485-3abd550c7f44.png)

here is my action :
![image](https://user-images.githubusercontent.com/22588362/32936321-6a4fda1a-cba6-11e7-8c03-a7a36091e692.png)

when im using **request.getBody()** , the return is {} / blank

i think the request.getBody() , is the body request from the fusio application :
![image](https://user-images.githubusercontent.com/22588362/32936392-aebf75de-cba6-11e7-9809-c73ac746554a.png)

**Comment by k42b3** [comment]
Hi, yes this is right, the `request.getBody()` should return the data of the request. Do you have used the correct request method i.e. POST? If you use GET the request body is not available and Fusio will return `{}`.

Otherwise the `resp.getBody()` of the HTTP request should return a string, so you need to use `JSON.parse(resp.getBody())` to transform this also into a JSON structure.

**Comment by CNX09** [comment]
yes, i'm already doing right method "POST". but if im post with POSTMAN, the return data always {}
![image](https://user-images.githubusercontent.com/22588362/32998351-f0a8b730-cdcc-11e7-9099-71acfeed2423.png)

if im using body in fusio.. the return data is good..
![image](https://user-images.githubusercontent.com/22588362/32998360-080ba522-cdcd-11e7-8cec-508a96ff5175.png)

**Comment by k42b3** [comment]
Ok, on your route `/api/getStdCostStructure` which request schema do you have configured? For testing you should use the `Passthru` schema which redirects all incoming data.

**Comment by CNX09** [comment]
yes, im use _Passthru Schema_ ..
