### ISSUE TITLE
cant use fusio object inside custom class and function

### ISSUE THREAD

**Issue by AhmadShamli** [apioo/fusio#99]
Hi,
I'm adding Action with PhpProcessor. Ex: /var/www/fusio/src/apps.php

Within apps.php:
<pre>
$data = NULL;
$connection = $connector->getConnection('DBConn');
if (!empty($request->getUriFragment('type'))) {
	$qtype = $request->getUriFragment('type');
}
if ($qtype == 'ask') {
		include_once "inc/ask.php";
		$data = ask::any($connection);
	}
return $response->build(200, [], [
		'data' => $data
	]);
</pre>

Within inc/ask.php:
<pre>
class ask {
public static function any($connection) {
$answer = $connection->query("select answer from table");
return "answer";
}
}
</pre>

However I'm getting an error as below.

<pre>
FastCGI sent in stderr: "PHP message: psx.ERROR: Cannot access empty property in /var/www/fusio/vendor/psx/data/src/Visitor/StdClassSerializeVisitor.php on line 39
PHP message: Stack trace:
PHP message: #0 /var/www/fusio/vendor/psx/data/src/Visitor/SerializeVisitorAbstract.php(75): PSX\Data\Visitor\StdClassSerializeVisitor->addObjectValue('', 27591, Object(stdClass))
PHP message: #1 /var/www/fusio/vendor/psx/data/src/GraphTraverser.php(73): PSX\Data\Visitor\SerializeVisitorAbstract->visitObjectValueEnd()
PHP message: #2 /var/www/fusio/vendor/psx/data/src/GraphTraverser.php(82): PSX\Data\GraphTraverser->traverseObject(Array, Object(PSX\Data\Visitor\StdClassSerializeVisitor))
PHP message: #3 /var/www/fusio/vendor/psx/data/src/GraphTraverser.php(91): PSX\Data\GraphTraverser->traverseValue(Array, Object(PSX\Data\Visitor\StdClassSerializeVisitor))
PHP message: #4 /var/www/fusio/vendor/psx/data/src/GraphTraverser.php(71): PSX\Data\GraphTraverser->traverseValue(Array, Object(PSX\Data\Visitor\StdClassSerializeVisitor))
PHP message: #5 /var/www/fusio/vendor/psx/data/src/GraphTraverser.php(47): PSX\Data\GraphTraverser->traverseObject(Array, Object(PSX\Data\Visitor\StdClassSerializeVisitor))
PHP message: #6 /var/www/fusio/vendor/psx/data/src/Writer/Json.php(44): PSX\Data\GraphTraverser->traverse(Array, Object(PSX\Data\Visitor\StdClassSerializeVisitor))
PHP message: #7 /var/www/fusio/vendor/psx/data/src/Processor.php(155): PSX\Data\Writer\Json->write(Array)
PHP message: #8 /var/www/fusio/vendor/psx/framework/src/Controller/ControllerAbstract.php(343): PSX\Data\Processor->write(Object(PSX\Data\Payload))
PHP message: #9 /var/www/fusio/vendor/psx/framework/src/Controller/ControllerAbstract.php(270): PSX\Framework\Controller\ControllerAbstract->setResponse(Array, N
</pre>

**Comment by k42b3** [comment]
Hi, mhh the code looks ok to me. From the error message I would guess that the `$data` variable contains empty array keys which could then probably produce this error. Could you show me the exact data structure which you pass to `$response->build(200, [], [...])` so that I can try to reproduce/debug this issue.

**Comment by AhmadShamli** [comment]
Hi,
Below query inside class (inc/ask.php) didnt return any data. You can test with any database.
<pre>
class ask {
public static function any($connection) {
$answer = $connection->query("select answer from table");
return $answer;
}
}
</pre>
While below is OK.
<pre>
class ask {
public static function any() {
$answer = "answer";
return $answer;
}
}
</pre>

**Comment by k42b3** [comment]
Ok, could you try to use the `fetchAll` method on the connection instead of `query`. The `fetchAll` method returns the complete result as array. The `query` method returns a statment object which Fusio can not resolve. You can take a look at all available methods at the [reference](http://www.doctrine-project.org/api/dbal/2.5/class-Doctrine.DBAL.Connection.html).

**Comment by AhmadShamli** [comment]
![image](https://user-images.githubusercontent.com/1076016/32981092-9b66da6a-ccad-11e7-9f0d-ea6a01d153c0.png)

as above, I'm using PhpStorm 2017. and it says the method was not found even is_object return true.

**Comment by k42b3** [comment]
Please try this code:

```php
<?php

class ma_mttr
{
    public static function ma_get(\Doctrine\DBAL\Connection $connection, $qduration)
    {
        return $connection->fetchAll('SELECT * FROM PROBSUMMARYM1');
    }
}

```

**Comment by AhmadShamli** [comment]
@k42b3 thanks....able to use the class now...
